name: Test

on:
   pull_request:
     branches: [ main ]

jobs:
   test_pull_request:
      runs-on: ubuntu-latest
      steps:
        -uses: actions/checkout@v2
        -uses: actions/setup-node@v1
         with:
           node-version: 12
        - run: composer self-update 1.10.17
        - run: make dev
        - run: npm run tests:static
