-- --------------------------------------------------------------------------------------------
-- SQL patch for the refactor of the WIAT_III_SA instrument                                  --
--                                                                                           --
-- Does the following:                                                                       --
--                                                                                           --
-- 1. Renames table WIAT_III_SA to WIAT_III_SA_backup                                        --
-- 2. Recreates table WIAT_III_SA: all scores columns are renamed according                  --
--    to the following nomenclature:                                                         --
--    <Section ID>_<domain ID>_<score type ID>                                               --
--    For example, the raw score of domain 'Listening Comprehension' for section             --
--    'Subtest Score Summary' is stored in SSS_LC_RAW.                                       --
-- 3. Transfers the followiong fields from WIAT_III_SA_backup to WIAT_III_SA:                --
--      CommentID, UserID, Examiner, Testdate, Data_entry_completion_status,                 --
--      Date_taken, Candidate_Age, Window_Difference, File_name, other_comments, Data_dir    --
--                                                                                           --
-- It is assumed that after this patch is run, all WIAT_II_SA score files will be uploaded   --
-- again into the database to re-populate the score columns.                                 --
--                                                                                           --
-- --------------------------------------------------------------------------------------------


ALTER TABLE WIAT_III_SA RENAME TO WIAT_III_SA_backup;

CREATE TABLE WIAT_III_SA (
    `CommentID` varchar(255) NOT NULL DEFAULT '',
    `UserID` varchar(255) DEFAULT NULL,
    `Examiner` varchar(255) DEFAULT NULL,
    `Testdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
    `Date_taken` date DEFAULT NULL,
    `Candidate_Age` varchar(255) DEFAULT NULL,
    `Window_Difference` varchar(255) DEFAULT NULL,

    `File_name` varchar(255) DEFAULT NULL,
    `Data_dir` varchar(100) DEFAULT NULL,
    `other_comments` text,

    `SSS_LC_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_LC_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_ERS_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_ERS_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_RC_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_RC_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_MPS_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MPS_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_AWF_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_AWF_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_SC_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_SC_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_WR_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_WR_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_EC_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_EC_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_PD_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_PD_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_OE_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_OE_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_NO_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_NO_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_ORF_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_ORF_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_SP_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_SP_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_MFA_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MFA_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_MFS_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MFS_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSS_MFM_RAW` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_CI` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_NCE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSS_MFM_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSSS_ORA_RAW` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_CI` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_NCE` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORA_GROWTH` VARCHAR(30) DEFAULT NULL,

    `SSSS_ORR_RAW` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_CI` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_NCE` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_STANINE` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_GRADE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_AGE_EQUIV` VARCHAR(30) DEFAULT NULL,
    `SSSS_ORR_GROWTH` VARCHAR(30) DEFAULT NULL,

    `CSS_TR_SUM` VARCHAR(30) DEFAULT NULL,
    `CSS_TR_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `CSS_TR_CI` VARCHAR(30) DEFAULT NULL,
    `CSS_TR_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `CSS_TR_NCE` VARCHAR(30) DEFAULT NULL,
    `CSS_TR_STANINE` VARCHAR(30) DEFAULT NULL,
    `CSS_TR_QUAL` VARCHAR(30) DEFAULT NULL,

    `CSS_BR_SUM` VARCHAR(30) DEFAULT NULL,
    `CSS_BR_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `CSS_BR_CI` VARCHAR(30) DEFAULT NULL,
    `CSS_BR_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `CSS_BR_NCE` VARCHAR(30) DEFAULT NULL,
    `CSS_BR_STANINE` VARCHAR(30) DEFAULT NULL,
    `CSS_BR_QUAL` VARCHAR(30) DEFAULT NULL,

    `CSS_RCF_SUM` VARCHAR(30) DEFAULT NULL,
    `CSS_RCF_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `CSS_RCF_CI` VARCHAR(30) DEFAULT NULL,
    `CSS_RCF_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `CSS_RCF_NCE` VARCHAR(30) DEFAULT NULL,
    `CSS_RCF_STANINE` VARCHAR(30) DEFAULT NULL,
    `CSS_RCF_QUAL` VARCHAR(30) DEFAULT NULL,

    `CSS_MATH_SUM` VARCHAR(30) DEFAULT NULL,
    `CSS_MATH_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `CSS_MATH_CI` VARCHAR(30) DEFAULT NULL,
    `CSS_MATH_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `CSS_MATH_NCE` VARCHAR(30) DEFAULT NULL,
    `CSS_MATH_STANINE` VARCHAR(30) DEFAULT NULL,
    `CSS_MATH_QUAL` VARCHAR(30) DEFAULT NULL,

    `CSS_MATHF_SUM` VARCHAR(30) DEFAULT NULL,
    `CSS_MATHF_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `CSS_MATHF_CI` VARCHAR(30) DEFAULT NULL,
    `CSS_MATHF_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `CSS_MATHF_NCE` VARCHAR(30) DEFAULT NULL,
    `CSS_MATHF_STANINE` VARCHAR(30) DEFAULT NULL,
    `CSS_MATHF_QUAL` VARCHAR(30) DEFAULT NULL,

    `SCSS_LC_RAW` VARCHAR(30) DEFAULT NULL,
    `SCSS_LC_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SCSS_LC_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SCSS_LC_NCE` VARCHAR(30) DEFAULT NULL,
    `SCSS_LC_STANINE` VARCHAR(30) DEFAULT NULL,
    `SCSS_LC_QUAL` VARCHAR(30) DEFAULT NULL,

    `SCSS_RV_RAW` VARCHAR(30) DEFAULT NULL,
    `SCSS_RV_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SCSS_RV_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SCSS_RV_NCE` VARCHAR(30) DEFAULT NULL,
    `SCSS_RV_STANINE` VARCHAR(30) DEFAULT NULL,
    `SCSS_RV_QUAL` VARCHAR(30) DEFAULT NULL,

    `SCSS_ODC_RAW` VARCHAR(30) DEFAULT NULL,
    `SCSS_ODC_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SCSS_ODC_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SCSS_ODC_NCE` VARCHAR(30) DEFAULT NULL,
    `SCSS_ODC_STANINE` VARCHAR(30) DEFAULT NULL,
    `SCSS_ODC_QUAL` VARCHAR(30) DEFAULT NULL,

    `SCSS_ORA_RAW` VARCHAR(30) DEFAULT NULL,
    `SCSS_ORA_STD_SCORE` VARCHAR(30) DEFAULT NULL,
    `SCSS_ORA_PER_RANK` VARCHAR(30) DEFAULT NULL,
    `SCSS_ORA_NCE` VARCHAR(30) DEFAULT NULL,
    `SCSS_ORA_STANINE` VARCHAR(30) DEFAULT NULL,
    `SCSS_ORA_QUAL` VARCHAR(30) DEFAULT NULL,

    PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO WIAT_III_SA (CommentID, UserID, Examiner, Testdate, Data_entry_completion_status, Date_taken, Candidate_Age, Window_Difference, File_name, other_comments, Data_dir)
  SELECT CommentID, UserID, Examiner, Testdate, Data_entry_completion_status, Date_taken, Candidate_Age, Window_Difference, File_name, other_comments, Data_dir
  FROM WIAT_III_SA_backup;

