UPDATE survey_test_battery SET Visit_label = 'V06' WHERE Test_name = 'BSRC_survey' AND Visit_label = 'V6';
ALTER TABLE `BSRC_survey` ADD COLUMN `Candidate_Age` varchar(255) default NULL AFTER `Date_taken`;
ALTER TABLE `BSRC_survey` ADD COLUMN `Window_Difference` varchar(255) default NULL AFTER `Candidate_Age`;
ALTER TABLE `BSRC_survey` MODIFY `average_hours_per_week` varchar(128);
ALTER TABLE `BSRC_survey` MODIFY `total_hours_since_last_visit` varchar(128);
ALTER TABLE `BSRC_survey` CHANGE `occupational_therapy` `occupational_therapy_received` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `date_occupational_therapy` `occupational_therapy_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `still_receiving_intervention_occupational_therapy` `occupational_therapy_intervention` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `stopped_date_occupational_therapy` `occupational_therapy_stopped_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `individual_group_occupational_therapy` `occupational_therapy_individual_group` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `setting_occupational_therapy` `occupational_therapy_setting` enum('office_clinic','home','daycare_preschool','other') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `other_setting_occupational_therapy` `occupational_therapy_other_setting` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `average_hours_occupational_therapy` `occupational_therapy_average_hours` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `physical_therapy` `physical_therapy_received` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `date_physical_therapy` `physical_therapy_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `still_receiving_intervention_physical_therapy` `physical_therapy_intervention` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `stopped_date_physical_therapy` `physical_therapy_stopped_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `individual_group_physical_therapy` `physical_therapy_individual_group` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `setting_physical_therapy` `physical_therapy_setting` enum('office_clinic','home','daycare_preschool','other') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `other_setting_physical_therapy` `physical_therapy_other_setting` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `average_hours_physical_therapy` `physical_therapy_average_hours` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `speech_language_therapy` `speech_language_therapy_received` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `date_speech_language_therapy` `speech_language_therapy_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `still_receiving_intervention_speech_language_therapy` `speech_language_therapy_intervention` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `stopped_date_speech_language_therapy` `speech_language_therapy_stopped_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `individual_group_speech_language_therapy` `speech_language_therapy_individual_group` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `setting_speech_language_therapy` `speech_language_therapy_setting` enum('office_clinic','home','daycare_preschool','other') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `other_setting_speech_language_therapy` `speech_language_therapy_other_setting` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `average_hours_speech_language_therapy` `speech_language_therapy_average_hours` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `comprehensive_behavioral` `comprehensive_behavioral_received` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `date_comprehensive_behavioral` `comprehensive_behavioral_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `still_receiving_intervention_comprehensive_behavioral` `comprehensive_behavioral_intervention` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `stopped_date_comprehensive_behavioral` `comprehensive_behavioral_stopped_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `individual_group_comprehensive_behavioral` `comprehensive_behavioral_individual_group` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `setting_comprehensive_behavioral` `comprehensive_behavioral_setting` enum('office_clinic','home','daycare_preschool','other') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `other_setting_comprehensive_behavioral` `comprehensive_behavioral_other_setting` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `average_hours_comprehensive_behavioral` `comprehensive_behavioral_average_hours` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `other` `other_received` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `date_other` `other_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `still_receiving_intervention_other` `other_intervention` enum('yes','no') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `stopped_date_other` `other_stopped_date` date default NULL;
ALTER TABLE `BSRC_survey` CHANGE `individual_group_other` `other_individual_group` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `setting_other` `other_setting` enum('office_clinic','home','daycare_preschool','other') default NULL;
ALTER TABLE `BSRC_survey` CHANGE `other_setting_other` `other_other_setting` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` CHANGE `average_hours_other` `other_average_hours` varchar(128) default NULL;
ALTER TABLE `BSRC_survey` MODIFY `since_yours_last_visit` varchar(128);
ALTER TABLE `BSRC_survey` MODIFY `in_past_year` varchar(128);
ALTER TABLE `BSRC_survey` MODIFY `q7_specify` varchar(128);
ALTER TABLE `BSRC_survey` MODIFY `q8_specify` varchar(128);
ALTER TABLE `BSRC_survey` MODIFY `if_checked_9_please_check` varchar(128);
