ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_1` `session_date_1_date` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_1_status` `session_date_1_date_status` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_2` `session_date_2_date` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_2_status` `session_date_2_date_status` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_3` `session_date_3_date` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_3_status` `session_date_3_date_status` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_4` `session_date_4_date` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_4_status` `session_date_4_date_status` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_5` `session_date_5_date` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_5_status` `session_date_5_date_status` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_6` `session_date_6_date` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` CHANGE `session_date_6_status` `session_date_6_date_status` date default NULL;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `other_facade_1_status` enum('not_answered') default NULL AFTER `other_facade_1`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `other_facade_2_status` enum('not_answered') default NULL AFTER `other_facade_2`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `other_facade_3_status` enum('not_answered') default NULL AFTER `other_facade_3`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `other_facade_4_status` enum('not_answered') default NULL AFTER `other_facade_4`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `other_facade_5_status` enum('not_answered') default NULL AFTER `other_facade_5`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `other_facade_6_status` enum('not_answered') default NULL AFTER `other_facade_6`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `how_many_breaks_1_status` enum('not_answered') default NULL AFTER `how_many_breaks_1`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `how_many_breaks_2_status` enum('not_answered') default NULL AFTER `how_many_breaks_2`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `how_many_breaks_3_status` enum('not_answered') default NULL AFTER `how_many_breaks_3`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `how_many_breaks_4_status` enum('not_answered') default NULL AFTER `how_many_breaks_4`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `how_many_breaks_5_status` enum('not_answered') default NULL AFTER `how_many_breaks_5`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `how_many_breaks_6_status` enum('not_answered') default NULL AFTER `how_many_breaks_6`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `break_duration_1_status` enum('dnk', 'refusal', 'not_answered') default NULL AFTER `break_duration_1`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `break_duration_2_status` enum('dnk', 'refusal', 'not_answered') default NULL AFTER `break_duration_2`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `break_duration_3_status` enum('dnk', 'refusal', 'not_answered') default NULL AFTER `break_duration_3`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `break_duration_4_status` enum('dnk', 'refusal', 'not_answered') default NULL AFTER `break_duration_4`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `break_duration_5_status` enum('dnk', 'refusal', 'not_answered') default NULL AFTER `break_duration_5`;
ALTER TABLE `Mock_Scanner_Training_Version_2` ADD COLUMN `break_duration_6_status` enum('dnk', 'refusal', 'not_answered') default NULL AFTER `break_duration_6`;
