ALTER TABLE mcdi_words_gestures_sentences_survey ADD `word_endings` int(5) default NULL AFTER `total_gestures_percentile`;
ALTER TABLE mcdi_words_gestures_sentences_survey ADD `word_forms` int(5) default NULL AFTER `word_endings`;
ALTER TABLE mcdi_words_gestures_sentences_survey ADD `word_forms_percentile` varchar(255) default NULL AFTER `word_forms`;
ALTER TABLE mcdi_words_gestures_sentences_survey ADD `word_endings_pt_2` int(5) default NULL AFTER `word_forms_percentile`;
ALTER TABLE mcdi_words_gestures_sentences_survey ADD `grammatical_complexity` int(5) default NULL AFTER `word_endings_pt_2`;
ALTER TABLE mcdi_words_gestures_sentences_survey ADD `grammatical_complexity_percentile` varchar(255) default NULL AFTER `word_forms_percentile`;

ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V1 III_E_1 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V2 III_E_2 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V3 III_E_3 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V4 III_E_4 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V5 III_E_5 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V6 III_E_6 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V7 III_E_7 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V8 III_E_8 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V9 III_E_9 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V10 III_E_10 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V11 III_E_11 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V12 III_E_12 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V13 III_E_13 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V14 III_E_14 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V15 III_E_15 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V16 III_E_16 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V17 III_E_17 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V18 III_E_18 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V19 III_E_19 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V20 III_E_20 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V21 III_E_21 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V22 III_E_22 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V23 III_E_23 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V24 III_E_24 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V25 III_E_25 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V26 III_E_26 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V27 III_E_27 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V28 III_E_28 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V29 III_E_29 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V30 III_E_30 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V31 III_E_31 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V32 III_E_32 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V33 III_E_33 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V34 III_E_34 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V35 III_E_35 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V36 III_E_36 enum('1','2','NK') default NULL;
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE III_C_V37 III_E_37 enum('1','2','NK') default NULL;