ALTER TABLE `ADOS2_Toddler_Module`
    CHANGE COLUMN `a3` `a3`                     ENUM ('0', '1', '2', '3', '8', 'not_answered')      NULL DEFAULT NULL,
    CHANGE COLUMN `a6` `a6`                     ENUM ('0', '1', '2', '3', '8', 'not_answered')      NULL DEFAULT NULL,
    CHANGE COLUMN `a8` `a8`                     ENUM ('0', '1', '2', '3', '8', 'not_answered')      NULL DEFAULT NULL,
    CHANGE COLUMN `a9` `a9`                     ENUM ('0', '1', '2', '3', '8', 'not_answered')      NULL DEFAULT NULL,
    CHANGE COLUMN `b1` `b1`                     ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    CHANGE COLUMN `b2` `b2`                     ENUM ('0', '1', '2', '3', '8', 'not_answered')      NULL DEFAULT NULL,
    CHANGE COLUMN `b3` `b3`                     ENUM ('0', '1', '2', '3', '8', 'not_answered')      NULL DEFAULT NULL,
    CHANGE COLUMN `b8` `b8`                     ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    CHANGE COLUMN `b9` `b9`                     ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    CHANGE COLUMN `b10` `b10`                   ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    CHANGE COLUMN `b13` `b13`                   ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    CHANGE COLUMN `b14` `b14`                   ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    CHANGE COLUMN `b16a` `b16a`                 ENUM ('0', '1', '2', '3', '7', 'not_answered')      NULL DEFAULT NULL,
    CHANGE COLUMN `b16b` `b16b`                 ENUM ('0', '1', '2', '3', '7', '8', 'not_answered') NULL DEFAULT NULL,
    CHANGE COLUMN `d4` `d4`                     ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    ADD COLUMN `d4_specify`                     TEXT AFTER `d4`,
    ADD COLUMN `d4_specify_status`              ENUM ('not_answered')                               NULL DEFAULT NULL AFTER `d4_specify`,
    CHANGE COLUMN `e3` `e3`                     ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    CHANGE COLUMN `e4` `e4`                     ENUM ('0', '1', '2', '3', 'not_answered')           NULL DEFAULT NULL,
    ADD COLUMN `a7_weighted`                    VARCHAR(255) DEFAULT NULL AFTER `a3_weighted`,
    CHANGE COLUMN `b3_weighted` `b6_weighted`   VARCHAR(255) DEFAULT NULL AFTER `b5_weighted`,
    ADD COLUMN `b7_weighted`                    VARCHAR(255) DEFAULT NULL AFTER `b6_weighted`,
    ADD COLUMN `b8_weighted`                    VARCHAR(255) DEFAULT NULL AFTER `b7_weighted`,
    CHANGE COLUMN `b10_weighted` `b13_weighted` VARCHAR(255) DEFAULT NULL AFTER `b12_weighted`,
    CHANGE COLUMN `b11_weighted` `b14_weighted` VARCHAR(255) DEFAULT NULL AFTER `b13_weighted`,
    ADD COLUMN `b15_weighted`                   VARCHAR(255) DEFAULT NULL AFTER `b14_weighted`,
    ADD COLUMN `b16b_weighted`                  VARCHAR(255) DEFAULT NULL AFTER `b15_weighted`,
    ADD COLUMN `b18_weighted`                   VARCHAR(255) DEFAULT NULL AFTER `b16b_weighted`,
    CHANGE COLUMN `d4_weighted` `d5_weighted`   VARCHAR(255) DEFAULT NULL AFTER `d2_weighted`,
    DROP COLUMN `social_affect_gotham_weighted`,
    DROP COLUMN `restricted_repetitive_gotham_weighted`,
    DROP COLUMN `gotham_weighted_score`;