ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE words_produced_percentile words_produced_number_percentile varchar(255);
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE early_gestures_percentile early_gestures_number_percentile varchar(255);
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE later_gestures_percentile later_gestures_number_percentile varchar(255);
ALTER TABLE mcdi_words_gestures_sentences_survey CHANGE total_gestures_percentile total_gestures_number_percentile varchar(255);