INSERT INTO `parameter_type` (`Name`, `Type`, `Description`, `SourceField`, `SourceFrom`) VALUES
    ('rbs_r_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'rbs_r'),
    ('rbs_r_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'rbs_r'),
    ('sibling_socialcontact_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'sibling_socialcontact'),
    ('sibling_socialcontact_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'sibling_socialcontact'),
    ('peer_socialcontact_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'peer_socialcontact'),
    ('peer_socialcontact_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'peer_socialcontact'),
    ('m_chat_rf_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'm_chat_rf'),
    ('m_chat_rf_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'm_chat_rf'),
    ('SEQ3_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SEQ3'),
    ('SEQ3_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SEQ3'),
    ('CCC2_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'CCC2'),
    ('CCC2_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'CCC2'),
    ('conners_parent_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'conners_parent'),
    ('conners_parent_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'conners_parent'),
    ('conners_teacher_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'conners_teacher'),
    ('conners_teacher_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'conners_teacher'),
    ('UCD_Charge_GI_History_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'UCD_Charge_GI_History'),
    ('UCD_Charge_GI_History_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'UCD_Charge_GI_History'),
    ('MASC2_Parent_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'MASC2_Parent'),
    ('MASC2_Parent_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'MASC2_Parent'),
    ('MASC2_Self_Report_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'MASC2_Self_Report'),
    ('MASC2_Self_Report_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'MASC2_Self_Report'),
    ('CSHQ_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'CSHQ'),
    ('CSHQ_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'CSHQ'),
    ('QRS_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'QRS'),
    ('QRS_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'QRS'),
    ('BRIEF2_Parent_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'BRIEF2_Parent'),
    ('BRIEF2_Parent_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'BRIEF2_Parent'),
    ('BRIEF2_Teacher_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'BRIEF2_Teacher'),
    ('BRIEF2_Teacher_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'BRIEF2_Teacher'),
    ('Seizure_Questionnaire_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'Seizure_Questionnaire'),
    ('Seizure_Questionnaire_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'Seizure_Questionnaire'),
    ('ABC2_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'ABC2'),
    ('ABC2_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'ABC2'),
    ('Teachers_Report_Form_6_To_18_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'Teachers_Report_Form_6_To_18'),
    ('Teachers_Report_Form_6_To_18_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'Teachers_Report_Form_6_To_18'),
    ('scq_proband_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'scq_proband_survey'),
    ('scq_proband_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'scq_proband_survey'),
    ('CBCL_6_To_18_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'CBCL_6_To_18'),
    ('CBCL_6_To_18_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'CBCL_6_To_18'),
    ('SRS2_SchoolAge_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SRS2_SchoolAge'),
    ('SRS2_SchoolAge_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SRS2_SchoolAge'),
    ('SSIS_Parent_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SSIS_Parent'),
    ('SSIS_Parent_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SSIS_Parent'),
    ('SSIS_Teacher_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SSIS_Teacher'),
    ('SSIS_Teacher_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SSIS_Teacher'),
    ('ABCL_DAD_ON_MOM_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'ABCL_DAD_ON_MOM'),
    ('ABCL_DAD_ON_MOM_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'ABCL_DAD_ON_MOM'),
    ('ABCL_MOM_ON_DAD_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'ABCL_MOM_ON_DAD'),
    ('ABCL_MOM_ON_DAD_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'ABCL_MOM_ON_DAD'),
    ('ADULT_SELF_REPORT_DAD_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'ADULT_SELF_REPORT_DAD'),
    ('ADULT_SELF_REPORT_DAD_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'ADULT_SELF_REPORT_DAD'),
    ('ADULT_SELF_REPORT_MOM_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'ADULT_SELF_REPORT_MOM'),
    ('ADULT_SELF_REPORT_MOM_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'ADULT_SELF_REPORT_MOM'),
    ('SRS2_InformantReport_Mom_On_Dad_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SRS2_InformantReport_Mom_On_Dad'),
    ('SRS2_InformantReport_Mom_On_Dad_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SRS2_InformantReport_Mom_On_Dad'),
    ('SRS2_InformantReport_Dad_On_Mom_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SRS2_InformantReport_Dad_On_Mom'),
    ('SRS2_InformantReport_Dad_On_Mom_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SRS2_InformantReport_Dad_On_Mom'),
    ('SRS2_SelfReport_Mom_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SRS2_SelfReport_Mom'),
    ('SRS2_SelfReport_Mom_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SRS2_SelfReport_Mom'),
    ('SRS2_SelfReport_Dad_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SRS2_SelfReport_Dad'),
    ('SRS2_SelfReport_Dad_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SRS2_SelfReport_Dad'),
    ('SRS2_SchoolAge_Parent_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SRS2_SchoolAge_Parent'),
    ('SRS2_SchoolAge_Parent_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SRS2_SchoolAge_Parent'),
    ('pspq_SelfReport_dad_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'pspq_SelfReport_dad'),
    ('pspq_SelfReport_dad_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'pspq_SelfReport_dad'),
    ('pspq_SelfReport_mom_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'pspq_SelfReport_mom'),
    ('pspq_SelfReport_mom_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'pspq_SelfReport_mom'),
    ('pspq_InformantReport_dad_on_mom_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'pspq_InformantReport_dad_on_mom'),
    ('pspq_InformantReport_dad_on_mom_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'pspq_InformantReport_dad_on_mom'),
    ('pspq_InformantReport_mom_on_dad_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'pspq_InformantReport_mom_on_dad'),
    ('pspq_InformantReport_mom_on_dad_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'pspq_InformantReport_mom_on_dad'),
    ('rbs_ecs_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'rbs_ecs'),
    ('rbs_ecs_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'rbs_ecs'),
    ('perinatal_data_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'perinatal_data'),
    ('perinatal_data_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'perinatal_data'),
    ('toddler_social_motivation_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'toddler_social_motivation_survey'),
    ('toddler_social_motivation_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'toddler_social_motivation_survey'),
    ('BISQ_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'BISQ_survey'),
    ('BISQ_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'BISQ_survey'),
    ('apsi_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'apsi_survey'),
    ('apsi_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'apsi_survey'),
    ('Infant_social_motivation_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'Infant_social_motivation_survey'),
    ('Infant_social_motivation_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'Infant_social_motivation_survey'),
    ('fyi_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'fyi_survey'),
    ('fyi_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'fyi_survey'),
    ('ibq_r_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'ibq_r_survey'),
    ('ibq_r_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'ibq_r_survey'),
    ('acesubjectmedical_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'acesubjectmedical_survey'),
    ('acesubjectmedical_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'acesubjectmedical_survey'),
    ('macarthur_words_gestures_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'macarthur_words_gestures_survey'),
    ('macarthur_words_gestures_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'macarthur_words_gestures_survey'),
    ('rbs_ec_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'rbs_ec_survey'),
    ('rbs_ec_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'rbs_ec_survey'),
    ('mcdi_words_gestures_sentences_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'mcdi_words_gestures_sentences_survey'),
    ('mcdi_words_gestures_sentences_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'mcdi_words_gestures_sentences_survey'),
    ('ECBQ_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'ECBQ_survey'),
    ('ECBQ_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'ECBQ_survey'),
    ('FES_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'FES'),
    ('FES_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'FES'),
    ('CBCL_1_To_5_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'CBCL_1_To_5_survey'),
    ('CBCL_1_To_5_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'CBCL_1_To_5_survey'),
    ('SRS2_Preschool_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SRS2_Preschool_survey'),
    ('SRS2_Preschool_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SRS2_Preschool_survey'),
    ('RBS_EC_G_V12_V24_Survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'RBS_EC_G_V12_V24_Survey'),
    ('RBS_EC_G_V12_V24_Survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'RBS_EC_G_V12_V24_Survey'),
    ('Med_Psych_History_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'Med_Psych_History_survey'),
    ('Med_Psych_History_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'Med_Psych_History_survey'),
    ('BRQ_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'BRQ_survey'),
    ('BRQ_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'BRQ_survey'),
    ('CCTQ_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'CCTQ_survey'),
    ('CCTQ_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'CCTQ_survey'),
    ('COVID_Child_Self_Report_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'COVID_Child_Self_Report_survey'),
    ('COVID_Child_Self_Report_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'COVID_Child_Self_Report_survey'),
    ('scq_subject_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'scq_subject_survey'),
    ('scq_subject_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'scq_subject_survey'),
    ('COVID_Parent_Report_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'COVID_Parent_Report_survey'),
    ('COVID_Parent_Report_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'COVID_Parent_Report_survey'),
    ('Med_Psych_History_Abbreviated_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'Med_Psych_History_Abbreviated_survey'),
    ('Med_Psych_History_Abbreviated_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'Med_Psych_History_Abbreviated_survey'),
    ('MEQC_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'MEQC_survey'),
    ('MEQC_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'MEQC_survey'),
    ('BSRC_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'BSRC_survey'),
    ('BSRC_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'BSRC_survey'),
    ('vrRSB_survey_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'vrRSB_survey'),
    ('vrRSB_survey_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'vrRSB_survey'),
    ('Saliva_Collection_Tracking_Form_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'Saliva_Collection_Tracking_Form'),
    ('Saliva_Collection_Tracking_Form_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'Saliva_Collection_Tracking_Form'),
    ('SCAARED_Adult_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SCAARED_Adult'),
    ('SCAARED_Adult_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SCAARED_Adult'),
    ('SCARED_Child_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SCARED_Child'),
    ('SCARED_Child_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SCARED_Child'),
    ('SCARED_Parent_Candidate_Age', 'varchar(255)', 'Candidate Age (Months)', 'Candidate_Age', 'SCARED_Parent'),
    ('SCARED_Parent_Window_Difference', 'varchar(255)', 'Window Difference (+/- Days)', 'Window_Difference', 'SCARED_Parent');
