ALTER TABLE `mri_parameter_form_sa`
    ADD COLUMN `t1w_run1_facemask` enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_passfail`,
    ADD COLUMN `t1w_run2_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_passfail`,
    ADD COLUMN `t1w_run3_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_passfail`,
    ADD COLUMN `t1w_run4_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_passfail`,
    ADD COLUMN `t1w_run5_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_passfail`,
    ADD COLUMN `t1w_run6_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_passfail`,
    ADD COLUMN `t2w_run1_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_passfail`,
    ADD COLUMN `t2w_run2_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_passfail`,
    ADD COLUMN `t2w_run3_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_passfail`,
    ADD COLUMN `t2w_run4_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_passfail`,
    ADD COLUMN `t2w_run5_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_passfail`,
    ADD COLUMN `t2w_run6_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_passfail`,

    ADD COLUMN `t1w_run1_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_2_passfail`,
    ADD COLUMN `t1w_run2_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_2_passfail`,
    ADD COLUMN `t1w_run3_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_2_passfail`,
    ADD COLUMN `t1w_run4_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_2_passfail`,
    ADD COLUMN `t1w_run5_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_2_passfail`,
    ADD COLUMN `t1w_run6_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_2_passfail`,
    ADD COLUMN `t2w_run1_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_2_passfail`,
    ADD COLUMN `t2w_run2_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_2_passfail`,
    ADD COLUMN `t2w_run3_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_2_passfail`,
    ADD COLUMN `t2w_run4_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_2_passfail`,
    ADD COLUMN `t2w_run5_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_2_passfail`,
    ADD COLUMN `t2w_run6_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_2_passfail`,

    ADD COLUMN `t1w_run1_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_3_passfail`,
    ADD COLUMN `t1w_run2_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_3_passfail`,
    ADD COLUMN `t1w_run3_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_3_passfail`,
    ADD COLUMN `t1w_run4_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_3_passfail`,
    ADD COLUMN `t1w_run5_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_3_passfail`,
    ADD COLUMN `t1w_run6_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_3_passfail`,
    ADD COLUMN `t2w_run1_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_3_passfail`,
    ADD COLUMN `t2w_run2_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_3_passfail`,
    ADD COLUMN `t2w_run3_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_3_passfail`,
    ADD COLUMN `t2w_run4_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_3_passfail`,
    ADD COLUMN `t2w_run5_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_3_passfail`,
    ADD COLUMN `t2w_run6_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_3_passfail`,

    ADD COLUMN `t1w_run1_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_4_passfail`,
    ADD COLUMN `t1w_run2_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_4_passfail`,
    ADD COLUMN `t1w_run3_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_4_passfail`,
    ADD COLUMN `t1w_run4_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_4_passfail`,
    ADD COLUMN `t1w_run5_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_4_passfail`,
    ADD COLUMN `t1w_run6_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_4_passfail`,
    ADD COLUMN `t2w_run1_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_4_passfail`,
    ADD COLUMN `t2w_run2_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_4_passfail`,
    ADD COLUMN `t2w_run3_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_4_passfail`,
    ADD COLUMN `t2w_run4_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_4_passfail`,
    ADD COLUMN `t2w_run5_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_4_passfail`,
    ADD COLUMN `t2w_run6_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_4_passfail`,

    CHANGE `dti_sequences_acquired` `cmrr1_dti_sequences_acquired`       enum ('complete','partial','none')                  DEFAULT NULL AFTER `auto_align_successful`,
    CHANGE `dti3_shell` `cmrr1_dti3_shell`                               enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr1_dti_sequences_acquired`,
    CHANGE `dti3_shell_attempts` `cmrr1_dti3_shell_attempts`             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr1_dti3_shell`,
    CHANGE `dti3_shell_num_attempts` `cmrr1_dti3_shell_num_attempts`     enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr1_dti3_shell_attempts`,
    ADD COLUMN `cmrr1_dti3_shell_facemask`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr1_dti3_shell_num_attempts`,
    CHANGE `6b0` `cmrr1_6b0`                                             enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr1_dti3_shell_facemask`,
    CHANGE `6b0_attempts` `cmrr1_6b0_attempts`                           enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr1_6b0`,
    CHANGE `6b0_num_attempts` `cmrr1_6b0_num_attempts`                   enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr1_6b0_attempts`,
    ADD COLUMN `cmrr1_6b0_facemask`                                      enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr1_6b0_num_attempts`,
    CHANGE `dti2_shell` `cmrr1_dti2_shell`                               enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr1_6b0_facemask`,
    CHANGE `dti2_shell_attempts` `cmrr1_dti2_shell_attempts`             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr1_dti2_shell`,
    CHANGE `dti2_shell_num_attempts` `cmrr1_dti2_shell_num_attempts`     enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr1_dti2_shell_attempts`,
    ADD COLUMN `cmrr1_dti2_shell_facemask`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr1_dti2_shell_num_attempts`,
    CHANGE `6b0_2` `cmrr1_6b02`                                         enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr1_dti2_shell_facemask`,
    CHANGE `6b0_2_attempts` `cmrr1_6b02_attempts`                       enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr1_6b02`,
    CHANGE `6b0_2_num_attempts` `cmrr1_6b02_num_attempts`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr1_6b02_attempts`,
    ADD COLUMN `cmrr1_6b02_facemask`                                    enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr1_6b02_num_attempts`,
    CHANGE `dti1_shell` `cmrr1_dti1_shell`                               enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr1_6b02_facemask`,
    CHANGE `dti1_shell_attempts` `cmrr1_dti1_shell_attempts`             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr1_dti1_shell`,
    CHANGE `dti1_shell_num_attempts` `cmrr1_dti1_shell_num_attempts`     enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr1_dti1_shell_attempts`,
    ADD COLUMN `cmrr1_dti1_shell_facemask`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr1_dti1_shell_num_attempts`,
    CHANGE `dti_comments` `cmrr1_dti_comments`                           text AFTER `cmrr1_dti1_shell_facemask`,

    ADD COLUMN `bold_run1_facemask`                                      enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run1_firmm`,
    ADD COLUMN `bold_run2_facemask`                                      enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run2_firmm`,
    ADD COLUMN `bold_run3_facemask`                                      enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run3_firmm`,
    ADD COLUMN `bold_run4_facemask`                                      enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run4_firmm`,

    ADD COLUMN `siemens_dti_sequences_acquired`                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable`,
    ADD COLUMN `siemens_dti3_shell`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_dti_sequences_acquired`,
    ADD COLUMN `siemens_dti3_shell_attempts`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_dti3_shell`,
    ADD COLUMN `siemens_dti3_shell_num_attempts`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_dti3_shell_attempts`,
    ADD COLUMN `siemens_dti3_shell_facemask`                             enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens_dti3_shell_num_attempts`,
    ADD COLUMN `siemens_6b0`                                             enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_dti3_shell_facemask`,
    ADD COLUMN `siemens_6b0_attempts`                                    enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_6b0`,
    ADD COLUMN `siemens_6b0_num_attempts`                                enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_6b0_attempts`,
    ADD COLUMN `siemens_6b0_facemask`                                    enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens_6b0_num_attempts`,
    ADD COLUMN `siemens_dti2_shell`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_6b0_facemask`,
    ADD COLUMN `siemens_dti2_shell_attempts`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_dti2_shell`,
    ADD COLUMN `siemens_dti2_shell_num_attempts`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_dti2_shell_attempts`,
    ADD COLUMN `siemens_dti2_shell_facemask`                             enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens_dti2_shell_num_attempts`,
    ADD COLUMN `siemens_6b02`                                           enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_dti2_shell_facemask`,
    ADD COLUMN `siemens_6b02_attempts`                                  enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_6b02`,
    ADD COLUMN `siemens_6b02_num_attempts`                              enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_6b02_attempts`,
    ADD COLUMN `siemens_6b02_facemask`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens_6b02_num_attempts`,
    ADD COLUMN `siemens_dti1_shell`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_6b02_facemask`,
    ADD COLUMN `siemens_dti1_shell_attempts`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_dti1_shell`,
    ADD COLUMN `siemens_dti1_shell_num_attempts`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_dti1_shell_attempts`,
    ADD COLUMN `siemens_dti1_shell_facemask`                             enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens_dti1_shell_num_attempts`,
    ADD COLUMN `siemens_dti_comments`                                    text AFTER `siemens_dti1_shell_facemask`,

    CHANGE `dti_sequences_acquired_2` `cmrr2_dti_sequences_acquired_2`   enum ('complete','partial','none')                  DEFAULT NULL AFTER `auto_align_successful_2`,
    CHANGE `dti_sequences_acquired_3` `cmrr3_dti_sequences_acquired_3`   enum ('complete','partial','none')                  DEFAULT NULL AFTER `auto_align_successful_3`,
    CHANGE `dti_sequences_acquired_4` `cmrr4_dti_sequences_acquired_4`   enum ('complete','partial','none')                  DEFAULT NULL AFTER `auto_align_successful_4`,
    CHANGE `dti3_shell_2` `cmrr2_dti3_shell_2`                           enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr2_dti_sequences_acquired_2`,
    CHANGE `dti3_shell_3` `cmrr3_dti3_shell_3`                           enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr3_dti_sequences_acquired_3`,
    CHANGE `dti3_shell_4` `cmrr4_dti3_shell_4`                           enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr4_dti_sequences_acquired_4`,
    CHANGE `dti3_shell_attempts_2` `cmrr2_dti3_shell_attempts_2`         enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr2_dti3_shell_2`,
    CHANGE `dti3_shell_attempts_3` `cmrr3_dti3_shell_attempts_3`         enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr3_dti3_shell_3`,
    CHANGE `dti3_shell_attempts_4` `cmrr4_dti3_shell_attempts_4`         enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr4_dti3_shell_4`,
    CHANGE `dti3_shell_num_attempts_2` `cmrr2_dti3_shell_num_attempts_2` enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr2_dti3_shell_attempts_2`,
    CHANGE `dti3_shell_num_attempts_3` `cmrr3_dti3_shell_num_attempts_3` enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr3_dti3_shell_attempts_3`,
    CHANGE `dti3_shell_num_attempts_4` `cmrr4_dti3_shell_num_attempts_4` enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr4_dti3_shell_attempts_4`,
    ADD COLUMN `cmrr2_dti3_shell_2_facemask_2`                           enum ('yes','no')                                   DEFAULT NULL AFTER `cmrr2_dti3_shell_num_attempts_2`,
    ADD COLUMN `cmrr3_dti3_shell_3_facemask_3`                           enum ('yes','no')                                   DEFAULT NULL AFTER `cmrr3_dti3_shell_num_attempts_3`,
    ADD COLUMN `cmrr4_dti3_shell_4_facemask_4`                           enum ('yes','no')                                   DEFAULT NULL AFTER `cmrr4_dti3_shell_num_attempts_4`,

    ADD COLUMN `cmrr2_6b0_2`                                             enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr2_dti3_shell_2_facemask_2`,
    ADD COLUMN `cmrr3_6b0_3`                                             enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr3_dti3_shell_3_facemask_3`,
    ADD COLUMN `cmrr4_6b0_4`                                             enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr4_dti3_shell_4_facemask_4`,
    CHANGE `6b0_attempts_2` `cmrr2_6b0_attempts_2`                       enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr2_6b0_2`,
    CHANGE `6b0_attempts_3` `cmrr3_6b0_attempts_3`                       enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr3_6b0_3`,
    CHANGE `6b0_attempts_4` `cmrr4_6b0_attempts_4`                       enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr4_6b0_4`,
    CHANGE `6b0_num_attempts_2` `cmrr2_6b0_num_attempts_2`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr2_6b0_attempts_2`,
    CHANGE `6b0_num_attempts_3` `cmrr3_6b0_num_attempts_3`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr3_6b0_attempts_3`,
    CHANGE `6b0_num_attempts_4` `cmrr4_6b0_num_attempts_4`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr4_6b0_attempts_4`,
    ADD COLUMN `cmrr2_6b0_2_facemask_2`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr2_6b0_num_attempts_2`,
    ADD COLUMN `cmrr3_6b0_3_facemask_3`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr3_6b0_num_attempts_3`,
    ADD COLUMN `cmrr4_6b0_4_facemask_4`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr4_6b0_num_attempts_4`,

    ADD COLUMN `cmrr2_dti2_shell_2`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr2_6b0_2_facemask_2`,
    ADD COLUMN `cmrr3_dti2_shell_3`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr3_6b0_3_facemask_3`,
    ADD COLUMN `cmrr4_dti2_shell_4`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr4_6b0_4_facemask_4`,
    ADD COLUMN `cmrr2_dti2_shell_attempts_2`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr2_dti2_shell_2`,
    ADD COLUMN `cmrr3_dti2_shell_attempts_3`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr3_dti2_shell_3`,
    ADD COLUMN `cmrr4_dti2_shell_attempts_4`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr4_dti2_shell_4`,
    ADD COLUMN `cmrr2_dti2_shell_num_attempts_2`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr2_dti2_shell_attempts_2`,
    ADD COLUMN `cmrr3_dti2_shell_num_attempts_3`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr3_dti2_shell_attempts_3`,
    ADD COLUMN `cmrr4_dti2_shell_num_attempts_4`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr4_dti2_shell_attempts_4`,
    ADD COLUMN `cmrr2_dti2_shell_2_facemask_2`                           enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr2_dti2_shell_num_attempts_2`,
    ADD COLUMN `cmrr3_dti2_shell_3_facemask_3`                           enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr3_dti2_shell_num_attempts_3`,
    ADD COLUMN `cmrr4_dti2_shell_4_facemask_4`                           enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr4_dti2_shell_num_attempts_4`,

    ADD COLUMN `cmrr2_6b02_2`                                         enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr2_dti2_shell_2_facemask_2`,
    ADD COLUMN `cmrr3_6b02_3`                                         enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr3_dti2_shell_3_facemask_3`,
    ADD COLUMN `cmrr4_6b02_4`                                         enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr4_dti2_shell_4_facemask_4`,
    ADD COLUMN `cmrr2_6b02_attempts_2`                       enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr2_6b02_2`,
    ADD COLUMN `cmrr3_6b02_attempts_3`                       enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr3_6b02_3`,
    ADD COLUMN `cmrr4_6b02_attempts_4`                       enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr4_6b02_4`,
    ADD COLUMN `cmrr2_6b02_num_attempts_2`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr2_6b02_attempts_2`,
    ADD COLUMN `cmrr3_6b02_num_attempts_3`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr3_6b02_attempts_3`,
    ADD COLUMN `cmrr4_6b02_num_attempts_4`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr4_6b02_attempts_4`,
    ADD COLUMN `cmrr2_6b02_2_facemask_2`                                    enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr2_6b02_num_attempts_2`,
    ADD COLUMN `cmrr3_6b02_3_facemask_3`                                    enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr3_6b02_num_attempts_3`,
    ADD COLUMN `cmrr4_6b02_4_facemask_4`                                    enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr4_6b02_num_attempts_4`,

    ADD COLUMN `cmrr2_dti1_shell_2`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr2_6b02_2_facemask_2`,
    ADD COLUMN `cmrr3_dti1_shell_3`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr3_6b02_3_facemask_3`,
    ADD COLUMN `cmrr4_dti1_shell_4`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `cmrr4_6b02_4_facemask_4`,
    ADD COLUMN `cmrr2_dti1_shell_attempts_2`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr2_dti1_shell_2`,
    ADD COLUMN `cmrr3_dti1_shell_attempts_3`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr3_dti1_shell_3`,
    ADD COLUMN `cmrr4_dti1_shell_attempts_4`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `cmrr4_dti1_shell_4`,
    ADD COLUMN `cmrr2_dti1_shell_num_attempts_2`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr2_dti1_shell_attempts_2`,
    ADD COLUMN `cmrr3_dti1_shell_num_attempts_3`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr3_dti1_shell_attempts_3`,
    ADD COLUMN `cmrr4_dti1_shell_num_attempts_4`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `cmrr4_dti1_shell_attempts_4`,
    ADD COLUMN `cmrr2_dti1_shell_2_facemask_2`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr2_dti1_shell_num_attempts_2`,
    ADD COLUMN `cmrr3_dti1_shell_3_facemask_3`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr3_dti1_shell_num_attempts_3`,
    ADD COLUMN `cmrr4_dti1_shell_4_facemask_4`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr4_dti1_shell_num_attempts_4`,

    CHANGE `dti_comments_2` `cmrr2_dti_comments_2`                       text AFTER `cmrr2_dti1_shell_2_facemask_2`,
    CHANGE `dti_comments_3` `cmrr3_dti_comments_3`                       text AFTER `cmrr3_dti1_shell_3_facemask_3`,
    CHANGE `dti_comments_4` `cmrr4_dti_comments_4`                       text AFTER `cmrr4_dti1_shell_4_facemask_4`,

    ADD COLUMN `bold_run1_2_facemask_2`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run1_firmm_2`,
    ADD COLUMN `bold_run2_2_facemask_2`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run2_firmm_2`,
    ADD COLUMN `bold_run3_2_facemask_2`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run3_firmm_2`,
    ADD COLUMN `bold_run4_2_facemask_2`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run4_firmm_2`,

    ADD COLUMN `bold_run1_3_facemask_3`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run1_firmm_3`,
    ADD COLUMN `bold_run2_3_facemask_3`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run2_firmm_3`,
    ADD COLUMN `bold_run3_3_facemask_3`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run3_firmm_3`,
    ADD COLUMN `bold_run4_3_facemask_3`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run4_firmm_3`,

    ADD COLUMN `bold_run1_4_facemask_4`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run1_firmm_4`,
    ADD COLUMN `bold_run2_4_facemask_4`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run2_firmm_4`,
    ADD COLUMN `bold_run3_4_facemask_4`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run3_firmm_4`,
    ADD COLUMN `bold_run4_4_facemask_4`                                  enum ('yes', 'no')                                  DEFAULT NULL AFTER `bold_run4_firmm_4`,

    ADD COLUMN `siemens2_dti_sequences_acquired_2`                       enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable_2`,
    ADD COLUMN `siemens2_dti3_shell_2`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens2_dti_sequences_acquired_2`,
    ADD COLUMN `siemens2_dti3_shell_attempts_2`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens2_dti3_shell_2`,
    ADD COLUMN `siemens2_dti3_shell_num_attempts_2`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens2_dti3_shell_attempts_2`,
    ADD COLUMN `siemens2_dti3_shell_2_facemask_2`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens2_dti3_shell_num_attempts_2`,
    ADD COLUMN `siemens2_6b0_2`                                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens2_dti3_shell_2_facemask_2`,
    ADD COLUMN `siemens2_6b0_attempts_2`                                 enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens2_6b0_2`,
    ADD COLUMN `siemens2_6b0_num_attempts_2`                             enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens2_6b0_attempts_2`,
    ADD COLUMN `siemens2_6b0_2_facemask_2`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens2_6b0_num_attempts_2`,
    ADD COLUMN `siemens2_dti2_shell_2`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens2_6b0_2_facemask_2`,
    ADD COLUMN `siemens2_dti2_shell_attempts_2`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens2_dti2_shell_2`,
    ADD COLUMN `siemens2_dti2_shell_num_attempts_2`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens2_dti2_shell_attempts_2`,
    ADD COLUMN `siemens2_dti2_shell_2_facemask_2`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens2_dti2_shell_num_attempts_2`,
    ADD COLUMN `siemens2_6b02_2`                                        enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens2_dti2_shell_2_facemask_2`,
    ADD COLUMN `siemens2_6b02_attempts_2`                               enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens2_6b02_2`,
    ADD COLUMN `siemens2_6b02_num_attempts_2`                           enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens2_6b02_attempts_2`,
    ADD COLUMN `siemens2_6b02_2_facemask_2`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens2_6b02_num_attempts_2`,
    ADD COLUMN `siemens2_dti1_shell_2`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens2_6b02_2_facemask_2`,
    ADD COLUMN `siemens2_dti1_shell_attempts_2`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens2_dti1_shell_2`,
    ADD COLUMN `siemens2_dti1_shell_num_attempts_2`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens2_dti1_shell_attempts_2`,
    ADD COLUMN `siemens2_dti1_shell_2_facemask_2`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens2_dti1_shell_num_attempts_2`,
    ADD COLUMN `siemens2_dti_comments`                                   text AFTER `siemens2_dti1_shell_2_facemask_2`,

    ADD COLUMN `siemens3_dti_sequences_acquired_3`                       enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable_3`,
    ADD COLUMN `siemens3_dti3_shell_3`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens3_dti_sequences_acquired_3`,
    ADD COLUMN `siemens3_dti3_shell_attempts_3`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens3_dti3_shell_3`,
    ADD COLUMN `siemens3_dti3_shell_num_attempts_3`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens3_dti3_shell_attempts_3`,
    ADD COLUMN `siemens3_dti3_shell_3_facemask_3`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens3_dti3_shell_num_attempts_3`,
    ADD COLUMN `siemens3_6b0_3`                                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens3_dti3_shell_3_facemask_3`,
    ADD COLUMN `siemens3_6b0_attempts_3`                                 enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens3_6b0_3`,
    ADD COLUMN `siemens3_6b0_num_attempts_3`                             enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens3_6b0_attempts_3`,
    ADD COLUMN `siemens3_6b0_3_facemask_3`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens3_6b0_num_attempts_3`,
    ADD COLUMN `siemens3_dti2_shell_3`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens3_6b0_3_facemask_3`,
    ADD COLUMN `siemens3_dti2_shell_attempts_3`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens3_dti2_shell_3`,
    ADD COLUMN `siemens3_dti2_shell_num_attempts_3`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens3_dti2_shell_attempts_3`,
    ADD COLUMN `siemens3_dti2_shell_3_facemask_3`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens3_dti2_shell_num_attempts_3`,
    ADD COLUMN `siemens3_6b02_3`                                        enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens3_dti2_shell_3_facemask_3`,
    ADD COLUMN `siemens3_6b02_attempts_3`                               enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens3_6b02_3`,
    ADD COLUMN `siemens3_6b02_num_attempts_3`                           enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens3_6b02_attempts_3`,
    ADD COLUMN `siemens3_6b02_3_facemask_3`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens3_6b02_num_attempts_3`,
    ADD COLUMN `siemens3_dti1_shell_3`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens3_6b02_3_facemask_3`,
    ADD COLUMN `siemens3_dti1_shell_attempts_3`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens3_dti1_shell_3`,
    ADD COLUMN `siemens3_dti1_shell_num_attempts_3`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens3_dti1_shell_attempts_3`,
    ADD COLUMN `siemens3_dti1_shell_3_facemask_3`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens3_dti1_shell_num_attempts_3`,
    ADD COLUMN `siemens3_dti_comments`                                   text AFTER `siemens3_dti1_shell_3_facemask_3`,

    ADD COLUMN `siemens4_dti_sequences_acquired_4`                       enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable_4`,
    ADD COLUMN `siemens4_dti3_shell_4`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens4_dti_sequences_acquired_4`,
    ADD COLUMN `siemens4_dti3_shell_attempts_4`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens4_dti3_shell_4`,
    ADD COLUMN `siemens4_dti3_shell_num_attempts_4`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens4_dti3_shell_attempts_4`,
    ADD COLUMN `siemens4_dti3_shell_4_facemask_4`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens4_dti3_shell_num_attempts_4`,
    ADD COLUMN `siemens4_6b0_4`                                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens4_dti3_shell_4_facemask_4`,
    ADD COLUMN `siemens4_6b0_attempts_4`                                 enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens4_6b0_4`,
    ADD COLUMN `siemens4_6b0_num_attempts_4`                             enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens4_6b0_attempts_4`,
    ADD COLUMN `siemens4_6b0_4_facemask_4`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens4_6b0_num_attempts_4`,
    ADD COLUMN `siemens4_dti2_shell_4`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens4_6b0_4_facemask_4`,
    ADD COLUMN `siemens4_dti2_shell_attempts_4`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens4_dti2_shell_4`,
    ADD COLUMN `siemens4_dti2_shell_num_attempts_4`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens4_dti2_shell_attempts_4`,
    ADD COLUMN `siemens4_dti2_shell_4_facemask_4`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens4_dti2_shell_num_attempts_4`,
    ADD COLUMN `siemens4_6b02_4`                                        enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens4_dti2_shell_4_facemask_4`,
    ADD COLUMN `siemens4_6b02_attempts_4`                               enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens4_6b02_4`,
    ADD COLUMN `siemens4_6b02_num_attempts_4`                           enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens4_6b02_attempts_4`,
    ADD COLUMN `siemens4_6b02_4_facemask_4`                               enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens4_6b02_num_attempts_4`,
    ADD COLUMN `siemens4_dti1_shell_4`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens4_6b02_4_facemask_4`,
    ADD COLUMN `siemens4_dti1_shell_attempts_4`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens4_dti1_shell_4`,
    ADD COLUMN `siemens4_dti1_shell_num_attempts_4`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens4_dti1_shell_attempts_4`,
    ADD COLUMN `siemens4_dti1_shell_4_facemask_4`                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens4_dti1_shell_num_attempts_4`,
    ADD COLUMN `siemens4_dti_comments`                                   text AFTER `siemens4_dti1_shell_4_facemask_4`;