CREATE TABLE `Aberrant_Behavior_Checklist` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`subject_id` varchar(255) default NULL,
`date_today` date default NULL,
`q1_excessively_active` enum('0','1','2','3') default NULL,
`q2_injures_self_on_purpose` enum('0','1','2','3') default NULL,
`q3_listless_sluggish_inactive` enum('0','1','2','3') default NULL,
`q4_aggressive_to_others` enum('0','1','2','3') default NULL,
`q5_seeks_isolation` enum('0','1','2','3') default NULL,
`q6_meaningless_recurring_movements` enum('0','1','2','3') default NULL,
`q7_boisterous_noisy_rough` enum('0','1','2','3') default NULL,
`q8_screams_inappropriately` enum('0','1','2','3') default NULL,
`q9_talks_excessively` enum('0','1','2','3') default NULL,
`q10_temper_tantrums_outbursts` enum('0','1','2','3') default NULL,
`q11_stereotyped_behavior_abnormal_repetitive` enum('0','1','2','3') default NULL,
`q12_preoccupied_stares_into_space` enum('0','1','2','3') default NULL,
`q13_impulsive` enum('0','1','2','3') default NULL,
`q14_irritable_and_whiny` enum('0','1','2','3') default NULL,
`q15_restless` enum('0','1','2','3') default NULL,
`q16_withdrawn` enum('0','1','2','3') default NULL,
`q17_odd_bizarre_behavior` enum('0','1','2','3') default NULL,
`q18_disobedient` enum('0','1','2','3') default NULL,
`q19_yells_at_inappropriate_times` enum('0','1','2','3') default NULL,
`q20_fixed_facial_expression` enum('0','1','2','3') default NULL,
`q21_disturbs_others` enum('0','1','2','3') default NULL,
`q22_repetitive_speech` enum('0','1','2','3') default NULL,
`q23_does_nothing_watch_others` enum('0','1','2','3') default NULL,
`q24_uncooperative` enum('0','1','2','3') default NULL,
`q25_depressed_mood` enum('0','1','2','3') default NULL,
`q26_resists_physical_contact` enum('0','1','2','3') default NULL,
`q27_moves_head_repetitively` enum('0','1','2','3') default NULL,
`q28_does_not_pay_attention_instructions` enum('0','1','2','3') default NULL,
`q29_demands_immediately` enum('0','1','2','3') default NULL,
`q30_isolates_self_from_others` enum('0','1','2','3') default NULL,
`q31_disrupts_group_activities` enum('0','1','2','3') default NULL,
`q32_sits_stands_one_position_long_time` enum('0','1','2','3') default NULL,
`q33_talks_to_self_loudly` enum('0','1','2','3') default NULL,
`q34_cries_over_minor_hurts` enum('0','1','2','3') default NULL,
`q35_repetitive_movements` enum('0','1','2','3') default NULL,
`q36_mood_changes_quickly` enum('0','1','2','3') default NULL,
`q37_unresponsive_to_structured_activities` enum('0','1','2','3') default NULL,
`q38_does_not_stay_in_seat` enum('0','1','2','3') default NULL,
`q39_will_not_sit_still_any_length_of_time` enum('0','1','2','3') default NULL,
`q40_difficult_to_reach_contact` enum('0','1','2','3') default NULL,
`q41_cries_and_screams_inappropriately` enum('0','1','2','3') default NULL,
`q42_prefers_to_be_alone` enum('0','1','2','3') default NULL,
`q43_does_not_try_to_communicate` enum('0','1','2','3') default NULL,
`q44_easily_distractible` enum('0','1','2','3') default NULL,
`q45_waves_shakes_extremities_repeatedly` enum('0','1','2','3') default NULL,
`q46_repeats_word_phrase_over_and_over` enum('0','1','2','3') default NULL,
`q47_stamps_feet_bangs_objects` enum('0','1','2','3') default NULL,
`q48_constantly_runs_or_jumps` enum('0','1','2','3') default NULL,
`q49_rocks_body_repeatedly` enum('0','1','2','3') default NULL,
`q50_deliberately_hurts_self` enum('0','1','2','3') default NULL,
`q51_pays_no_attention` enum('0','1','2','3') default NULL,
`q52_physical_violence_to_self` enum('0','1','2','3') default NULL,
`q53_inactive` enum('0','1','2','3') default NULL,
`q54_excessively_active` enum('0','1','2','3') default NULL,
`q55_responds_negatively_to_affection` enum('0','1','2','3') default NULL,
`q56_deliberately_ignores_directions` enum('0','1','2','3') default NULL,
`q57_temper_outbursts_tantrums` enum('0','1','2','3') default NULL,
`q58_shows_few_social_reactions` enum('0','1','2','3') default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
