ALTER TABLE ados_module1 ADD COLUMN `ADOS_SA_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados_module1 ADD COLUMN `ADOS_RRB_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados_module2 ADD COLUMN `ADOS_SA_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados_module2 ADD COLUMN `ADOS_RRB_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados_module3 ADD COLUMN `ADOS_SA_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados_module3 ADD COLUMN `ADOS_RRB_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados2_module1 ADD COLUMN `ADOS_SA_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados2_module1 ADD COLUMN `ADOS_RRB_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados2_module2 ADD COLUMN `ADOS_SA_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados2_module2 ADD COLUMN `ADOS_RRB_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados2_module3 ADD COLUMN `ADOS_SA_CSS` VARCHAR(10) DEFAULT NULL;
ALTER TABLE ados2_module3 ADD COLUMN `ADOS_RRB_CSS` VARCHAR(10) DEFAULT NULL;

