CREATE TABLE `air_pollution` (
  `CommentID` varchar(255) NOT NULL default '',
  `UserID` varchar(255) default NULL,
  `Examiner` varchar(255) default NULL,
  `Testdate` timestamp NOT NULL,
  `Date_taken` date default NULL,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
  `consent` enum('yes','no','not_answered') DEFAULT NULL,
  `consent_date` date DEFAULT NULL,
  `code` varchar(255) default NULL,
  `proband_name` text default NULL,
  `proband_birthdate` date default NULL,
  `living1yb4m1` varchar(255) default NULL,
  `address_line1m1` text default NULL,
  `address_line2m1` text default NULL,
  `citym1` text default NULL,
  `statem1` text default NULL,
  `zip_codem1` text default NULL,
  `from1b41` date default NULL,
  `to1b41` date default NULL,
  `livinghere3bd1` varchar(255) default NULL,
  `living1yb4m2` varchar(255) default NULL,
  `address_line1m2` text default NULL,
  `address_line2m2` text default NULL,
  `citym2` text default NULL,
  `statem2` text default NULL,
  `zip_codem2` text default NULL,
  `from1b42` date default NULL,
  `to1b42` date default NULL,
  `living1yb4m3` varchar(255) default NULL,
  `address_line1m3` text default NULL,
  `address_line2m3` text default NULL,
  `citym3` text default NULL,
  `statem3` text default NULL,
  `zip_codem3` text default NULL,
  `from1b43` date default NULL,
  `to1b43` date default NULL,
  `living1yb4m4` varchar(255) default NULL,
  `address_line1m4` text default NULL,
  `address_line2m4` text default NULL,
  `citym4` text default NULL,
  `statem4` text default NULL,
  `zip_codem4` text default NULL,
  `from1b44` date default NULL,
  `to1b44` date default NULL,
  `living1yb4m5` varchar(255) default NULL,
  `address_line1m5` text default NULL,
  `address_line2m5` text default NULL,
  `citym5` text default NULL,
  `statem5` text default NULL,
  `zip_codem5` text default NULL,
  `from1b45` date default NULL,
  `to1b45` date default NULL,
  `livingatb1` varchar(255) default NULL,
  `address_line1b1` text default NULL,
  `address_line2b1` text default NULL,
  `cityb1` text default NULL,
  `stateb1` text default NULL,
  `zip_codeb1` text default NULL,
  `fromatb1` date default NULL,
  `toatb1` date default NULL,
  `livingatb2` varchar(255) default NULL,
  `address_line1b2` text default NULL,
  `address_line2b2` text default NULL,
  `cityb2` text default NULL,
  `stateb2` text default NULL,
  `zip_codeb2` text default NULL,
  `fromatb2` date default NULL,
  `toatb2` date default NULL,
  `livingatb3` varchar(255) default NULL,
  `address_line1b3` text default NULL,
  `address_line2b3` text default NULL,
  `cityb3` text default NULL,
  `stateb3` text default NULL,
  `zip_codeb3` text default NULL,
  `fromatb3` date default NULL,
  `toatb3` date default NULL,
  `livingatb4` varchar(255) default NULL,
  `address_line1b4` text default NULL,
  `address_line2b4` text default NULL,
  `cityb4` text default NULL,
  `stateb4` text default NULL,
  `zip_codeb4` text default NULL,
  `fromatb4` date default NULL,
  `toatb4` date default NULL,
  `livingatb5` varchar(255) default NULL,
  `address_line1b5` text default NULL,
  `address_line2b5` text default NULL,
  `cityb5` text default NULL,
  `stateb5` text default NULL,
  `zip_codeb5` text default NULL,
  `fromatb5` date default NULL,
  `toatb5` date default NULL,
  `livingatb6` varchar(255) default NULL,
  `address_line1b6` text default NULL,
  `address_line2b6` text default NULL,
  `cityb6` text default NULL,
  `stateb6` text default NULL,
  `zip_codeb6` text default NULL,
  `fromatb6` date default NULL,
  `toatb6` date default NULL,
  `additional_comments` text default NULL,
  `additional_comments_status` enum('not_answered') default NULL,
  PRIMARY KEY  (`CommentID`)
);
INSERT INTO `test_names` (Test_name, Full_name, Sub_group, isDirectEntry) VALUES ('air_pollution', 'Air Pollution', 6, true);
INSERT INTO `instrument_subtests` (`Test_name`, `Subtest_name`, `Description`, `Order_number`) VALUES ('air_pollution', 'air_pollution_page2', 'Page2', '1');
ALTER TABLE `participant_status` ADD COLUMN `air_consent` enum('yes','no','not_answered') DEFAULT NULL;
ALTER TABLE `participant_status` ADD COLUMN `air_consent_date` date DEFAULT NULL;
ALTER TABLE `participant_status` ADD COLUMN `air_consent_withdrawal` date DEFAULT NULL;
ALTER TABLE `consent_info_history` ADD COLUMN `air_consent` enum('yes','no','not_answered') DEFAULT NULL;
ALTER TABLE `consent_info_history` ADD COLUMN `air_consent_date` date DEFAULT NULL;
ALTER TABLE `consent_info_history` ADD COLUMN `air_consent_withdrawal` date DEFAULT NULL;
