CREATE TABLE `APSI` (
`CommentID` varchar(200) NOT NULL default '',

                            `UserID` varchar(100) default NULL,

                            `Examiner` varchar(100) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(100) default NULL,
`Window_Difference` varchar(100) default NULL,
`filling_out_form` enum('mother','father','step_mother','step_father','other') default NULL,
`other_filling_out_form` varchar(100) default NULL,
`q1` enum('no','possibly','definitely','NA') default NULL,
`q2` enum('no','possibly','definitely','NA') default NULL,
`q3` enum('no','possibly','definitely','NA') default NULL,
`q4` enum('no','possibly','definitely','NA') default NULL,
`q5` enum('no','possibly','definitely','NA') default NULL,
`q6` enum('no','possibly','definitely','NA') default NULL,
`q7` enum('no','possibly','definitely','NA') default NULL,
`q8` enum('no','possibly','definitely','NA') default NULL,
`q9` enum('no','possibly','definitely','NA') default NULL,
`q10` enum('no','possibly','definitely','NA') default NULL,
`q11` enum('no','possibly','definitely','NA') default NULL,
`q12` enum('no','possibly','definitely','NA') default NULL,
`q13` enum('no','possibly','definitely','NA') default NULL,
`q14` enum('no','possibly','definitely','NA') default NULL,
`q15` enum('no','possibly','definitely','NA') default NULL,
`q16` enum('no','possibly','definitely','NA') default NULL,
`q17` enum('no','possibly','definitely','NA') default NULL,
`q18` enum('no','possibly','definitely','NA') default NULL,
`q19` enum('no','possibly','definitely','NA') default NULL,
`q20` enum('no','possibly','definitely','NA') default NULL,
`q21` enum('no','possibly','definitely','NA') default NULL,
`q22` enum('no','possibly','definitely','NA') default NULL,
`q23` enum('no','possibly','definitely','NA') default NULL,
`q24` enum('no','possibly','definitely','NA') default NULL,
`q25` enum('no','possibly','definitely','NA') default NULL,
`q26` enum('no','possibly','definitely','NA') default NULL,
`speech_loss` varchar(100) default NULL,
`eye_contact_social_emot_loss` varchar(100) default NULL,
`other_skills_lost` text default NULL,
`speech_loss_happened_when` TEXT default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
