CREATE TABLE `apsi_survey` (
`CommentID` varchar(200) NOT NULL default '',
`Date_taken` date,
`filling_out_form` enum('m','f','s_m','s_f','oth'),
`other_filling_out_form` varchar(255),
`q1` enum('n','p','d','NA'),
`q2` enum('n','p','d','NA'),
`q3` enum('n','p','d','NA'),
`q4` enum('n','p','d','NA'),
`q5` enum('n','p','d','NA'),
`q6` enum('n','p','d','NA'),
`q7` enum('n','p','d','NA'),
`q8` enum('n','p','d','NA'),
`q9` enum('n','p','d','NA'),
`q10` enum('n','p','d','NA'),
`q11` enum('n','p','d','NA'),
`q12` enum('n','p','d','NA'),
`q13` enum('n','p','d','NA'),
`q14` enum('n','p','d','NA'),
`q15` enum('n','p','d','NA'),
`q16` enum('n','p','d','NA'),
`q17` enum('n','p','d','NA'),
`q18` enum('n','p','d','NA'),
`q19` enum('n','p','d','NA'),
`q20` enum('n','p','d','NA'),
`q21` enum('n','p','d','NA'),
`q22` enum('n','p','d','NA'),
`q23` enum('n','p','d','NA'),
`q24` enum('n','p','d','NA'),
`q25` enum('n','p','d','NA'),
`q26` enum('n','p','d','NA'),
`speech_loss` enum('n','y'),
`eye_contact_social_emot_loss` enum('n','y'),
`other_skills_lost` text,
`speech_loss_occurred_before_eye_loss` enum('n','y'),
`speech_loss_occurred_after_eye_loss` enum('n','y'),
`speech_loss_occurred_close_to_eye_loss` enum('n','y'),
`words_used_before_speech_loss` text,
PRIMARY KEY  (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
