CREATE TABLE `asd_peds` (
    `CommentID` varchar(255) NOT NULL default '',
    `UserID` varchar(255) default NULL,
    `Examiner` varchar(255) default NULL,
    `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
    `Date_taken` date default NULL,
    `Candidate_Age` varchar(255) default NULL,
    `Window_Difference` varchar(255) default NULL,
    `dichotomous_total_score` varchar(255) default NULL,
    `likert_total_score` varchar(255) default NULL,
    `child_age` varchar(255) default NULL,
    `child_gender` enum('male','female') default NULL,
    `q1_speech_likert` enum('1','2','3') default NULL,
    `q1_speech_dichotomous` enum('1','3') default NULL,
    `q2_eye_contact_likert` enum('1','2','3') default NULL,
    `q2_eye_contact_dichotomous` enum('1','3') default NULL,
    `q3_vocalizations_likert` enum('1','2','3') default NULL,
    `q3_vocalizations_dichotomous` enum('1','3') default NULL,
    `q4_play_likert` enum('1','2','3') default NULL,
    `q4_play_dichotomous` enum('1','3') default NULL,
    `q5_body_movements_likert` enum('1','2','3') default NULL,
    `q5_body_movements_dichotomous` enum('1','3') default NULL,
    `q6_gestures_likert` enum('1','2','3') default NULL,
    `q6_gestures_dichotomous` enum('1','3') default NULL,
    `q7_sensory_likert` enum('1','2','3') default NULL,
    `q7_sensory_dichotomous` enum('1','3') default NULL,
    `asd_if_forced_to_choose` enum('1_absent','2_unsure','3_present') default NULL,
    `recommend_in_person_evaluation` enum('yes','no') default NULL,
    `diagnosis_issued` varchar(255) default NULL,
    `how_certain_diagnostic_impression` enum('1_completely_uncertain','2_somewhat_uncertain','3_somewhat_certain','4_completely_certain') default NULL,
    PRIMARY KEY  (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;