CREATE TABLE `BOT2_Short` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`preferred_drawing_hand` enum('right','left') default NULL,
`preferred_throwing_hand_arm` enum('right','left') default NULL,
`preferred_foot_leg` enum('right','left') default NULL,
`examinee_school` varchar(255) default NULL,
`subtest_1_3_raw_score` varchar(255) default NULL,
`subtest_1_3_point_score` enum('0','1','2','3','4','5','6','7') default NULL,
`subtest_1_6_raw_score` varchar(255) default NULL,
`subtest_1_6_point_score` enum('0','1','2','3','4','5','6','7') default NULL,
`subtest_2_2_basic_shape` enum('0','1') default NULL,
`subtest_2_2_closure` enum('0','1') default NULL,
`subtest_2_2_edges` enum('0','1') default NULL,
`subtest_2_2_orientation` enum('0','1') default NULL,
`subtest_2_2_overall_size` enum('0','1') default NULL,
`subtest_2_2_raw_score` varchar(255) default NULL,
`subtest_2_2_point_score` varchar(255) default NULL,
`subtest_2_7_basic_shape` enum('0','1') default NULL,
`subtest_2_7_closure` enum('0','1') default NULL,
`subtest_2_7_edges` enum('0','1') default NULL,
`subtest_2_7_orientation` enum('0','1') default NULL,
`subtest_2_7_overall_size` enum('0','1') default NULL,
`subtest_2_7_raw_score` varchar(255) default NULL,
`subtest_2_7_point_score` varchar(255) default NULL,
`subtest_3_2_trial1` varchar(255) default NULL,
`subtest_3_2_trial2` varchar(255) default NULL,
`subtest_3_2_point_score` enum('0','1','2','3','4','5','6','7','8','9') default NULL,
`subtest_4_3_trial1` varchar(255) default NULL,
`subtest_4_3_trial2` varchar(255) default NULL,
`subtest_4_3_point_score` enum('0','1','2','3') default NULL,
`subtest_4_6_trial1` varchar(255) default NULL,
`subtest_4_6_trial2` varchar(255) default NULL,
`subtest_4_6_point_score` enum('0','1','2','3','4') default NULL,
`subtest_5_2_trial1` varchar(255) default NULL,
`subtest_5_2_trial2` varchar(255) default NULL,
`subtest_5_2_point_score` enum('0','1','2','3','4') default NULL,
`subtest_5_7_trial1` varchar(255) default NULL,
`subtest_5_7_trial2` varchar(255) default NULL,
`subtest_5_7_point_score` enum('0','1','2','3','4') default NULL,
`subtest_6_3_trial1` varchar(255) default NULL,
`subtest_6_3_trial2` varchar(255) default NULL,
`subtest_6_3_point_score` enum('0','1','2','3','4','5','6','7','8','9','10') default NULL,
`subtest_7_1_trial1` varchar(255) default NULL,
`subtest_7_1_point_score` enum('0','1','2','3','4','5') default NULL,
`subtest_7_6_trial1` varchar(255) default NULL,
`subtest_7_6_trial2` varchar(255) default NULL,
`subtest_7_6_point_score` enum('0','1','2','3','4','5','6','7') default NULL,
`subtest_8_2_type` enum('knee','full') default NULL,
`subtest_8_2_trial1` varchar(255) default NULL,
`subtest_8_2_point_score` enum('0','1','2','3','4','5','6','7','8','9') default NULL,
`subtest_8_3_trial1` varchar(255) default NULL,
`subtest_8_3_point_score` enum('0','1','2','3','4','5','6','7','8','9') default NULL,
`notes_observations` varchar(255) default NULL,
`total_point_score` varchar(255) default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
