CREATE TABLE `BRIEF2_Parent` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`childs_name` varchar(255) default NULL,
`birth_date` date default NULL,
`childs_gender` enum('male','female') default NULL,
`childs_age` varchar(255) default NULL,
`childs_age_status` enum('not_answered') default NULL,
`childs_grade` varchar(255) default NULL,
`childs_grade_status` enum('not_answered') default NULL,
`rater_name` varchar(255) default NULL,
`relationship_to_child` varchar(255) default NULL,
`date_today` date default NULL,
`q1_is_fidgety` enum('N','S','O') default NULL,
`q2_resists_accepting_different_way_to_solve_problem` enum('N','S','O') default NULL,
`q3_given_three_things_remembers_only_first_or_last` enum('N','S','O') default NULL,
`q4_unaware_of_how_behavior_affects_bothers_others` enum('N','S','O') default NULL,
`q5_work_is_sloppy` enum('N','S','O') default NULL,
`q6_has_explosive_angry_outbursts` enum('N','S','O') default NULL,
`q7_does_not_plan_ahead_school_assignments` enum('N','S','O') default NULL,
`q8_cannot_find_things_in_room_or_school_desk` enum('N','S','O') default NULL,
`q9_is_not_a_self_starter` enum('N','S','O') default NULL,
`q10_does_not_think_before_doing_impulsive` enum('N','S','O') default NULL,
`q11_has_trouble_getting_used_to_new_situations` enum('N','S','O') default NULL,
`q12_has_a_short_attention_span` enum('N','S','O') default NULL,
`q13_has_poor_understanding_of_own_strengths_weaknesses` enum('N','S','O') default NULL,
`q14_has_outbursts_for_little_reason` enum('N','S','O') default NULL,
`q15_gets_caught_up_in_details_misses_big_picture` enum('N','S','O') default NULL,
`q16_gets_out_of_control_more_than_friends` enum('N','S','O') default NULL,
`q17_gets_stuck_on_one_topic_activity` enum('N','S','O') default NULL,
`q18_forgets_his_her_name` enum('N','S','O') default NULL,
`q19_has_trouble_with_chores_tasks_more_than_one_step` enum('N','S','O') default NULL,
`q20_does_not_realize_certain_actions_bother_others` enum('N','S','O') default NULL,
`q21_written_work_is_poorly_organized` enum('N','S','O') default NULL,
`q22_small_events_trigger_big_reactions` enum('N','S','O') default NULL,
`q23_has_good_ideas_lacks_follow_through` enum('N','S','O') default NULL,
`q24_talks_at_wrong_time` enum('N','S','O') default NULL,
`q25_has_trouble_finishing_tasks` enum('N','S','O') default NULL,
`q26_does_not_notice_when_behavior_causes_negative_reactions` enum('N','S','O') default NULL,
`q27_reacts_more_strongly_than_other_children` enum('N','S','O') default NULL,
`q28_has_trouble_remembering_things_even_for_minutes` enum('N','S','O') default NULL,
`q29_makes_careless_errors` enum('N','S','O') default NULL,
`q30_gets_out_of_seat_at_wrong_times` enum('N','S','O') default NULL,
`q31_becomes_upset_with_new_situations` enum('N','S','O') default NULL,
`q32_has_trouble_concentrating_tasks_schoolwork` enum('N','S','O') default NULL,
`q33_has_poor_handwriting` enum('N','S','O') default NULL,
`q34_mood_changes_frequently` enum('N','S','O') default NULL,
`q35_has_good_ideas_cannot_get_on_paper` enum('N','S','O') default NULL,
`q36_has_trouble_counting_to_three` enum('N','S','O') default NULL,
`q37_leaves_messes_others_clean_up` enum('N','S','O') default NULL,
`q38_needs_to_be_told_to_begin_task` enum('N','S','O') default NULL,
`q39_acts_too_wild_or_out_of_control` enum('N','S','O') default NULL,
`q40_thinks_too_much_about_same_topic` enum('N','S','O') default NULL,
`q41_forgets_what_he_she_was_doing` enum('N','S','O') default NULL,
`q42_does_not_check_work_for_mistakes` enum('N','S','O') default NULL,
`q43_angry_or_tearful_outbursts_intense_end_suddenly` enum('N','S','O') default NULL,
`q44_becomes_overwhelmed_by_large_assignments` enum('N','S','O') default NULL,
`q45_loses_lunch_box_money_permission_slips_homework` enum('N','S','O') default NULL,
`q46_needs_help_from_adult_to_stay_on_task` enum('N','S','O') default NULL,
`q47_forgets_to_hand_in_homework_even_when_completed` enum('N','S','O') default NULL,
`q48_has_trouble_putting_brakes_on_actions` enum('N','S','O') default NULL,
`q49_resists_change_of_routine_foods_places` enum('N','S','O') default NULL,
`q50_has_trouble_getting_started_on_homework_tasks` enum('N','S','O') default NULL,
`q51_mood_easily_influenced_by_situation` enum('N','S','O') default NULL,
`q52_underestimates_time_needed_to_finish_tasks` enum('N','S','O') default NULL,
`q53_does_not_bring_home_homework_sheets_materials` enum('N','S','O') default NULL,
`q54_cannot_find_front_door_of_home` enum('N','S','O') default NULL,
`q55_does_not_take_initiative` enum('N','S','O') default NULL,
`q56_becomes_upset_too_easily` enum('N','S','O') default NULL,
`q57_starts_assignments_tasks_last_minute` enum('N','S','O') default NULL,
`q58_has_trouble_moving_from_one_activity_to_another` enum('N','S','O') default NULL,
`q59_has_trouble_carrying_out_actions_to_reach_goals` enum('N','S','O') default NULL,
`q60_is_disturbed_by_change_of_teacher_or_class` enum('N','S','O') default NULL,
`q61_has_trouble_organizing_activities_with_friends` enum('N','S','O') default NULL,
`q62_becomes_too_silly` enum('N','S','O') default NULL,
`q63_leaves_trail_of_belongings` enum('N','S','O') default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
