CREATE TABLE `BSRC_survey` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`child_birth_date` date default NULL,
`today_date` date default NULL,
`date_last_visit` date default NULL,
`did_professional_refer_early_intervention` enum('yes','no') default NULL,
`did_child_receive_early_intervention` enum('yes','no') default NULL,
`average_hours_per_week` varchar(255) default NULL,
`total_hours_since_last_visit` varchar(255) default NULL,
`did_professional_recommend_child_socialization` enum('yes','no') default NULL,
`did_child_participate_socialization` enum('yes','no') default NULL,
`did_child_receive_developmental_delays` enum('yes','no') default NULL,
`occupational_therapy` enum('yes','no') default NULL,
`date_occupational_therapy` date default NULL,
`still_receiving_intervention_occupational_therapy` enum('yes','no') default NULL,
`stopped_date_occupational_therapy` date default NULL,
`individual_group_occupational_therapy` enum('individual','group') default NULL,
`setting_occupational_therapy` enum('office_clinic','home','daycare_preschool','other') default NULL,
`other_setting_occupational_therapy` varchar(255) default NULL,
`average_hours_occupational_therapy` varchar(255) default NULL,
`physical_therapy` enum('yes','no') default NULL,
`date_physical_therapy` date default NULL,
`still_receiving_intervention_physical_therapy` enum('yes','no') default NULL,
`stopped_date_physical_therapy` date default NULL,
`individual_group_physical_therapy` enum('individual','group') default NULL,
`setting_physical_therapy` enum('office_clinic','home','daycare_preschool','other') default NULL,
`other_setting_physical_therapy` varchar(255) default NULL,
`average_hours_physical_therapy` varchar(255) default NULL,
`speech_language_therapy` enum('yes','no') default NULL,
`date_speech_language_therapy` date default NULL,
`still_receiving_intervention_speech_language_therapy` enum('yes','no') default NULL,
`stopped_date_speech_language_therapy` date default NULL,
`individual_group_speech_language_therapy` enum('individual','group') default NULL,
`setting_speech_language_therapy` enum('office_clinic','home','daycare_preschool','other') default NULL,
`other_setting_speech_language_therapy` varchar(255) default NULL,
`average_hours_speech_language_therapy` varchar(255) default NULL,
`comprehensive_behavioral` enum('yes','no') default NULL,
`date_comprehensive_behavioral` date default NULL,
`still_receiving_intervention_comprehensive_behavioral` enum('yes','no') default NULL,
`stopped_date_comprehensive_behavioral` date default NULL,
`individual_group_comprehensive_behavioral` enum('individual','group') default NULL,
`setting_comprehensive_behavioral` enum('office_clinic','home','daycare_preschool','other') default NULL,
`other_setting_comprehensive_behavioral` varchar(255) default NULL,
`average_hours_comprehensive_behavioral` varchar(255) default NULL,
`other` enum('yes','no') default NULL,
`date_other` date default NULL,
`still_receiving_intervention_other` enum('yes','no') default NULL,
`stopped_date_other` date default NULL,
`individual_group_other` enum('individual','group') default NULL,
`setting_other` enum('office_clinic','home','daycare_preschool','other') default NULL,
`other_setting_other` varchar(255) default NULL,
`average_hours_other` varchar(255) default NULL,
`since_yours_last_visit` varchar(255) default NULL,
`in_past_year` varchar(255) default NULL,
`did_child_receive_complementary_therapies_autism` enum('yes','no') default NULL,
`q7_specify` varchar(255) default NULL,
`did_child_receive_medical_therapies_autism` enum('yes','no') default NULL,
`q8_specify` varchar(255) default NULL,
`do_you_continue_enrollment_intervention` enum('yes','no') default NULL,
`if_checked_9_please_check` varchar(255) default NULL,
`additional_info_about_services` text default NULL,
`additional_info_about_services_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
