CREATE TABLE `CCC2` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`child_name` varchar(255) default NULL,
`child_name_status` enum('not_answered') default NULL,
`child_gender` enum('male','female') default NULL,
`user_birthdate_date` date default NULL,
`user_birthdate_date_status` enum('not_answered') default NULL,
`hear_loss` enum('yes','no') default NULL,
`hear_loss_yes` text default NULL,
`hear_loss_yes_status` enum('not_answered') default NULL,
`lang_eng` enum('yes','no') default NULL,
`lang_eng_no` text default NULL,
`lang_eng_no_status` enum('not_answered') default NULL,
`word_to_sent` enum('yes','no') default NULL,
`word_to_sent_no` text default NULL,
`word_to_sent_no_status` enum('not_answered') default NULL,
`responder_name` varchar(255) default NULL,
`responder_name_status` enum('not_answered') default NULL,
`responder_address` text default NULL,
`responder_address_status` enum('not_answered') default NULL,
`responder_realtionship` enum('parent','caregiver','teacher','other') default NULL,
`responder_relationship_other` varchar(255) default NULL,
`responder_relationship_other_status` enum('not_answered') default NULL,
`responder_know_period` varchar(255) default NULL,
`responder_know_period_status` enum('not_answered') default NULL,
`comments` text default NULL,
`comments_status` enum('not_answered') default NULL,
`CCC2_response_1` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_2` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_3` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_4` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_5` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_6` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_7` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_8` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_9` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_10` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_11` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_12` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_13` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_14` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_15` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_16` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_17` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_18` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_19` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_20` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_21` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_22` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_23` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_24` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_25` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_26` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_27` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_28` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_29` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_30` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_31` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_32` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_33` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_34` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_35` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_36` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_37` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_38` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_39` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_40` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_41` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_42` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_43` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_44` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_45` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_46` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_47` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_48` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_49` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_50` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_51` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_52` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_53` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_54` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_55` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_56` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_57` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_58` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_59` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_60` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_61` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_62` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_63` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_64` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_65` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_66` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_67` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_68` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_69` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
`CCC2_response_70` enum('','0.less than once a week (or never)','1.at least once a week, but not everyday (or occasionally)','2.once or twice a day (or frequently)','3.several times (more than twice) a day (or always)') default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
