-- -------------------------------------------------------------------
--                                                                  --
-- 1. Adds column CCHMCID to table candidate.                       --
-- 2. Assigns a random CCHMCID to the candidates that are part of   --
--    the collaborative data set.                                   --
--                                                                  --
-- -------------------------------------------------------------------

ALTER TABLE candidate ADD COLUMN CCHMCID varchar(10) DEFAULT NULL;

UPDATE candidate SET CCHMCID='CCHMC2109' WHERE PSCID='PHI4000';
UPDATE candidate SET CCHMCID='CCHMC9999' WHERE PSCID='PHI4002';
UPDATE candidate SET CCHMCID='CCHMC0023' WHERE PSCID='PHI4005';
UPDATE candidate SET CCHMCID='CCHMC1223' WHERE PSCID='PHI4006';
UPDATE candidate SET CCHMCID='CCHMC5231' WHERE PSCID='PHI4007';
UPDATE candidate SET CCHMCID='CCHMC6554' WHERE PSCID='PHI4009';
UPDATE candidate SET CCHMCID='CCHMC1218' WHERE PSCID='PHI4010';
UPDATE candidate SET CCHMCID='CCHMC2765' WHERE PSCID='PHI4012';
UPDATE candidate SET CCHMCID='CCHMC4770' WHERE PSCID='PHI4013';
UPDATE candidate SET CCHMCID='CCHMC0333' WHERE PSCID='PHI4014';
UPDATE candidate SET CCHMCID='CCHMC2288' WHERE PSCID='PHI4016';
UPDATE candidate SET CCHMCID='CCHMC7766' WHERE PSCID='SEA4000';
UPDATE candidate SET CCHMCID='CCHMC1234' WHERE PSCID='SEA4002';
UPDATE candidate SET CCHMCID='CCHMC9012' WHERE PSCID='STL4000';
UPDATE candidate SET CCHMCID='CCHMC0001' WHERE PSCID='STL4001';
UPDATE candidate SET CCHMCID='CCHMC3490' WHERE PSCID='STL4002';
UPDATE candidate SET CCHMCID='CCHMC7651' WHERE PSCID='STL4003';
UPDATE candidate SET CCHMCID='CCHMC8810' WHERE PSCID='STL4005';
UPDATE candidate SET CCHMCID='CCHMC0099' WHERE PSCID='STL4009';
UPDATE candidate SET CCHMCID='CCHMC3211' WHERE PSCID='STL4010';
UPDATE candidate SET CCHMCID='CCHMC7771' WHERE PSCID='STL4023';
UPDATE candidate SET CCHMCID='CCHMC7867' WHERE PSCID='STL4027';
UPDATE candidate SET CCHMCID='CCHMC1119' WHERE PSCID='STL4029';
UPDATE candidate SET CCHMCID='CCHMC4543' WHERE PSCID='STL4030';
UPDATE candidate SET CCHMCID='CCHMC6577' WHERE PSCID='UNC4003';
UPDATE candidate SET CCHMCID='CCHMC3222' WHERE PSCID='UNC4009';

