CREATE TABLE `Conners_Parent_FOH_Sibling` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`Date_taken` date default NULL,
`sibling_dob` date default NULL,
`relationship_to_child` enum('mother','father','step_mother','step_father','other') default NULL,
`other_relationship_to_child` varchar(255) default NULL,
`grade` varchar(255) default NULL,
`IN_raw_score` varchar(255) default NULL,
`IN_T_score` varchar(255) default NULL,
`IN_response_style` varchar(255) default NULL,
`HY_raw_score` varchar(255) default NULL,
`HY_T_score` varchar(255) default NULL,
`HY_response_style` varchar(255) default NULL,
`LP_raw_score` varchar(255) default NULL,
`LP_T_score` varchar(255) default NULL,
`LP_response_style` varchar(255) default NULL,
`EF_raw_score` varchar(255) default NULL,
`EF_T_score` varchar(255) default NULL,
`EF_response_style` varchar(255) default NULL,
`AG_raw_score` varchar(255) default NULL,
`AG_T_score` varchar(255) default NULL,
`AG_response_style` varchar(255) default NULL,
`PR_raw_score` varchar(255) default NULL,
`PR_T_score` varchar(255) default NULL,
`PR_response_style` varchar(255) default NULL,
`PI_raw_score` varchar(255) default NULL,
`PI_T_score` varchar(255) default NULL,
`PI_response_style` varchar(255) default NULL,
`NI_raw_score` varchar(255) default NULL,
`NI_T_score` varchar(255) default NULL,
`NI_response_style` varchar(255) default NULL,
`q1` enum('0','1','2','3') default NULL,
`q2` enum('0','1','2','3') default NULL,
`q3` enum('0','1','2','3') default NULL,
`q4` enum('0','1','2','3') default NULL,
`q5` enum('0','1','2','3') default NULL,
`q6` enum('0','1','2','3') default NULL,
`q7` enum('0','1','2','3') default NULL,
`q8` enum('0','1','2','3') default NULL,
`q9` enum('0','1','2','3') default NULL,
`q10` enum('0','1','2','3') default NULL,
`q11` enum('0','1','2','3','not_applicable') default NULL,
`q12` enum('0','1','2','3') default NULL,
`q13` enum('0','1','2','3') default NULL,
`q14` enum('0','1','2','3') default NULL,
`q15` enum('0','1','2','3') default NULL,
`q16` enum('0','1','2','3') default NULL,
`q17` enum('0','1','2','3') default NULL,
`q18` enum('0','1','2','3') default NULL,
`q19` enum('0','1','2','3') default NULL,
`q20` enum('0','1','2','3') default NULL,
`q21` enum('0','1','2','3') default NULL,
`q22` enum('0','1','2','3') default NULL,
`q23` enum('0','1','2','3') default NULL,
`q24` enum('0','1','2','3') default NULL,
`q25` enum('0','1','2','3') default NULL,
`q26` enum('0','1','2','3') default NULL,
`q27` enum('0','1','2','3') default NULL,
`q28` enum('0','1','2','3') default NULL,
`q29` enum('0','1','2','3') default NULL,
`q30` enum('0','1','2','3') default NULL,
`q31` enum('0','1','2','3') default NULL,
`q32` enum('0','1','2','3') default NULL,
`q33` enum('0','1','2','3') default NULL,
`q34` enum('0','1','2','3') default NULL,
`q35` enum('0','1','2','3') default NULL,
`q36` enum('0','1','2','3') default NULL,
`q37` enum('0','1','2','3') default NULL,
`q38` enum('0','1','2','3') default NULL,
`q39` enum('0','1','2','3') default NULL,
`q40` enum('0','1','2','3') default NULL,
`q41` enum('0','1','2','3') default NULL,
`q42` enum('0','1','2','3','not_applicable') default NULL,
`q43` enum('0','1','2','3') default NULL,
`q44` varchar(255) default NULL,
`q45` varchar(255) default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
