CREATE TABLE `CSHQ` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
relationship_to_child enum('mother','father','step_mother','step_father','other'),
other_relationship_to_child varchar (255),
`bedtime_resistance` varchar(255) default NULL,
`sleep_onset_delay` varchar(255) default NULL,
`sleep_duration` varchar(255) default NULL,
`sleep_anxiety` varchar(255) default NULL,
`night_wakings` varchar(255) default NULL,
`parasomnias` varchar(255) default NULL,
`sleep_disordered_breathing` varchar(255) default NULL,
`daytime_sleepiness` varchar(255) default NULL,
`total_score` varchar(255) default NULL,
`goes_to_bed_at_same_time_item1_frequency` enum('3','2','1') default NULL,
`goes_to_bed_at_same_time_item1_problem` enum('1','0','n/a') default NULL,
`falls_asleep_in_20_min_item2_frequency` enum('3','2','1') default NULL,
`falls_asleep_in_20_min_item2_problem` enum('1','0','n/a') default NULL,
`falls_asleep_in_own_bed_item3_frequency` enum('3','2','1') default NULL,
`falls_asleep_in_own_bed_item3_problem` enum('1','0','n/a') default NULL,
`falls_asleep_in_others_bed_item4_frequency` enum('3','2','1') default NULL,
`falls_asleep_in_others_bed_item4_problem` enum('1','0','n/a') default NULL,
`falls_asleep_with_movement_frequency` enum('3','2','1') default NULL,
`falls_asleep_with_movement_problem` enum('1','0','n/a') default NULL,
`falls_asleep_with_object_frequency` enum('3','2','1') default NULL,
`falls_asleep_with_object_problem` enum('1','0','n/a') default NULL,
`needs_parent_in_room_to_sleep_item5_frequency` enum('3','2','1') default NULL,
`needs_parent_in_room_to_sleep_item5_problem` enum('1','0','n/a') default NULL,
`ready_to_go_to_bed_frequency` enum('3','2','1') default NULL,
`ready_to_go_to_bed_problem` enum('1','0','n/a') default NULL,
`resists_going_to_bed_frequency` enum('3','2','1') default NULL,
`resists_going_to_bed_problem` enum('1','0','n/a') default NULL,
`struggles_at_bedtime_item6_frequency` enum('3','2','1') default NULL,
`struggles_at_bedtime_item6_problem` enum('1','0','n/a') default NULL,
`afraid_of_sleeping_in_dark_item7_frequency` enum('3','2','1') default NULL,
`afraid_of_sleeping_in_dark_item7_problem` enum('1','0','n/a') default NULL,
`afraid_of_sleeping_alone_item8_frequency` enum('3','2','1') default NULL,
`afraid_of_sleeping_alone_item8_problem` enum('1','0','n/a') default NULL,
`sleep_behavior_duration` varchar(255) default NULL,
`sleep_behavior_duration_hours` varchar(10),
`sleep_behavior_duration_mins` varchar(10),
`sleep_behavior_duration_status` enum('', 'dnk','refusal','not_answered') default NULL,
`sleeps_too_little_item9_frequency` enum('3','2','1') default NULL,
`sleeps_too_little_item9_problem` enum('1','0','n/a') default NULL,
`sleeps_too_much_frequency` enum('3','2','1') default NULL,
`sleeps_too_much_problem` enum('1','0','n/a') default NULL,
`sleeps_right_amount_item10_frequency` enum('3','2','1') default NULL,
`sleeps_right_amount_item10_problem` enum('1','0','n/a') default NULL,
`sleeps_same_amount_each_day_item11_frequency` enum('3','2','1') default NULL,
`sleeps_same_amount_each_day_item11_problem` enum('1','0','n/a') default NULL,
`wets_bed_at_night_item12_frequency` enum('3','2','1') default NULL,
`wets_bed_at_night_item12_problem` enum('1','0','n/a') default NULL,
`talks_during_sleep_item13_frequency` enum('3','2','1') default NULL,
`talks_during_sleep_item13_problem` enum('1','0','n/a') default NULL,
`restless_and_moves_alot_item14_frequency` enum('3','2','1') default NULL,
`restless_and_moves_alot_item14_problem` enum('1','0','n/a') default NULL,
`sleepwalks_item15_frequency` enum('3','2','1') default NULL,
`sleepwalks_item15_problem` enum('1','0','n/a') default NULL,
`moves_to_others_bed_at_night_item16_frequency` enum('3','2','1') default NULL,
`moves_to_others_bed_at_night_item16_problem` enum('1','0','n/a') default NULL,
`reports_pain_during_sleep_frequency` enum('3','2','1') default NULL,
`reports_pain_during_sleep_problem` enum('1','0','n/a') default NULL,
`reports_pain_during_sleep_body_pain` varchar(255) default NULL,
`grinds_teeth_during_sleep_item17_frequency` enum('3','2','1') default NULL,
`grinds_teeth_during_sleep_item17_problem` enum('1','0','n/a') default NULL,
`snores_loudly_item18_frequency` enum('3','2','1') default NULL,
`snores_loudly_item18_problem` enum('1','0','n/a') default NULL,
`stops_breathing_item19_frequency` enum('3','2','1') default NULL,
`stops_breathing_item19_problem` enum('1','0','n/a') default NULL,
`snorts_and_gasps_item20_frequency` enum('3','2','1') default NULL,
`snorts_and_gasps_item20_problem` enum('1','0','n/a') default NULL,
`trouble_sleeping_away_item21_frequency` enum('3','2','1') default NULL,
`trouble_sleeping_away_item21_problem` enum('1','0','n/a') default NULL,
`complains_about_sleeping_problems_frequency` enum('3','2','1') default NULL,
`complains_about_sleeping_problems_problem` enum('1','0','n/a') default NULL,
`awakens_screaming_sweating_item22_frequency` enum('3','2','1') default NULL,
`awakens_screaming_sweating_item22_problem` enum('1','0','n/a') default NULL,
`alarmed_by_scary_dream_item23_frequency` enum('3','2','1') default NULL,
`alarmed_by_scary_dream_item23_problem` enum('1','0','n/a') default NULL,
`awakes_once_item24_frequency` enum('3','2','1') default NULL,
`awakes_once_item24_problem` enum('1','0','n/a') default NULL,
`awakes_more_than_once_item25_frequency` enum('3','2','1') default NULL,
`awakes_more_than_once_item25_problem` enum('1','0','n/a') default NULL,
`returns_to_sleep_without_help_frequency` enum('3','2','1') default NULL,
`returns_to_sleep_without_help_problem` enum('1','0','n/a') default NULL,
`waking_during_night_duration` varchar(255) default NULL,
`waking_during_night_duration_status` enum('not_answered') default NULL,
`bed_time` time default NULL,
`bed_time_status` enum('', 'dnk','refusal','not_answered'),
`morning_waking_time` time default NULL,
`morning_waking_time_hours` varchar(10),
`morning_waking_time_mins` varchar(10),
`morning_waking_time_status` enum('', 'dnk','refusal','not_answered') default NULL,
`wakes_by_himself_item26_frequency` enum('3','2','1') default NULL,
`wakes_by_himself_item26_problem` enum('1','0','n/a') default NULL,
`wakes_up_in_neg_mood_item27_frequency` enum('3','2','1') default NULL,
`wakes_up_in_neg_mood_item27_problem` enum('1','0','n/a') default NULL,
`others_wake_child_item28_frequency` enum('3','2','1') default NULL,
`others_wake_child_item28_problem` enum('1','0','n/a') default NULL,
`hard_time_getting_out_of_bed_item29_frequency` enum('3','2','1') default NULL,
`hard_time_getting_out_of_bed_item29_problem` enum('1','0','n/a') default NULL,
`takes_long_time_to_be_alert_item30_frequency` enum('3','2','1') default NULL,
`takes_long_time_to_be_alert_item30_problem` enum('1','0','n/a') default NULL,
`wakes_up_early_frequency` enum('3','2','1') default NULL,
`wakes_up_early_problem` enum('1','0','n/a') default NULL,
`good_appetite_in_morning_frequency` enum('3','2','1') default NULL,
`good_appetite_in_morning_problem` enum('1','0','n/a') default NULL,
`_frequency` enum('3','2','1') default NULL,
`_problem` enum('1','0','n/a') default NULL,
`naps_during_day_frequency` enum('3','2','1') default NULL,
`naps_during_day_problem` enum('1','0','n/a') default NULL,
`suddenly_falls_asleep_frequency` enum('3','2','1') default NULL,
`suddenly_falls_asleep_problem` enum('1','0','n/a') default NULL,
`seems_tired_item31_frequency` enum('3','2','1') default NULL,
`seems_tired_item31_problem` enum('1','0','n/a') default NULL,
`play_alone` enum('1','2','3') default NULL,
`watching_tv_item32` enum('1','2','3') default NULL,
`riding_in_car_item33` enum('1','2','3') default NULL,
`eating_meals` enum('1','2','3') default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
