INSERT INTO test_names (Test_name, Full_name, Sub_Group, isDirectEntry) VALUES ('DS_Infant_Intervention_History_Form_survey', "Intervention History Form - DS-Infant - Survey", 1, 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page1', "Page 1", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page2', "Page 2", 2);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page3', "Page 3", 3);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page4', "Page 4", 4);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page5', "Page 5", 5);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page6', "Page 6", 6);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page7', "Page 7", 7);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page8', "Page 8", 8);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page9', "Page 9", 9);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('DS_Infant_Intervention_History_Form_survey','DS_Infant_Intervention_History_Form_survey_page10', "Page 10", 10);
INSERT INTO survey_test_battery (Test_name, Visit_label) VALUES ('DS_Infant_Intervention_History_Form_survey','V06');
INSERT INTO survey_test_battery (Test_name, Visit_label) VALUES ('DS_Infant_Intervention_History_Form_survey','V6-CVD');
INSERT INTO survey_test_battery (Test_name, Visit_label) VALUES ('DS_Infant_Intervention_History_Form_survey','V12');
INSERT INTO survey_test_battery (Test_name, Visit_label) VALUES ('DS_Infant_Intervention_History_Form_survey','V12-CVD');
INSERT INTO survey_test_battery (Test_name, Visit_label) VALUES ('DS_Infant_Intervention_History_Form_survey','V24');
INSERT INTO survey_test_battery (Test_name, Visit_label) VALUES ('DS_Infant_Intervention_History_Form_survey','V24-CVD');