CREATE TABLE `EEG` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Candidate_Age` VARCHAR(255) DEFAULT NULL,
`Window_Difference` VARCHAR(255) DEFAULT NULL,
`subject_ID` varchar(255) default NULL,
`age` varchar(255) default NULL,
`gender` enum('f','m','not_answered') default NULL,
`Date_taken` date default NULL,
`start_time` enum('1','2','3','4','5','6','7','8','9','10','11','12','not_answered') default NULL,
`start_time_AMPM` enum('AM','PM','not_answered') default NULL,
`experimenter_initials` varchar(255) default NULL,
`behavioral_assistant_initials` varchar(255) default NULL,
`caregiver_present` enum('y','n') default NULL,
`caregiver_role` varchar(255) default NULL,
`filename_1` varchar(255) default NULL,
`ofc` varchar(255) default NULL,
`net_serial_number` varchar(255) default NULL,
`additional_notes` text default NULL,
`impedance_before_netting` enum('y','n') default NULL,
`bad_channels_before_netting` text default NULL,
`impedance_after_netting` enum('y','n') default NULL,
`bad_channels_after_netting` text default NULL,
`net_quality_rating` enum('1','2','3','not_answered') default NULL,
`netting_notes` text default NULL,
`Photo_of_Net_Placement_Taken` enum('y','n') default NULL,
`photo_file_name` varchar(255) default NULL,
`filename_2` varchar(255) default NULL,
`note_1_1` text default NULL,
`note_1_2` text default NULL,
`note_1_3` text default NULL,
`mood_1` enum('1','2','3','4','5') default NULL,
`quality_1` enum('1','2','3') default NULL,
`trials_completed_1` varchar(255) default NULL,
`filename_3` varchar(255) default NULL,
`note_2_1` text default NULL,
`note_2_2` text default NULL,
`note_2_3` text default NULL,
`mood_2` enum('1','2','3','4','5') default NULL,
`quality_2` enum('1','2','3') default NULL,
`trials_completed_2` varchar(255) default NULL,
`filename_4` varchar(255) default NULL,
`note_3_1` text default NULL,
`note_3_2` text default NULL,
`note_3_3` text default NULL,
`mood_3` enum('1','2','3','4','5') default NULL,
`quality_3` enum('1','2','3') default NULL,
`trials_completed_3` varchar(255) default NULL,
`filename_5` varchar(255) default NULL,
`note_4_1` text default NULL,
`note_4_2` text default NULL,
`note_4_3` text default NULL,
`mood_4` enum('1','2','3','4','5') default NULL,
`quality_4` enum('1','2','3') default NULL,
`trials_completed_4` varchar(255) default NULL,
`note_5_1` text default NULL,
`end_time` enum('1','2','3','4','5','6','7','8','9','10','11','12','not_answered') default NULL,
`end_AMPM` enum('AM','PM','not_answered') default NULL,
`overall_5` enum('f','m') default NULL,
`experimental_order_5` enum('f','m') default NULL,
`note_5_2` text default NULL,
`file` varchar(255) default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
