CREATE TABLE `EEG_QC` (
  `CommentID` varchar(255) NOT NULL DEFAULT '',
  `UserID` varchar(255) DEFAULT NULL,
  `Examiner` varchar(255) DEFAULT NULL,
  `Testdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
  `Date_taken` date DEFAULT NULL,
  `Candidate_Age` varchar(255) DEFAULT NULL,
  `Window_Difference` varchar(255) DEFAULT NULL,
  `name_did_qc` varchar(255) DEFAULT NULL,
  `r_1`  varchar(255) DEFAULT NULL,
  `r_2`  text DEFAULT NULL,
  `r_3`  text DEFAULT NULL,
  `r_4`  varchar(255) DEFAULT NULL,
  `r_5`  text DEFAULT NULL,
  `v_1`  varchar(255) DEFAULT NULL,
  `v_2`  text DEFAULT NULL,
  `v_3`  text DEFAULT NULL,
  `v_4`  varchar(255) DEFAULT NULL,
  `v_5`  text DEFAULT NULL,
  `a_1`  varchar(255) DEFAULT NULL,
  `a_2`  text DEFAULT NULL,
  `a_3`  text DEFAULT NULL,
  `a_4`  varchar(255) DEFAULT NULL,
  `a_5`  text DEFAULT NULL,
  PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
