CREATE TABLE `IEP_Extraction_Form` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`academic_year` varchar(255) default NULL,
`q1_does_participant_have_504_plan` enum('no','yes') default NULL,
`q1_if_yes_select_applicable_category` enum('physical','behavioral','emotional','other') default NULL,
`q1_if_yes_summarize_accommodations` text default NULL,
`q1_if_yes_summarize_accommodations_status` enum('not_answered') default NULL,
`q2_does_participant_have_IEP` enum('no','yes') default NULL,
`q2_participant_primary_education` enum('autism','deafness','emotional_disturbance','hearing_impairment','intellectual_disability','multiple_disabilities','orthopedic_impairment','other_health_impairment','specific_learning_disability','speech_or_language_impairment','traumatic_brain_injury','visual_impairment','developmental_delay') default NULL,
`q2_participant_secondary_education` enum('autism','deafness','emotional_disturbance','hearing_impairment','intellectual_disability','multiple_disabilities','orthopedic_impairment','other_health_impairment','specific_learning_disability','speech_or_language_impairment','traumatic_brain_injury','visual_impairment','developmental_delay') default NULL,
`q2_specify_special_education_support_provided` enum('autistic_support','learning_support','life_skills_support','multiple_disabilities_support','physical_support','speech_and_language_support','emotional_support','deaf_and_hard_hearing_support','blind_support','other') default NULL,
`q2_special_education_support_notes` text default NULL,
`q2_special_education_support_notes_status` enum('not_answered') default NULL,
`q2_specify_level_of_support` enum('special_education_full_time','special_education_part_time','general_education_full_time') default NULL,
`q2_specify_pull_out_services` enum('social_skills','mathematics','reading') default NULL,
`q2_speech_therapy` enum('no','yes') default NULL,
`speech_therapy_format` enum('individual','group','consultation') default NULL,
`speech_therapy_length` enum('15_minutes','30_minutes','60_minutes') default NULL,
`speech_therapy_period` enum('weekly','biweekly','monthly') default NULL,
`speech_therapy_num_sessions` enum('1','2','3','4','5') default NULL,
`speech_therapy_notes` text default NULL,
`speech_therapy_notes_status` enum('not_answered') default NULL,
`q2_occupational_therapy` enum('no','yes') default NULL,
`occupational_therapy_format` enum('individual','group','consultation') default NULL,
`occupational_therapy_length` enum('15_minutes','30_minutes','60_minutes') default NULL,
`occupational_therapy_period` enum('weekly','biweekly','monthly') default NULL,
`occupational_therapy_num_sessions` enum('1','2','3','4','5') default NULL,
`occupational_therapy_notes` text default NULL,
`occupational_therapy_notes_status` enum('not_answered') default NULL,
`q2_physical_therapy` enum('no','yes') default NULL,
`physical_therapy_format` enum('individual','group','consultation') default NULL,
`physical_therapy_length` enum('15_minutes','30_minutes','60_minutes') default NULL,
`physical_therapy_period` enum('weekly','biweekly','monthly') default NULL,
`physical_therapy_num_sessions` enum('1','2','3','4','5') default NULL,
`physical_therapy_notes` text default NULL,
`physical_therapy_notes_status` enum('not_answered') default NULL,
`q2_other` enum('no','yes') default NULL,
`q2_other_describe` text default NULL,
`q2_other_describe_status` enum('not_answered') default NULL,
`q2_participant_receive_paraprofessional_aid` enum('no','yes') default NULL,
`q2_paraprofessional_aid_notes` text default NULL,
`q2_paraprofessional_aid_notes_status` enum('not_answered') default NULL,
`q2_participant_receive_ESY_services` enum('no','yes','not_yet_determined') default NULL,
`q2_ESY_notes` text default NULL,
`q2_ESY_notes_status` enum('not_answered') default NULL,
`q2_participant_FBA_completed_BIP_implemented` enum('no','yes') default NULL,
`q2_FBA_BIP_notes` text default NULL,
`q2_FBA_BIP_notes_status` enum('not_answered') default NULL,
`q2_describe_other_supports_provided_by_school` text default NULL,
`q2_describe_other_supports_provided_by_school_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
