CREATE TABLE `mock_scanner_training_form` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`total_mock_sessions` enum('1','2','3','4','5','6','7','8') default NULL,
`mock_time` time default NULL,
`mock_time_status` enum('dnk','refusal','not_answered') default NULL,
`session_date_1_date` date default NULL,
`session_date_1_date_status` enum('not_answered') default NULL,
`total_session_duration_1` time default NULL,
`total_session_duration_1_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_1` varchar(255) default NULL,
`session_specialist_1_status` enum('not_answered') default NULL,
`total_session_staffs_1` enum('1','2','3') default NULL,
`scan_attempt_1` enum('Yes','No','not_answered') default NULL,
`scan_acquired_1` enum('Complete','Partial','None','NA') default NULL,
`training_home_1` enum('Yes','No','not_answered') default NULL,
`training_home_yes_1` text default NULL,
`training_home_yes_1_status` enum('not_answered') default NULL,
`medication_1` enum('Yes','No','not_answered') default NULL,
`medication_yes_1` text default NULL,
`medication_yes_1_status` enum('not_answered') default NULL,
`bx_strategies_1` varchar(255) default NULL,
`session_comments_1` text default NULL,
`session_comments_1_status` enum('not_answered') default NULL,
`session_date_2_date` date default NULL,
`session_date_2_date_status` enum('not_answered') default NULL,
`total_session_duration_2` time default NULL,
`total_session_duration_2_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_2` varchar(255) default NULL,
`session_specialist_2_status` enum('not_answered') default NULL,
`total_session_staffs_2` enum('1','2','3') default NULL,
`scan_attempt_2` enum('Yes','No','not_answered') default NULL,
`scan_acquired_2` enum('Complete','Partial','None','NA') default NULL,
`training_home_2` enum('Yes','No','not_answered') default NULL,
`training_home_yes_2` text default NULL,
`training_home_yes_2_status` enum('not_answered') default NULL,
`medication_2` enum('Yes','No','not_answered') default NULL,
`medication_yes_2` text default NULL,
`medication_yes_2_status` enum('not_answered') default NULL,
`bx_strategies_2` varchar(255) default NULL,
`session_comments_2` text default NULL,
`session_comments_2_status` enum('not_answered') default NULL,
`session_date_3_date` date default NULL,
`session_date_3_date_status` enum('not_answered') default NULL,
`total_session_duration_3` time default NULL,
`total_session_duration_3_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_3` varchar(255) default NULL,
`session_specialist_3_status` enum('not_answered') default NULL,
`total_session_staffs_3` enum('1','2','3') default NULL,
`scan_attempt_3` enum('Yes','No','not_answered') default NULL,
`scan_acquired_3` enum('Complete','Partial','None','NA') default NULL,
`training_home_3` enum('Yes','No','not_answered') default NULL,
`training_home_yes_3` text default NULL,
`training_home_yes_3_status` enum('not_answered') default NULL,
`medication_3` enum('Yes','No','not_answered') default NULL,
`medication_yes_3` text default NULL,
`medication_yes_3_status` enum('not_answered') default NULL,
`bx_strategies_3` varchar(255) default NULL,
`session_comments_3` text default NULL,
`session_comments_3_status` enum('not_answered') default NULL,
`session_date_4_date` date default NULL,
`session_date_4_date_status` enum('not_answered') default NULL,
`total_session_duration_4` time default NULL,
`total_session_duration_4_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_4` varchar(255) default NULL,
`session_specialist_4_status` enum('not_answered') default NULL,
`total_session_staffs_4` enum('1','2','3') default NULL,
`scan_attempt_4` enum('Yes','No','not_answered') default NULL,
`scan_acquired_4` enum('Complete','Partial','None','NA') default NULL,
`training_home_4` enum('Yes','No','not_answered') default NULL,
`training_home_yes_4` text default NULL,
`training_home_yes_4_status` enum('not_answered') default NULL,
`medication_4` enum('Yes','No','not_answered') default NULL,
`medication_yes_4` text default NULL,
`medication_yes_4_status` enum('not_answered') default NULL,
`bx_strategies_4` varchar(255) default NULL,
`session_comments_4` text default NULL,
`session_comments_4_status` enum('not_answered') default NULL,
`session_date_5_date` date default NULL,
`session_date_5_date_status` enum('not_answered') default NULL,
`total_session_duration_5` time default NULL,
`total_session_duration_5_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_5` varchar(255) default NULL,
`session_specialist_5_status` enum('not_answered') default NULL,
`total_session_staffs_5` enum('1','2','3') default NULL,
`scan_attempt_5` enum('Yes','No','not_answered') default NULL,
`scan_acquired_5` enum('Complete','Partial','None','NA') default NULL,
`training_home_5` enum('Yes','No','not_answered') default NULL,
`training_home_yes_5` text default NULL,
`training_home_yes_5_status` enum('not_answered') default NULL,
`medication_5` enum('Yes','No','not_answered') default NULL,
`medication_yes_5` text default NULL,
`medication_yes_5_status` enum('not_answered') default NULL,
`bx_strategies_5` varchar(255) default NULL,
`session_comments_5` text default NULL,
`session_comments_5_status` enum('not_answered') default NULL,
`session_date_6_date` date default NULL,
`session_date_6_date_status` enum('not_answered') default NULL,
`total_session_duration_6` time default NULL,
`total_session_duration_6_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_6` varchar(255) default NULL,
`session_specialist_6_status` enum('not_answered') default NULL,
`total_session_staffs_6` enum('1','2','3') default NULL,
`scan_attempt_6` enum('Yes','No','not_answered') default NULL,
`scan_acquired_6` enum('Complete','Partial','None','NA') default NULL,
`training_home_6` enum('Yes','No','not_answered') default NULL,
`training_home_yes_6` text default NULL,
`training_home_yes_6_status` enum('not_answered') default NULL,
`medication_6` enum('Yes','No','not_answered') default NULL,
`medication_yes_6` text default NULL,
`medication_yes_6_status` enum('not_answered') default NULL,
`bx_strategies_6` varchar(255) default NULL,
`session_comments_6` text default NULL,
`session_comments_6_status` enum('not_answered') default NULL,
`session_date_7_date` date default NULL,
`session_date_7_date_status` enum('not_answered') default NULL,
`total_session_duration_7` time default NULL,
`total_session_duration_7_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_7` varchar(255) default NULL,
`session_specialist_7_status` enum('not_answered') default NULL,
`total_session_staffs_7` enum('1','2','3') default NULL,
`scan_attempt_7` enum('Yes','No','not_answered') default NULL,
`scan_acquired_7` enum('Complete','Partial','None','NA') default NULL,
`training_home_7` enum('Yes','No','not_answered') default NULL,
`training_home_yes_7` text default NULL,
`training_home_yes_7_status` enum('not_answered') default NULL,
`medication_7` enum('Yes','No','not_answered') default NULL,
`medication_yes_7` text default NULL,
`medication_yes_7_status` enum('not_answered') default NULL,
`bx_strategies_7` varchar(255) default NULL,
`session_comments_7` text default NULL,
`session_comments_7_status` enum('not_answered') default NULL,
`session_date_8_date` date default NULL,
`session_date_8_date_status` enum('not_answered') default NULL,
`total_session_duration_8` time default NULL,
`total_session_duration_8_status` enum('dnk','refusal','not_answered') default NULL,
`session_specialist_8` varchar(255) default NULL,
`session_specialist_8_status` enum('not_answered') default NULL,
`total_session_staffs_8` enum('1','2','3') default NULL,
`scan_attempt_8` enum('Yes','No','not_answered') default NULL,
`scan_acquired_8` enum('Complete','Partial','None','NA') default NULL,
`training_home_8` enum('Yes','No','not_answered') default NULL,
`training_home_yes_8` text default NULL,
`training_home_yes_8_status` enum('not_answered') default NULL,
`medication_8` enum('Yes','No','not_answered') default NULL,
`medication_yes_8` text default NULL,
`medication_yes_8_status` enum('not_answered') default NULL,
`bx_strategies_8` varchar(255) default NULL,
`session_comments_8` text default NULL,
`session_comments_8_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- Meta Sql Patches
INSERT INTO test_names(Test_name, Full_name, Sub_Group) VALUES('mock_scanner_training_form','Mock Scanner Training Form', 1);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('mock_scanner_training_form', '0', '0', 'Y', 'Visit', 1, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('mock_scanner_training_form', '0', '0', 'Y', 'Visit', 2, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('mock_scanner_training_form', '0', '0', 'Y', 'Visit', 3, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('mock_scanner_training_form', '0', '0', 'Y', 'Visit', 9, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('mock_scanner_training_form', '0', '0', 'Y', 'Visit', 10, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('mock_scanner_training_form', '0', '0', 'Y', 'Visit', 12, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('mock_scanner_training_form', '0', '0', 'Y', 'Visit', 13, 'VSA', NULL);
