CREATE TABLE `Mock_Scanner_Training_Version_2` (
`CommentID` varchar(255) NOT NULL default '',
`UserID` varchar(255) default NULL,
`Examiner` varchar(255) default NULL,
`Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`total_mock_sessions` enum('1','2','3','4','5','6') default NULL,
`mock_time` time default NULL,
`mock_time_status` enum('not_answered') default NULL,
`session_date_1` date default NULL,
`session_date_1_status` enum('not_answered') default NULL,
`total_session_staffs_1` enum('1','2','3') default NULL,
`total_session_duration_1` time default NULL,
`total_session_duration_1_status` enum('not_answered') default NULL,
`session_specialist_1` varchar(255) default NULL,
`session_specialist_1_status` enum('not_answered') default NULL,
`medication_1` enum('Yes','No') default NULL,
`medication_yes_1` text default NULL,
`medication_yes_1_status` enum('not_answered') default NULL,
`scan_attempt_1` enum('Yes','No') default NULL,
`scan_acquired_1` enum('Partial','None','NA') default NULL,
`training_home_1` enum('Yes','No') default NULL,
`tool_training_protocol_1` enum('Yes', 'No') default NULL,
`tool_story_board_1` enum('Yes', 'No') default NULL,
`tool_social_story_1` enum('Yes', 'No') default NULL,
`tool_site_video_1` enum('Yes', 'No') default NULL,
`tool_generic_video_1` enum('Yes', 'No') default NULL,
`tool_body_awareness_video_1` enum('Yes', 'No') default NULL,
`reinforcer_preferred_treat_1` enum('Yes', 'No') default NULL,
`reinforcer_generic_treat_1` enum('Yes', 'No') default NULL,
`reinforcer_prize_1` enum('Yes', 'No') default NULL,
`reinforcer_social_reinforcer_1` enum('Yes', 'No') default NULL,
`reinforcer_delayed_reinforcer_1` enum('Yes', 'No') default NULL,
`reinforcer_verbal_praise_1` enum('Yes', 'No') default NULL,
`reinforcer_sb_1` enum('Yes', 'No') default NULL,
`reinforcer_spin_office_chair_1` enum('Yes', 'No') default NULL,
`bx_strategies_1_wb` enum('Yes', 'No') default NULL,
`bx_strategies_1_motion_sensor` enum('Yes', 'No') default NULL,
`bx_strategies_1_pref_video` enum('Yes', 'No') default NULL,
`bx_strategies_1_verb_reminders` enum('Yes', 'No') default NULL,
`bx_strategies_1_mod_sibling` enum('Yes', 'No') default NULL,
`bx_strategies_1_increase_sound` enum('Yes', 'No') default NULL,
`bx_strategies_1_listen_music` enum('Yes', 'No') default NULL,
`bx_strategies_1_body_awareness_video` enum('Yes', 'No') default NULL,
`bx_strategies_1_competition` enum('Yes', 'No') default NULL,
`bx_strategies_1_face_camera` enum('Yes', 'No') default NULL,
`bx_strategies_1_fsv` enum('Yes', 'No') default NULL,
`bx_strategies_1_generic_power_card` enum('Yes', 'No') default NULL,
`bx_strategies_1_token_board` enum('Yes', 'No') default NULL,
`bx_strategies_1_power_cards_pref` enum('Yes', 'No') default NULL,
`bx_strategies_1_shaping` enum('Yes', 'No') default NULL,
`bx_strategies_1_social_story` enum('Yes', 'No') default NULL,
`bx_strategies_1_dance_game` enum('Yes', 'No') default NULL,
`bx_strategies_1_token_board_pref` enum('Yes', 'No') default NULL,
`bx_strategies_1_vc` enum('Yes', 'No') default NULL,
`bx_strategies_1_vsb` enum('Yes', 'No') default NULL,
`bx_strategies_1_vt` enum('Yes', 'No') default NULL,
`bx_strategies_1_simon_says` enum('Yes', 'No') default NULL,
`facade_type_1` enum('space', 'none', 'other') default NULL,
`other_facade_1` text default NULL,
`zoom_call_1` enum('Yes', 'No') default NULL,
`parent_in_room_1` enum('Yes', 'No') default NULL,
`bx_specialist_ppe_1` varchar(128) default NULL,
`subject_wearing_mask_1` enum('Yes', 'No') default NULL,
`subject_mask_breaks_1` enum('Yes', 'No') default NULL,
`how_many_breaks_1` varchar(128) default NULL,
`break_duration_1` varchar(128) default NULL,
`session_comments_1` text default NULL,
`session_comments_1_status` enum('not_answered') default NULL,
`session_date_2` date default NULL,
`session_date_2_status` enum('not_answered') default NULL,
`total_session_staffs_2` enum('1','2','3') default NULL,
`total_session_duration_2` time default NULL,
`total_session_duration_2_status` enum('not_answered') default NULL,
`session_specialist_2` varchar(255) default NULL,
`session_specialist_2_status` enum('not_answered') default NULL,
`medication_2` enum('Yes','No') default NULL,
`medication_yes_2` text default NULL,
`medication_yes_2_status` enum('not_answered') default NULL,
`scan_attempt_2` enum('Yes','No') default NULL,
`scan_acquired_2` enum('Partial','None','NA') default NULL,
`training_home_2` enum('Yes','No') default NULL,
`tool_training_protocol_2` enum('Yes', 'No') default NULL,
`tool_story_board_2` enum('Yes', 'No') default NULL,
`tool_social_story_2` enum('Yes', 'No') default NULL,
`tool_site_video_2` enum('Yes', 'No') default NULL,
`tool_generic_video_2` enum('Yes', 'No') default NULL,
`tool_body_awareness_video_2` enum('Yes', 'No') default NULL,
`reinforcer_preferred_treat_2` enum('Yes', 'No') default NULL,
`reinforcer_generic_treat_2` enum('Yes', 'No') default NULL,
`reinforcer_prize_2` enum('Yes', 'No') default NULL,
`reinforcer_social_reinforcer_2` enum('Yes', 'No') default NULL,
`reinforcer_delayed_reinforcer_2` enum('Yes', 'No') default NULL,
`reinforcer_verbal_praise_2` enum('Yes', 'No') default NULL,
`reinforcer_sb_2` enum('Yes', 'No') default NULL,
`reinforcer_spin_office_chair_2` enum('Yes', 'No') default NULL,
`bx_strategies_2_wb` enum('Yes', 'No') default NULL,
`bx_strategies_2_motion_sensor` enum('Yes', 'No') default NULL,
`bx_strategies_2_pref_video` enum('Yes', 'No') default NULL,
`bx_strategies_2_verb_reminders` enum('Yes', 'No') default NULL,
`bx_strategies_2_mod_sibling` enum('Yes', 'No') default NULL,
`bx_strategies_2_increase_sound` enum('Yes', 'No') default NULL,
`bx_strategies_2_listen_music` enum('Yes', 'No') default NULL,
`bx_strategies_2_body_awareness_video` enum('Yes', 'No') default NULL,
`bx_strategies_2_competition` enum('Yes', 'No') default NULL,
`bx_strategies_2_face_camera` enum('Yes', 'No') default NULL,
`bx_strategies_2_fsv` enum('Yes', 'No') default NULL,
`bx_strategies_2_generic_power_card` enum('Yes', 'No') default NULL,
`bx_strategies_2_token_board` enum('Yes', 'No') default NULL,
`bx_strategies_2_power_cards_pref` enum('Yes', 'No') default NULL,
`bx_strategies_2_shaping` enum('Yes', 'No') default NULL,
`bx_strategies_2_social_story` enum('Yes', 'No') default NULL,
`bx_strategies_2_dance_game` enum('Yes', 'No') default NULL,
`bx_strategies_2_token_board_pref` enum('Yes', 'No') default NULL,
`bx_strategies_2_vc` enum('Yes', 'No') default NULL,
`bx_strategies_2_vsb` enum('Yes', 'No') default NULL,
`bx_strategies_2_vt` enum('Yes', 'No') default NULL,
`bx_strategies_2_simon_says` enum('Yes', 'No') default NULL,
`facade_type_2` enum('space', 'none', 'other') default NULL,
`other_facade_2` text default NULL,
`zoom_call_2` enum('Yes', 'No') default NULL,
`parent_in_room_2` enum('Yes', 'No') default NULL,
`bx_specialist_ppe_2` varchar(128) default NULL,
`subject_wearing_mask_2` enum('Yes', 'No') default NULL,
`subject_mask_breaks_2` enum('Yes', 'No') default NULL,
`how_many_breaks_2` varchar(128) default NULL,
`break_duration_2` varchar(128) default NULL,
`session_comments_2` text default NULL,
`session_comments_2_status` enum('not_answered') default NULL,
`session_date_3` date default NULL,
`session_date_3_status` enum('not_answered') default NULL,
`total_session_staffs_3` enum('1','2','3') default NULL,
`total_session_duration_3` time default NULL,
`total_session_duration_3_status` enum('not_answered') default NULL,
`session_specialist_3` varchar(255) default NULL,
`session_specialist_3_status` enum('not_answered') default NULL,
`medication_3` enum('Yes','No') default NULL,
`medication_yes_3` text default NULL,
`medication_yes_3_status` enum('not_answered') default NULL,
`scan_attempt_3` enum('Yes','No') default NULL,
`scan_acquired_3` enum('Partial','None','NA') default NULL,
`training_home_3` enum('Yes','No') default NULL,
`tool_training_protocol_3` enum('Yes', 'No') default NULL,
`tool_story_board_3` enum('Yes', 'No') default NULL,
`tool_social_story_3` enum('Yes', 'No') default NULL,
`tool_site_video_3` enum('Yes', 'No') default NULL,
`tool_generic_video_3` enum('Yes', 'No') default NULL,
`tool_body_awareness_video_3` enum('Yes', 'No') default NULL,
`reinforcer_preferred_treat_3` enum('Yes', 'No') default NULL,
`reinforcer_generic_treat_3` enum('Yes', 'No') default NULL,
`reinforcer_prize_3` enum('Yes', 'No') default NULL,
`reinforcer_social_reinforcer_3` enum('Yes', 'No') default NULL,
`reinforcer_delayed_reinforcer_3` enum('Yes', 'No') default NULL,
`reinforcer_verbal_praise_3` enum('Yes', 'No') default NULL,
`reinforcer_sb_3` enum('Yes', 'No') default NULL,
`reinforcer_spin_office_chair_3` enum('Yes', 'No') default NULL,
`bx_strategies_3_wb` enum('Yes', 'No') default NULL,
`bx_strategies_3_motion_sensor` enum('Yes', 'No') default NULL,
`bx_strategies_3_pref_video` enum('Yes', 'No') default NULL,
`bx_strategies_3_verb_reminders` enum('Yes', 'No') default NULL,
`bx_strategies_3_mod_sibling` enum('Yes', 'No') default NULL,
`bx_strategies_3_increase_sound` enum('Yes', 'No') default NULL,
`bx_strategies_3_listen_music` enum('Yes', 'No') default NULL,
`bx_strategies_3_body_awareness_video` enum('Yes', 'No') default NULL,
`bx_strategies_3_competition` enum('Yes', 'No') default NULL,
`bx_strategies_3_face_camera` enum('Yes', 'No') default NULL,
`bx_strategies_3_fsv` enum('Yes', 'No') default NULL,
`bx_strategies_3_generic_power_card` enum('Yes', 'No') default NULL,
`bx_strategies_3_token_board` enum('Yes', 'No') default NULL,
`bx_strategies_3_power_cards_pref` enum('Yes', 'No') default NULL,
`bx_strategies_3_shaping` enum('Yes', 'No') default NULL,
`bx_strategies_3_social_story` enum('Yes', 'No') default NULL,
`bx_strategies_3_dance_game` enum('Yes', 'No') default NULL,
`bx_strategies_3_token_board_pref` enum('Yes', 'No') default NULL,
`bx_strategies_3_vc` enum('Yes', 'No') default NULL,
`bx_strategies_3_vsb` enum('Yes', 'No') default NULL,
`bx_strategies_3_vt` enum('Yes', 'No') default NULL,
`bx_strategies_3_simon_says` enum('Yes', 'No') default NULL,
`facade_type_3` enum('space', 'none', 'other') default NULL,
`other_facade_3` text default NULL,
`zoom_call_3` enum('Yes', 'No') default NULL,
`parent_in_room_3` enum('Yes', 'No') default NULL,
`bx_specialist_ppe_3` varchar(128) default NULL,
`subject_wearing_mask_3` enum('Yes', 'No') default NULL,
`subject_mask_breaks_3` enum('Yes', 'No') default NULL,
`how_many_breaks_3` varchar(128) default NULL,
`break_duration_3` varchar(128) default NULL,
`session_comments_3` text default NULL,
`session_comments_3_status` enum('not_answered') default NULL,
`session_date_4` date default NULL,
`session_date_4_status` enum('not_answered') default NULL,
`total_session_staffs_4` enum('1','2','3') default NULL,
`total_session_duration_4` time default NULL,
`total_session_duration_4_status` enum('not_answered') default NULL,
`session_specialist_4` varchar(255) default NULL,
`session_specialist_4_status` enum('not_answered') default NULL,
`medication_4` enum('Yes','No') default NULL,
`medication_yes_4` text default NULL,
`medication_yes_4_status` enum('not_answered') default NULL,
`scan_attempt_4` enum('Yes','No') default NULL,
`scan_acquired_4` enum('Partial','None','NA') default NULL,
`training_home_4` enum('Yes','No') default NULL,
`tool_training_protocol_4` enum('Yes', 'No') default NULL,
`tool_story_board_4` enum('Yes', 'No') default NULL,
`tool_social_story_4` enum('Yes', 'No') default NULL,
`tool_site_video_4` enum('Yes', 'No') default NULL,
`tool_generic_video_4` enum('Yes', 'No') default NULL,
`tool_body_awareness_video_4` enum('Yes', 'No') default NULL,
`reinforcer_preferred_treat_4` enum('Yes', 'No') default NULL,
`reinforcer_generic_treat_4` enum('Yes', 'No') default NULL,
`reinforcer_prize_4` enum('Yes', 'No') default NULL,
`reinforcer_social_reinforcer_4` enum('Yes', 'No') default NULL,
`reinforcer_delayed_reinforcer_4` enum('Yes', 'No') default NULL,
`reinforcer_verbal_praise_4` enum('Yes', 'No') default NULL,
`reinforcer_sb_4` enum('Yes', 'No') default NULL,
`reinforcer_spin_office_chair_4` enum('Yes', 'No') default NULL,
`bx_strategies_4_wb` enum('Yes', 'No') default NULL,
`bx_strategies_4_motion_sensor` enum('Yes', 'No') default NULL,
`bx_strategies_4_pref_video` enum('Yes', 'No') default NULL,
`bx_strategies_4_verb_reminders` enum('Yes', 'No') default NULL,
`bx_strategies_4_mod_sibling` enum('Yes', 'No') default NULL,
`bx_strategies_4_increase_sound` enum('Yes', 'No') default NULL,
`bx_strategies_4_listen_music` enum('Yes', 'No') default NULL,
`bx_strategies_4_body_awareness_video` enum('Yes', 'No') default NULL,
`bx_strategies_4_competition` enum('Yes', 'No') default NULL,
`bx_strategies_4_face_camera` enum('Yes', 'No') default NULL,
`bx_strategies_4_fsv` enum('Yes', 'No') default NULL,
`bx_strategies_4_generic_power_card` enum('Yes', 'No') default NULL,
`bx_strategies_4_token_board` enum('Yes', 'No') default NULL,
`bx_strategies_4_power_cards_pref` enum('Yes', 'No') default NULL,
`bx_strategies_4_shaping` enum('Yes', 'No') default NULL,
`bx_strategies_4_social_story` enum('Yes', 'No') default NULL,
`bx_strategies_4_dance_game` enum('Yes', 'No') default NULL,
`bx_strategies_4_token_board_pref` enum('Yes', 'No') default NULL,
`bx_strategies_4_vc` enum('Yes', 'No') default NULL,
`bx_strategies_4_vsb` enum('Yes', 'No') default NULL,
`bx_strategies_4_vt` enum('Yes', 'No') default NULL,
`bx_strategies_4_simon_says` enum('Yes', 'No') default NULL,
`facade_type_4` enum('space', 'none', 'other') default NULL,
`other_facade_4` text default NULL,
`zoom_call_4` enum('Yes', 'No') default NULL,
`parent_in_room_4` enum('Yes', 'No') default NULL,
`bx_specialist_ppe_4` varchar(128) default NULL,
`subject_wearing_mask_4` enum('Yes', 'No') default NULL,
`subject_mask_breaks_4` enum('Yes', 'No') default NULL,
`how_many_breaks_4` varchar(128) default NULL,
`break_duration_4` varchar(128) default NULL,
`session_comments_4` text default NULL,
`session_comments_4_status` enum('not_answered') default NULL,
`session_date_5` date default NULL,
`session_date_5_status` enum('not_answered') default NULL,
`total_session_staffs_5` enum('1','2','3') default NULL,
`total_session_duration_5` time default NULL,
`total_session_duration_5_status` enum('not_answered') default NULL,
`session_specialist_5` varchar(255) default NULL,
`session_specialist_5_status` enum('not_answered') default NULL,
`medication_5` enum('Yes','No') default NULL,
`medication_yes_5` text default NULL,
`medication_yes_5_status` enum('not_answered') default NULL,
`scan_attempt_5` enum('Yes','No') default NULL,
`scan_acquired_5` enum('Partial','None','NA') default NULL,
`training_home_5` enum('Yes','No') default NULL,
`tool_training_protocol_5` enum('Yes', 'No') default NULL,
`tool_story_board_5` enum('Yes', 'No') default NULL,
`tool_social_story_5` enum('Yes', 'No') default NULL,
`tool_site_video_5` enum('Yes', 'No') default NULL,
`tool_generic_video_5` enum('Yes', 'No') default NULL,
`tool_body_awareness_video_5` enum('Yes', 'No') default NULL,
`reinforcer_preferred_treat_5` enum('Yes', 'No') default NULL,
`reinforcer_generic_treat_5` enum('Yes', 'No') default NULL,
`reinforcer_prize_5` enum('Yes', 'No') default NULL,
`reinforcer_social_reinforcer_5` enum('Yes', 'No') default NULL,
`reinforcer_delayed_reinforcer_5` enum('Yes', 'No') default NULL,
`reinforcer_verbal_praise_5` enum('Yes', 'No') default NULL,
`reinforcer_sb_5` enum('Yes', 'No') default NULL,
`reinforcer_spin_office_chair_5` enum('Yes', 'No') default NULL,
`bx_strategies_5_wb` enum('Yes', 'No') default NULL,
`bx_strategies_5_motion_sensor` enum('Yes', 'No') default NULL,
`bx_strategies_5_pref_video` enum('Yes', 'No') default NULL,
`bx_strategies_5_verb_reminders` enum('Yes', 'No') default NULL,
`bx_strategies_5_mod_sibling` enum('Yes', 'No') default NULL,
`bx_strategies_5_increase_sound` enum('Yes', 'No') default NULL,
`bx_strategies_5_listen_music` enum('Yes', 'No') default NULL,
`bx_strategies_5_body_awareness_video` enum('Yes', 'No') default NULL,
`bx_strategies_5_competition` enum('Yes', 'No') default NULL,
`bx_strategies_5_face_camera` enum('Yes', 'No') default NULL,
`bx_strategies_5_fsv` enum('Yes', 'No') default NULL,
`bx_strategies_5_generic_power_card` enum('Yes', 'No') default NULL,
`bx_strategies_5_token_board` enum('Yes', 'No') default NULL,
`bx_strategies_5_power_cards_pref` enum('Yes', 'No') default NULL,
`bx_strategies_5_shaping` enum('Yes', 'No') default NULL,
`bx_strategies_5_social_story` enum('Yes', 'No') default NULL,
`bx_strategies_5_dance_game` enum('Yes', 'No') default NULL,
`bx_strategies_5_token_board_pref` enum('Yes', 'No') default NULL,
`bx_strategies_5_vc` enum('Yes', 'No') default NULL,
`bx_strategies_5_vsb` enum('Yes', 'No') default NULL,
`bx_strategies_5_vt` enum('Yes', 'No') default NULL,
`bx_strategies_5_simon_says` enum('Yes', 'No') default NULL,
`facade_type_5` enum('space', 'none', 'other') default NULL,
`other_facade_5` text default NULL,
`zoom_call_5` enum('Yes', 'No') default NULL,
`parent_in_room_5` enum('Yes', 'No') default NULL,
`bx_specialist_ppe_5` varchar(128) default NULL,
`subject_wearing_mask_5` enum('Yes', 'No') default NULL,
`subject_mask_breaks_5` enum('Yes', 'No') default NULL,
`how_many_breaks_5` varchar(128) default NULL,
`break_duration_5` varchar(128) default NULL,
`session_comments_5` text default NULL,
`session_comments_5_status` enum('not_answered') default NULL,
`session_date_6` date default NULL,
`session_date_6_status` enum('not_answered') default NULL,
`total_session_staffs_6` enum('1','2','3') default NULL,
`total_session_duration_6` time default NULL,
`total_session_duration_6_status` enum('not_answered') default NULL,
`session_specialist_6` varchar(255) default NULL,
`session_specialist_6_status` enum('not_answered') default NULL,
`medication_6` enum('Yes','No') default NULL,
`medication_yes_6` text default NULL,
`medication_yes_6_status` enum('not_answered') default NULL,
`scan_attempt_6` enum('Yes','No') default NULL,
`scan_acquired_6` enum('Partial','None','NA') default NULL,
`training_home_6` enum('Yes','No') default NULL,
`tool_training_protocol_6` enum('Yes', 'No') default NULL,
`tool_story_board_6` enum('Yes', 'No') default NULL,
`tool_social_story_6` enum('Yes', 'No') default NULL,
`tool_site_video_6` enum('Yes', 'No') default NULL,
`tool_generic_video_6` enum('Yes', 'No') default NULL,
`tool_body_awareness_video_6` enum('Yes', 'No') default NULL,
`reinforcer_preferred_treat_6` enum('Yes', 'No') default NULL,
`reinforcer_generic_treat_6` enum('Yes', 'No') default NULL,
`reinforcer_prize_6` enum('Yes', 'No') default NULL,
`reinforcer_social_reinforcer_6` enum('Yes', 'No') default NULL,
`reinforcer_delayed_reinforcer_6` enum('Yes', 'No') default NULL,
`reinforcer_verbal_praise_6` enum('Yes', 'No') default NULL,
`reinforcer_sb_6` enum('Yes', 'No') default NULL,
`reinforcer_spin_office_chair_6` enum('Yes', 'No') default NULL,
`bx_strategies_6_wb` enum('Yes', 'No') default NULL,
`bx_strategies_6_motion_sensor` enum('Yes', 'No') default NULL,
`bx_strategies_6_pref_video` enum('Yes', 'No') default NULL,
`bx_strategies_6_verb_reminders` enum('Yes', 'No') default NULL,
`bx_strategies_6_mod_sibling` enum('Yes', 'No') default NULL,
`bx_strategies_6_increase_sound` enum('Yes', 'No') default NULL,
`bx_strategies_6_listen_music` enum('Yes', 'No') default NULL,
`bx_strategies_6_body_awareness_video` enum('Yes', 'No') default NULL,
`bx_strategies_6_competition` enum('Yes', 'No') default NULL,
`bx_strategies_6_face_camera` enum('Yes', 'No') default NULL,
`bx_strategies_6_fsv` enum('Yes', 'No') default NULL,
`bx_strategies_6_generic_power_card` enum('Yes', 'No') default NULL,
`bx_strategies_6_token_board` enum('Yes', 'No') default NULL,
`bx_strategies_6_power_cards_pref` enum('Yes', 'No') default NULL,
`bx_strategies_6_shaping` enum('Yes', 'No') default NULL,
`bx_strategies_6_social_story` enum('Yes', 'No') default NULL,
`bx_strategies_6_dance_game` enum('Yes', 'No') default NULL,
`bx_strategies_6_token_board_pref` enum('Yes', 'No') default NULL,
`bx_strategies_6_vc` enum('Yes', 'No') default NULL,
`bx_strategies_6_vsb` enum('Yes', 'No') default NULL,
`bx_strategies_6_vt` enum('Yes', 'No') default NULL,
`bx_strategies_6_simon_says` enum('Yes', 'No') default NULL,
`facade_type_6` enum('space', 'none', 'other') default NULL,
`other_facade_6` text default NULL,
`zoom_call_6` enum('Yes', 'No') default NULL,
`parent_in_room_6` enum('Yes', 'No') default NULL,
`bx_specialist_ppe_6` varchar(128) default NULL,
`subject_wearing_mask_6` enum('Yes', 'No') default NULL,
`subject_mask_breaks_6` enum('Yes', 'No') default NULL,
`how_many_breaks_6` varchar(128) default NULL,
`break_duration_6` varchar(128) default NULL,
`session_comments_6` text default NULL,
`session_comments_6_status` enum('not_answered') default NULL,
PRIMARY KEY (`CommentID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO test_names(Test_name, Full_name, Sub_group) VALUES('Mock_Scanner_Training_Version_2','Mock Scanner Training: IBIS School Age Project', 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Mock_Scanner_Training_Version_2','Mock_Scanner_Training_Version_2_page1', "Page 1", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Mock_Scanner_Training_Version_2','Mock_Scanner_Training_Version_2_page2', "Page 2", 2);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Mock_Scanner_Training_Version_2','Mock_Scanner_Training_Version_2_page3', "Page 3", 3);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Mock_Scanner_Training_Version_2','Mock_Scanner_Training_Version_2_page4', "Page 4", 4);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Mock_Scanner_Training_Version_2','Mock_Scanner_Training_Version_2_page5', "Page 5", 5);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Mock_Scanner_Training_Version_2','Mock_Scanner_Training_Version_2_page6', "Page 6", 6);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID) VALUES ('Mock_Scanner_Training_Version_2', '0', '0', 'Y', 'Visit', 1, 'VSA-CVD', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID) VALUES ('Mock_Scanner_Training_Version_2', '0', '0', 'Y', 'Visit', 2, 'VSA-CVD', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID) VALUES ('Mock_Scanner_Training_Version_2', '0', '0', 'Y', 'Visit', 3, 'VSA-CVD', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID) VALUES ('Mock_Scanner_Training_Version_2', '0', '0', 'Y', 'Visit', 9, 'VSA-CVD', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID) VALUES ('Mock_Scanner_Training_Version_2', '0', '0', 'Y', 'Visit', 10, 'VSA-CVD', NULL);