alter table `mri_parameter_ep` ADD COLUMN `session_number` varchar(255) default NULL;
alter table `mri_parameter_ep` DROP COLUMN `record_time_enter_mri_room_1`;
alter table `mri_parameter_ep` DROP COLUMN `record_time_enter_mri_room_2`;
alter table `mri_parameter_ep` DROP COLUMN `record_time_enter_mri_room_3`;
alter table `mri_parameter_ep` DROP COLUMN `record_time_enter_mri_room_4`;
alter table `mri_parameter_ep` DROP COLUMN `orientation`;
alter table `mri_parameter_ep` DROP COLUMN `vitamine`;
alter table `mri_parameter_ep` ADD COLUMN `record_orientation_1` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `record_orientation_2` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `record_orientation_3` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `record_orientation_4` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `record_vitamine_1` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `record_vitamine_2` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `record_vitamine_3` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `record_vitamine_4` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `boldplus_attempts` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `captured_cycle` varchar(255) default NULL;
alter table `mri_parameter_ep` ADD COLUMN `acquisition_window` varchar(255) default NULL;
alter table `mri_parameter_ep` DROP COLUMN `hr_range`;
