CREATE TABLE `perinatal_data` (
`CommentID` varchar(255) NOT NULL default '',
`UserID` varchar(255),
`Examiner` varchar(255),
`Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date,
`Candidate_Age` varchar(255),
`Window_Difference` varchar(255),
`initial_weight` enum('less100','129lb','149lb','178lb','199lb','219lb','over219'),
`weight_gain` enum('less10','19lb','29lb','39lb','49lb','over49'),
`height_f` varchar(255),
`height_i` varchar(255),
`supplement_3months_before` enum('y','n'),
`supplement_during` enum('y','n'),
`condition_flu` enum('y','n'),
`condition_fever` enum('y','n'),
`condition_diabete` enum('y','n'),
`condition_eclampsia` enum('y','n'),
`condition_gestational_diabete` enum('y','n'),
`condition_pre_eclampsia` enum('y','n'),
`condition_hypermesis` enum('y','n'),
`condition_low_blood_pressure` enum('y','n'),
`condition_preterm_early_labor` enum('y','n'),
`condition_premature_membranes_rupture` enum('y','n'),
`smoking` enum('y','n'),
`tobacco` enum('y','n'),
`drinking` enum('y','n'),
`past_condition_diabete` enum('y','n'),
`past_condition_lupus` enum('y','n'),
`past_condition_high_blood_pressure` enum('y','n'),
`past_condition_asthma` enum('y','n'),
`past_condition_other_autoimmune_disorder` enum('y','n'),
`past_condition_mental_illness` enum('y','n'),
`past_condition_depression` enum('y','n'),
PRIMARY KEY  (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
