CREATE TABLE `rbs_ecs` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`repetitive_motor_number` varchar(255) default NULL,
`repetitive_motor_interfere_rating` varchar(255) default NULL,
`self_directed_injurious_number` varchar(255) default NULL,
`self_directed_injurious_interfere_rating` varchar(255) default NULL,
`restricted_number` varchar(255) default NULL,
`restricted_interfere_rating` varchar(255) default NULL,
`ritual_routine_number` varchar(255) default NULL,
`ritual_routine_interfere_rating` varchar(255) default NULL,
`composite_score_number` varchar(255) default NULL,
`composite_score_interfere_rating` varchar(255) default NULL,
`repetitive_motor_raw` varchar(255) default NULL,
`repetitive_motor_mean` varchar(255) default NULL,
`self_directed_injurious_raw` varchar(255) default NULL,
`self_directed_injurious_mean` varchar(255) default NULL,
`restricted_raw` varchar(255) default NULL,
`restricted_mean` varchar(255) default NULL,
`ritual_routine_raw` varchar(255) default NULL,
`ritual_routine_mean` varchar(255) default NULL,
`composite_score_raw` varchar(255) default NULL,
`composite_score_mean` varchar(255) default NULL,
`1_legs` enum('0','1','2','3','4') default NULL,
`2_head` enum('0','1','2','3','4') default NULL,
`3_whole_body` enum('0','1','2','3','4') default NULL,
`4_arms_hands` enum('0','1','2','3','4') default NULL,
`5_arms_hands` enum('0','1','2','3','4') default NULL,
`6_object_usage` enum('0','1','2','3','4') default NULL,
`7_mouthing_objects` enum('0','1','2','3','4') default NULL,
`8_locomotion` enum('0','1','2','3','4') default NULL,
`9_vocalizations` enum('0','1','2','3','4') default NULL,
`repetitive_motor_interfere` enum('0','1','2','3','4') default NULL,
`repetitive_motor_comment` text default NULL,
`10_hits_with_body_part` enum('0','1','2','3','4') default NULL,
`11_hits_with_object` enum('0','1','2','3','4') default NULL,
`12_hits_against_surface` enum('0','1','2','3','4') default NULL,
`13_bites` enum('0','1','2','3','4') default NULL,
`14_rubs_pokes` enum('0','1','2','3','4') default NULL,
`15_pulls_hair` enum('0','1','2','3','4') default NULL,
`16_skin_picking` enum('0','1','2','3','4') default NULL,
`self_directed_injurious_interfere` enum('0','1','2','3','4') default NULL,
`self_directed_injurious_comment` text default NULL,
`17_limited_interests` enum('0','1','2','3','4') default NULL,
`18_restricted_use_media` enum('0','1','2','3','4') default NULL,
`19_sensory_interests` enum('0','1','2','3','4') default NULL,
`20_attach_to_specific_obj` enum('0','1','2','3','4') default NULL,
`21_focus_parts_of_obj` enum('0','1','2','3','4') default NULL,
`22_stillness` enum('0','1','2','3','4') default NULL,
`23_visual_inspection` enum('0','1','2','3','4') default NULL,
`24_fascination_with_movement` enum('0','1','2','3','4') default NULL,
`restricted_interfere` enum('0','1','2','3','4') default NULL,
`restricted_comment` text default NULL,
`25_arranging` enum('0','1','2','3','4') default NULL,
`26_placement_of_objects` enum('0','1','2','3','4') default NULL,
`27_upset_visiting_new_places` enum('0','1','2','3','4') default NULL,
`28_upset_if_interrupted` enum('0','1','2','3','4') default NULL,
`29_appearance_of_others` enum('0','1','2','3','4') default NULL,
`30_inflexible_routine` enum('0','1','2','3','4') default NULL,
`31_eating_mealtime` enum('0','1','2','3','4') default NULL,
`32_sleeping_bedtime` enum('0','1','2','3','4') default NULL,
`33_play` enum('0','1','2','3','4') default NULL,
`34_social_interaction` enum('0','1','2','3','4') default NULL,
`ritual_routine_interfere` enum('0','1','2','3','4') default NULL,
`ritual_routine_comment` text default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
