CREATE TABLE `rbs_ec_survey` (
`CommentID` varchar(255) NOT NULL,
`Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date,
`Candidate_Age` varchar(255),
`Window_Difference` varchar(255),
`relationship_to_child` enum('m','f','o'),
`other_relationship_to_child` varchar(255),
`1_legs` enum('0','1','2','3','4','nk'),
`2_head` enum('0','1','2','3','4','nk'),
`3_whole_body` enum('0','1','2','3','4','nk'),
`4_arms_hands` enum('0','1','2','3','4','nk'),
`5_arms_hands` enum('0','1','2','3','4','nk'),
`6_object_usage` enum('0','1','2','3','4','nk'),
`7_mouthing_objects` enum('0','1','2','3','4','nk'),
`8_locomotion` enum('0','1','2','3','4','nk'),
`9_vocalizations` enum('0','1','2','3','4','nk'),
`10_hits_self_with_obj` enum('0','1','2','3','4','nk'),
`11_sensory_interests` enum('0','1','2','3','4','nk'),
`12_visual_inspection` enum('0','1','2','3','4','nk'),
`13_stillness` enum('0','1','2','3','4','nk'),
`14_fascination_movement` enum('0','1','2','3','4','nk'),
`comments` text,
PRIMARY KEY  (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
