CREATE TABLE `Saliva_Collection_Tracking_Form` (
  `CommentID` varchar(255) NOT NULL DEFAULT '',
  `UserID` varchar(255) DEFAULT NULL,
  `Examiner` varchar(255) DEFAULT NULL,
  `Testdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
  `Date_taken` date DEFAULT NULL,
  `Candidate_Age` varchar(255) DEFAULT NULL,
  `Window_Difference` varchar(255) DEFAULT NULL,
  `Date_Kits` date DEFAULT NULL,
  `subject_need_collection` enum('yes','no','0') DEFAULT NULL,
  `subject_how_collected` enum('At_Visit','Via_Mail') DEFAULT NULL,
  `subject_kit_used` varchar(100) DEFAULT NULL,
  `subject_visit_collection_date` date DEFAULT NULL,
  `subject_visit_mailed_to_UNC` date DEFAULT NULL,
  `subject_visit_mailed_to_UNC_status` varchar(100) DEFAULT NULL,
  `subject_visit_tracking_number` varchar(255) DEFAULT NULL,
  `subject_mail_receive` varchar(255) DEFAULT NULL,
  `subject_mail_tracking_number` varchar(255) DEFAULT NULL,
  `proband_need_collection` enum('yes','no','0'),
  `proband_need_signed_consent` enum('yes','no','0'),
  `proband_kit_used` varchar(100),
  `proband_consent` varchar(255),
  `proband_how_collected` varchar(255),
  `proband_visit_collection_date` date,
  `proband_visit_tracking_number` varchar(255),
  `proband_visit_mailed_to_UNC` date,
  `proband_visit_mailed_to_UNC_status` varchar(100),
  `proband_mail_receive` varchar(255),
  `proband_mail_tracking_number` varchar(255),
  `mother_need_collection` enum('yes','no','0'),
  `mother_how_collected` varchar(100),
  `mother_visit_collection_date` date,
  `mother_visit_mailed_to_UNC` date,
  `mother_visit_mailed_to_UNC_status` varchar(100),
  `mother_visit_tracking_number` varchar(255),
  `mother_mail_receive` varchar(255),
  `mother_mail_tracking_number` varchar(255),
  `father_need_collection` enum('yes','no','0'),
  `father_how_collected` varchar(100),
  `father_visit_collection_date` date,
  `father_visit_mailed_to_UNC` date,
  `father_visit_mailed_to_UNC_status` varchar(100),
  `father_visit_tracking_number` varchar(255),
  `father_mail_receive` varchar(255),
  `father_mail_tracking_number` varchar(255),
  `delivered_to_lab` varchar(255),
  `delivered_to_lab_date` varchar(100),
  `delivered_to_lab_by` varchar(100),
  `have_family_id` varchar(255),
  `family_id` varchar(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
