CREATE TABLE `SEQ3_Subject_Survey` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`HYPER_total_score` varchar(255) default NULL,
`HYPO_total_score` varchar(255) default NULL,
`SIRS_total_score` varchar(255) default NULL,
`EP_total_score` varchar(255) default NULL,
`SOCIAL_SENSORY_total_score` varchar(255) default NULL,
`NONSOCIAL_SENSORY_total_score` varchar(255) default NULL,
`Auditory_total_score` varchar(255) default NULL,
`Visual_total_score` varchar(255) default NULL,
`Tactile_total_score` varchar(255) default NULL,
`Gustatory_or_Oflactory_total_score` varchar(255) default NULL,
`Vestibular_total_score` varchar(255) default NULL,
`child_birth_date` date default NULL,
`person_completing_form` enum('mother','father','step_mother','step_father','both','teacher','other') default NULL,
`if_other_person` varchar(255) default NULL,
`1_react_sensitively_to_sounds` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`2_make_nosie_to_avoid_other_sounds` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`3_notice_sounds_in_environment_before_others` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`4_ignore_loud_noises` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`5_make_accurate_impersonations` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`6_demonstrates_perfect_pitch` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`7_fascinated_with_sounds` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`8_ignore_you_when_you_call_name` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`9_bothered_by_everyday_sounds` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`10_show_distress` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`11_fascinated_excited_by_others_singing` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`12_ability_to_copy_environmental_sounds` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`13_enjoy_listening_to_music` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`14_trouble_distinguishing_between_sounds` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`15_disturbed_by_bright_lights` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`16_fascinated_by_own_reflection_in_persons_eyes` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`17_stare_at_lights_or_moving_objects` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`18_avoid_face_or_gaze_during_social_games` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`19_fascinated_by_visual_effect_of_water` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`20_notice_minor_changes_in_physical_environment` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`21_fascinated_with_lights` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`22_slow_to_notice_new_objects_or_toys` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`23_slow_to_look_at_objects_near_them` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`24_notice_changes_in_visual_appearance_of_others` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`25_look_at_objects_using_side_vision` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`26_enjoy_children_videos_or_tv_programs` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`27_watch_objects_they_move_rapidly` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`28_fascinated_by_reflection_in_shiny_surfaces` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`29_look_at_angles_or_corners_of_objects` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`30_fascinated_by_flickering_or_scrolling_motions` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`31_ignore_not_notice_someone_new_or_different` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`32_watch_hands_or_fingers_move_or_flicker` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`33_visually_distracted_by_little_things_moving` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`34_trouble_distinguishing_visual_sensations` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`35_enjoy_looking_at_picture_books` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`36_dislike_cuddling_or_being_held` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`37_crave_intense_firm_touch` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`38_avoid_touching_certain_textures` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`39_like_feeling_of_air_blowing` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`40_trouble_adjusting_to_water_temperature` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`41_crave_being_tickled` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`42_dislike_being_in_water` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`43_ignore_or_not_notice_when_tap_shoulder` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`44_sensitive_to_bothered_by_sticky_material` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`45_fascinated_with_touch` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`46_bothered_by_tags_or_seams` enum('never','once_in_a_while','sometimes','frequently','always','NA') default NULL,
`47_bothered_by_tight_clothing` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`48_easily_find_objects_by_feel` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`49_show_distress_during_grooming` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`50_touch_or_rub_certain_surfaces_or_materials` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`51_react_negatively_pull_away_when_touched` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`52_dislike_being_tickled` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`53_slow_to_react_to_pain` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`54_react_negatively_to_haircuts` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`55_fascinated_with_textures_or_surfaces` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`56_unaware_of_extreme_temperatures` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`57_rub_wet_substances_on_smooth_surface` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`58_trouble_distinguishing_between_different_touch_sensations` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`59_refuse_new_foods_or_avoids_certain_foods` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`60_smell_objects_or_toys_during_play` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`61_sensitive_to_or_bothered_by_people_smell` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`62_put_objects_toys_non_food_items_in_mouth` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`63_picky_eater` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`64_crave_foods_with_strong_taste` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`65_fascinated_with_particular_taste` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`66_notice_smells_before_other_people` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`67_fascinated_with_particular_smells` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`68_mouth_suck_chew_hands_or_fingers` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`69_unaware_of_strong_unpleasant_smells_others_notice` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`70_taste_difference_between_different_brands_same_food` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`71_lick_non_food_objects` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`72_refuse_food_they_like_if_mixed_with_another` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`73_gag_in_response_to_certain_smells` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`74_trouble_distinguishing_different_tastes_or_flavors` enum('never','once_in_a_while','sometimes','frequently','always','NA') default NULL,
`75_enjoy_long_car_rides` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`76_jump_rock_spin` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`77_uneasy_or_dizzy_from_swing_merry_go_round_rocker` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`78_seek_physical_rough_housing_play` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`79_enjoy_being_upside_down` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`80_flaps_arms_or_hands_when_excited` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`81_avoid_escalators_elevators_or_other` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`82_unaware_of_moving_unstable_surfaces` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`83_react_negatively_moved_quickly_tipped_backwards_spun_around` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`84_spin_self_around_without_becoming_dizzy` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`85_unusual_postures_with_hands_fingers_arms` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`86_trouble_distinguishing_movement_sensations` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`87_trouble_looking_and_listening_same_time` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`88_report_certain_letters_or_numbers_particular_color` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`89_overwhelmed_in_places_a_lot_of_activity` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`90_event_in_sense_causes_feeling_in_different_sense` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`91_confuse_which_sense_something_is_from` enum('never','once_in_a_while','sometimes','frequently','always','NA') default NULL,
`92_more_sensitive_to_social_touch` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`93_like_to_dance_to_particular_music` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`94_increase_background_noise_to_improve_attention_to_activity` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`95_avoid_toys_make_noise_and_light_up_same_time` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`96_trouble_focusing_other_sounds_happening` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`97_shut_down_when_too_much_stimulation` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`98_how_often_experienced_sensations_differently` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`98_describe_if_applicable` text default NULL,
`99_first_noticed_differences_in_sensory_exp` enum('applicable','not_applicable') default NULL,
`99_years` varchar(255) default NULL,
`99_months` varchar(255) default NULL,
`100_how_childs_sensory_avoidances_changed_1` enum('much_less_avoidant','somewhat_less_avoidant','unchanged','somewhat_more_avoidant','much_more_avoidant') default NULL,
`100_describe_if_changed` text default NULL,
`101_how_often_childs_sensory_avoidances_interfere_daily` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`101_describe_if_applicable` text default NULL,
`102_list_comments_avoidances_to_senses` text default NULL,
`103_how_have_sensory_fascinations_changed_1` enum('much_less_intense','somewhat_less_avoidant','unchanged','somewhat_more_intense','much_more_intense') default NULL,
`103_describe_if_changed` text default NULL,
`104_how_often_sensory_fascinations_interfere_daily` enum('never','once_in_a_while','sometimes','frequently','always') default NULL,
`104_describe_if_applicable` text default NULL,
`105_list_comments_fascinations_cravings_to_senses` text default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO test_names (Test_name, Full_name, Sub_group, IsDirectEntry) VALUES ('SEQ3_Subject_Survey', 'SEQ3 (Sensory Experiences Questionnaire - Version 3.0) - FXS Subject - Survey', '1', '1');
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page1', "Page 1", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page2', "Page 2", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page3', "Page 3", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page4', "Page 4", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page5', "Page 5", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page6', "Page 6", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page7', "Page 7", 1);
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('SEQ3_Subject_Survey', 'SEQ3_Subject_Survey_page8', "Page 8", 1);

INSERT INTO survey_test_battery (Test_name, Active, SubprojectID, Visit_label) VALUES ('SEQ3_Subject_Survey', DEFAULT, 4, 'VSA');
INSERT INTO survey_test_battery (Test_name, Active, SubprojectID, Visit_label) VALUES ('SEQ3_Subject_Survey', DEFAULT, 5, 'VSA');
INSERT INTO survey_test_battery (Test_name, Active, SubprojectID, Visit_label) VALUES ('SEQ3_Subject_Survey', DEFAULT, 7, 'VSA');
INSERT INTO survey_test_battery (Test_name, Active, SubprojectID, Visit_label) VALUES ('SEQ3_Subject_Survey', DEFAULT, 4, 'VSA-CVD');
INSERT INTO survey_test_battery (Test_name, Active, SubprojectID, Visit_label) VALUES ('SEQ3_Subject_Survey', DEFAULT, 5, 'VSA-CVD');
INSERT INTO survey_test_battery (Test_name, Active, SubprojectID, Visit_label) VALUES ('SEQ3_Subject_Survey', DEFAULT, 7, 'VSA-CVD');

