CREATE TABLE `Shipley2_Data_Labels` (
`CommentID` varchar(100) NOT NULL default '',

                            `UserID` TEXT default NULL,

                            `Examiner` TEXT default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` TEXT default NULL,
`Window_Difference` TEXT default NULL,
`Uploaded_Shipley2_Data_Labels` TEXT default NULL,
`Participant_1` TEXT default NULL,
`Survey_Identifier_1` TEXT default NULL,
`Relationship_1` TEXT default NULL,
`Specify_other_relationship_1` TEXT default NULL,
`Complete1_1` TEXT default NULL,
`Survey_Timestamp_1` TEXT default NULL,
`TALK_1` TEXT default NULL,
`COUCH_1` TEXT default NULL,
`REMEMBER_1` TEXT default NULL,
`PARDON_1` TEXT default NULL,
`HIDEOUS_1` TEXT default NULL,
`MASSIVE_1` TEXT default NULL,
`PROBABLE_1` TEXT default NULL,
`IMPOSTOR_1` TEXT default NULL,
`FASCINATE_1` TEXT default NULL,
`EVIDENT_1` TEXT default NULL,
`NARRATE_1` TEXT default NULL,
`HAUL_1` TEXT default NULL,
`HILARITY_1` TEXT default NULL,
`IGNORANT_1` TEXT default NULL,
`CAPTION_1` TEXT default NULL,
`INDICATE_1` TEXT default NULL,
`SOLEMN_1` TEXT default NULL,
`FORTIFY_1` TEXT default NULL,
`MERIT_1` TEXT default NULL,
`RENOWN_1` TEXT default NULL,
`FACILITATE_1` TEXT default NULL,
`AMULET_1` TEXT default NULL,
`STERILE_1` TEXT default NULL,
`CORDIAL_1` TEXT default NULL,
`SQUANDER_1` TEXT default NULL,
`SERRATED_1` TEXT default NULL,
`PLAGIARIZE_1` TEXT default NULL,
`ORIFICE_1` TEXT default NULL,
`PRISTINE_1` TEXT default NULL,
`INNOCUOUS_1` TEXT default NULL,
`JOCOSE_1` TEXT default NULL,
`RUE_1` TEXT default NULL,
`INEXORABLE_1` TEXT default NULL,
`DIVEST_1` TEXT default NULL,
`MOLLIFY_1` TEXT default NULL,
`QUERULOUS_1` TEXT default NULL,
`ABET_1` TEXT default NULL,
`DESUETUDE_1` TEXT default NULL,
`PEREGRINATE_1` TEXT default NULL,
`QUOTIDIAN_1` TEXT default NULL,
`1_2_3_4_5_FILL_1` TEXT default NULL,
`whiteblack_shortlong_downFILL_1` TEXT default NULL,
`AB_BC_CD_DFILL_1` TEXT default NULL,
`10_1_9_2_8_FILL_1` TEXT default NULL,
`A_Z_B_Y_C_X_D_FILL_1` TEXT default NULL,
`oh_ho_rat_tar_mood_FILL_1` TEXT default NULL,
`escape_scape_cape_FILL_1` TEXT default NULL,
`mist_is_wasp_as_pint_in_toneFILL_1` TEXT default NULL,
`NE_SE_SE_NW_E_W_N_FILL_1` TEXT default NULL,
`12321_23432_34543_456_FILL_1` TEXT default NULL,
`knit_in_spud_up_both_to_stay_FILL_1` TEXT default NULL,
`57326_73265_32657_26573_FILL_1` TEXT default NULL,
`Scotland_landscape_scapegoat_FILL_ee_1` TEXT default NULL,
`3_7_5_11_2_FILL_1` TEXT default NULL,
`tam_tan_rib_rid_rat_raw_hip_FILL_1` TEXT default NULL,
`G_V_J_T_M_R_FILL_1` TEXT default NULL,
`surgeon_1234567_snore_17635_rogue_FILL_1` TEXT default NULL,
`4_11_7_20_3_FILL_1` TEXT default NULL,
`two_w_four_r_one_o_three_FILL_1` TEXT default NULL,
`thicken_10_founder_4_nectarine_FILL_1` TEXT default NULL,
`3124_82_73_154_46_13_FILL_1` TEXT default NULL,
`KW_MS_PP_TN_FILL_1` TEXT default NULL,
`pole_post_FILL_1` TEXT default NULL,
`9_6_12_7_3_FILL_1` TEXT default NULL,
`trauma_tuna_flight_fit_wife_a_FILL_glossy_gravity_1` TEXT default NULL,
`Participant_2` TEXT default NULL,
`Survey_Identifier_2` TEXT default NULL,
`Relationship_2` TEXT default NULL,
`Specify_other_relationship_2` TEXT default NULL,
`Complete1_2` TEXT default NULL,
`Survey_Timestamp_2` TEXT default NULL,
`TALK_2` TEXT default NULL,
`COUCH_2` TEXT default NULL,
`REMEMBER_2` TEXT default NULL,
`PARDON_2` TEXT default NULL,
`HIDEOUS_2` TEXT default NULL,
`MASSIVE_2` TEXT default NULL,
`PROBABLE_2` TEXT default NULL,
`IMPOSTOR_2` TEXT default NULL,
`FASCINATE_2` TEXT default NULL,
`EVIDENT_2` TEXT default NULL,
`NARRATE_2` TEXT default NULL,
`HAUL_2` TEXT default NULL,
`HILARITY_2` TEXT default NULL,
`IGNORANT_2` TEXT default NULL,
`CAPTION_2` TEXT default NULL,
`INDICATE_2` TEXT default NULL,
`SOLEMN_2` TEXT default NULL,
`FORTIFY_2` TEXT default NULL,
`MERIT_2` TEXT default NULL,
`RENOWN_2` TEXT default NULL,
`FACILITATE_2` TEXT default NULL,
`AMULET_2` TEXT default NULL,
`STERILE_2` TEXT default NULL,
`CORDIAL_2` TEXT default NULL,
`SQUANDER_2` TEXT default NULL,
`SERRATED_2` TEXT default NULL,
`PLAGIARIZE_2` TEXT default NULL,
`ORIFICE_2` TEXT default NULL,
`PRISTINE_2` TEXT default NULL,
`INNOCUOUS_2` TEXT default NULL,
`JOCOSE_2` TEXT default NULL,
`RUE_2` TEXT default NULL,
`INEXORABLE_2` TEXT default NULL,
`DIVEST_2` TEXT default NULL,
`MOLLIFY_2` TEXT default NULL,
`QUERULOUS_2` TEXT default NULL,
`ABET_2` TEXT default NULL,
`DESUETUDE_2` TEXT default NULL,
`PEREGRINATE_2` TEXT default NULL,
`QUOTIDIAN_2` TEXT default NULL,
`1_2_3_4_5_FILL_2` TEXT default NULL,
`whiteblack_shortlong_downFILL_2` TEXT default NULL,
`AB_BC_CD_DFILL_2` TEXT default NULL,
`10_1_9_2_8_FILL_2` TEXT default NULL,
`A_Z_B_Y_C_X_D_FILL_2` TEXT default NULL,
`oh_ho_rat_tar_mood_FILL_2` TEXT default NULL,
`escape_scape_cape_FILL_2` TEXT default NULL,
`mist_is_wasp_as_pint_in_toneFILL_2` TEXT default NULL,
`NE_SE_SE_NW_E_W_N_FILL_2` TEXT default NULL,
`12321_23432_34543_456_FILL_2` TEXT default NULL,
`knit_in_spud_up_both_to_stay_FILL_2` TEXT default NULL,
`57326_73265_32657_26573_FILL_2` TEXT default NULL,
`Scotland_landscape_scapegoat_FILL_ee_2` TEXT default NULL,
`3_7_5_11_2_FILL_2` TEXT default NULL,
`tam_tan_rib_rid_rat_raw_hip_FILL_2` TEXT default NULL,
`G_V_J_T_M_R_FILL_2` TEXT default NULL,
`surgeon_1234567_snore_17635_rogue_FILL_2` TEXT default NULL,
`4_11_7_20_3_FILL_2` TEXT default NULL,
`two_w_four_r_one_o_three_FILL_2` TEXT default NULL,
`thicken_10_founder_4_nectarine_FILL_2` TEXT default NULL,
`3124_82_73_154_46_13_FILL_2` TEXT default NULL,
`KW_MS_PP_TN_FILL_2` TEXT default NULL,
`pole_post_FILL_2` TEXT default NULL,
`9_6_12_7_3_FILL_2` TEXT default NULL,
`trauma_tuna_flight_fit_wife_a_FILL_glossy_gravity_2` TEXT default NULL,
`Data_dir_assessment` TEXT default NULL,
  `File_type` varchar(25) DEFAULT NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- META
INSERT INTO test_names (Test_name, Full_name, Sub_group) VALUES ('Shipley2_Data_Labels', 'Shipley2 Data Labels (Raw Data Parser)', '1');
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Shipley2_Data_Labels', 'Shipley2_Data_Labels_page1', "Page 1", 1);
-- adding to test battery
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data_Labels', '0', '0', 'Y', 'Visit', 1, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data_Labels', '0', '0', 'Y', 'Visit', 2, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data_Labels', '0', '0', 'Y', 'Visit', 3, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data_Labels', '0', '0', 'Y', 'Visit', 9, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data_Labels', '0', '0', 'Y', 'Visit', 10, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data_Labels', '0', '0', 'Y', 'Visit', 21, 'VSA', NULL);
