CREATE TABLE `Shipley2_Data` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` TEXT default NULL,

                            `Examiner` TEXT default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` TEXT default NULL,
`Window_Difference` TEXT default NULL,
`Uploaded_Shipley2_Data` TEXT default NULL,
`participant_id_1` TEXT default NULL,
`redcap_survey_identifier_1` TEXT default NULL,
`relationship_1` TEXT default NULL,
`relationship_other_1` TEXT default NULL,
`dcc_id_1` TEXT default NULL,
`intake_complete_1` TEXT default NULL,
`shipley2_timestamp_1` TEXT default NULL,
`shipley2_vocab_01_1` TEXT default NULL,
`shipley2_vocab_02_1` TEXT default NULL,
`shipley2_vocab_03_1` TEXT default NULL,
`shipley2_vocab_04_1` TEXT default NULL,
`shipley2_vocab_05_1` TEXT default NULL,
`shipley2_vocab_06_1` TEXT default NULL,
`shipley2_vocab_07_1` TEXT default NULL,
`shipley2_vocab_08_1` TEXT default NULL,
`shipley2_vocab_09_1` TEXT default NULL,
`shipley2_vocab_10_1` TEXT default NULL,
`shipley2_vocab_11_1` TEXT default NULL,
`shipley2_vocab_12_1` TEXT default NULL,
`shipley2_vocab_13_1` TEXT default NULL,
`shipley2_vocab_14_1` TEXT default NULL,
`shipley2_vocab_15_1` TEXT default NULL,
`shipley2_vocab_16_1` TEXT default NULL,
`shipley2_vocab_17_1` TEXT default NULL,
`shipley2_vocab_18_1` TEXT default NULL,
`shipley2_vocab_19_1` TEXT default NULL,
`shipley2_vocab_20_1` TEXT default NULL,
`shipley2_vocab_21_1` TEXT default NULL,
`shipley2_vocab_22_1` TEXT default NULL,
`shipley2_vocab_23_1` TEXT default NULL,
`shipley2_vocab_24_1` TEXT default NULL,
`shipley2_vocab_25_1` TEXT default NULL,
`shipley2_vocab_26_1` TEXT default NULL,
`shipley2_vocab_27_1` TEXT default NULL,
`shipley2_vocab_28_1` TEXT default NULL,
`shipley2_vocab_29_1` TEXT default NULL,
`shipley2_vocab_30_1` TEXT default NULL,
`shipley2_vocab_31_1` TEXT default NULL,
`shipley2_vocab_32_1` TEXT default NULL,
`shipley2_vocab_33_1` TEXT default NULL,
`shipley2_vocab_34_1` TEXT default NULL,
`shipley2_vocab_35_1` TEXT default NULL,
`shipley2_vocab_36_1` TEXT default NULL,
`shipley2_vocab_37_1` TEXT default NULL,
`shipley2_vocab_38_1` TEXT default NULL,
`shipley2_vocab_39_1` TEXT default NULL,
`shipley2_vocab_40_1` TEXT default NULL,
`shipley2_abstract_01_1` TEXT default NULL,
`shipley2_abstract_02_1` TEXT default NULL,
`shipley2_abstract_03_1` TEXT default NULL,
`shipley2_abstract_04_1` TEXT default NULL,
`shipley2_abstract_05_1` TEXT default NULL,
`shipley2_abstract_06_1` TEXT default NULL,
`shipley2_abstract_07_1` TEXT default NULL,
`shipley2_abstract_08_1` TEXT default NULL,
`shipley2_abstract_09_1` TEXT default NULL,
`shipley2_abstract_10_1` TEXT default NULL,
`shipley2_abstract_11_1` TEXT default NULL,
`shipley2_abstract_12_1` TEXT default NULL,
`shipley2_abstract_13_1` TEXT default NULL,
`shipley2_abstract_14_1` TEXT default NULL,
`shipley2_abstract_15_1` TEXT default NULL,
`shipley2_abstract_16_1` TEXT default NULL,
`shipley2_abstract_17_1` TEXT default NULL,
`shipley2_abstract_18_1` TEXT default NULL,
`shipley2_abstract_19_1` TEXT default NULL,
`shipley2_abstract_20_1` TEXT default NULL,
`shipley2_abstract_21_1` TEXT default NULL,
`shipley2_abstract_22_1` TEXT default NULL,
`shipley2_abstract_23_1` TEXT default NULL,
`shipley2_abstract_24_1` TEXT default NULL,
`shipley2_abstract_25_1` TEXT default NULL,
`shipley_block_01_answer_1` TEXT default NULL,
`shipley_block_02_answer_1` TEXT default NULL,
`shipley_block_03_answer_1` TEXT default NULL,
`shipley_block_04_answer_1` TEXT default NULL,
`shipley_block_05_answer1_1` TEXT default NULL,
`shipley_block_05_answer2_1` TEXT default NULL,
`shipley_block_06_answer1_1` TEXT default NULL,
`shipley_block_06_answer2_1` TEXT default NULL,
`shipley_block_07_answer1_1` TEXT default NULL,
`shipley_block_07_answer2_1` TEXT default NULL,
`shipley_block_08_answer1_1` TEXT default NULL,
`shipley_block_08_answer2_1` TEXT default NULL,
`shipley_block_09_answer1_1` TEXT default NULL,
`shipley_block_09_answer2_1` TEXT default NULL,
`shipley_block_10_answer1_1` TEXT default NULL,
`shipley_block_10_answer2_1` TEXT default NULL,
`shipley_block_10_answer3_1` TEXT default NULL,
`shipley_block_10_answer4_1` TEXT default NULL,
`shipley_block_11_answer1_1` TEXT default NULL,
`shipley_block_11_answer2_1` TEXT default NULL,
`shipley_block_11_answer3_1` TEXT default NULL,
`shipley_block_11_answer4_1` TEXT default NULL,
`shipley_block_12_answer1_1` TEXT default NULL,
`shipley_block_12_answer2_1` TEXT default NULL,
`shipley_block_12_answer3_1` TEXT default NULL,
`shipley_block_12_answer4_1` TEXT default NULL,
`shipley2_complete_1` TEXT default NULL,
`participant_id_2` TEXT default NULL,
`redcap_survey_identifier_2` TEXT default NULL,
`relationship_2` TEXT default NULL,
`relationship_other_2` TEXT default NULL,
`dcc_id_2` TEXT default NULL,
`intake_complete_2` TEXT default NULL,
`shipley2_timestamp_2` TEXT default NULL,
`shipley2_vocab_01_2` TEXT default NULL,
`shipley2_vocab_02_2` TEXT default NULL,
`shipley2_vocab_03_2` TEXT default NULL,
`shipley2_vocab_04_2` TEXT default NULL,
`shipley2_vocab_05_2` TEXT default NULL,
`shipley2_vocab_06_2` TEXT default NULL,
`shipley2_vocab_07_2` TEXT default NULL,
`shipley2_vocab_08_2` TEXT default NULL,
`shipley2_vocab_09_2` TEXT default NULL,
`shipley2_vocab_10_2` TEXT default NULL,
`shipley2_vocab_11_2` TEXT default NULL,
`shipley2_vocab_12_2` TEXT default NULL,
`shipley2_vocab_13_2` TEXT default NULL,
`shipley2_vocab_14_2` TEXT default NULL,
`shipley2_vocab_15_2` TEXT default NULL,
`shipley2_vocab_16_2` TEXT default NULL,
`shipley2_vocab_17_2` TEXT default NULL,
`shipley2_vocab_18_2` TEXT default NULL,
`shipley2_vocab_19_2` TEXT default NULL,
`shipley2_vocab_20_2` TEXT default NULL,
`shipley2_vocab_21_2` TEXT default NULL,
`shipley2_vocab_22_2` TEXT default NULL,
`shipley2_vocab_23_2` TEXT default NULL,
`shipley2_vocab_24_2` TEXT default NULL,
`shipley2_vocab_25_2` TEXT default NULL,
`shipley2_vocab_26_2` TEXT default NULL,
`shipley2_vocab_27_2` TEXT default NULL,
`shipley2_vocab_28_2` TEXT default NULL,
`shipley2_vocab_29_2` TEXT default NULL,
`shipley2_vocab_30_2` TEXT default NULL,
`shipley2_vocab_31_2` TEXT default NULL,
`shipley2_vocab_32_2` TEXT default NULL,
`shipley2_vocab_33_2` TEXT default NULL,
`shipley2_vocab_34_2` TEXT default NULL,
`shipley2_vocab_35_2` TEXT default NULL,
`shipley2_vocab_36_2` TEXT default NULL,
`shipley2_vocab_37_2` TEXT default NULL,
`shipley2_vocab_38_2` TEXT default NULL,
`shipley2_vocab_39_2` TEXT default NULL,
`shipley2_vocab_40_2` TEXT default NULL,
`shipley2_abstract_01_2` TEXT default NULL,
`shipley2_abstract_02_2` TEXT default NULL,
`shipley2_abstract_03_2` TEXT default NULL,
`shipley2_abstract_04_2` TEXT default NULL,
`shipley2_abstract_05_2` TEXT default NULL,
`shipley2_abstract_06_2` TEXT default NULL,
`shipley2_abstract_07_2` TEXT default NULL,
`shipley2_abstract_08_2` TEXT default NULL,
`shipley2_abstract_09_2` TEXT default NULL,
`shipley2_abstract_10_2` TEXT default NULL,
`shipley2_abstract_11_2` TEXT default NULL,
`shipley2_abstract_12_2` TEXT default NULL,
`shipley2_abstract_13_2` TEXT default NULL,
`shipley2_abstract_14_2` TEXT default NULL,
`shipley2_abstract_15_2` TEXT default NULL,
`shipley2_abstract_16_2` TEXT default NULL,
`shipley2_abstract_17_2` TEXT default NULL,
`shipley2_abstract_18_2` TEXT default NULL,
`shipley2_abstract_19_2` TEXT default NULL,
`shipley2_abstract_20_2` TEXT default NULL,
`shipley2_abstract_21_2` TEXT default NULL,
`shipley2_abstract_22_2` TEXT default NULL,
`shipley2_abstract_23_2` TEXT default NULL,
`shipley2_abstract_24_2` TEXT default NULL,
`shipley2_abstract_25_2` TEXT default NULL,
`shipley_block_01_answer_2` TEXT default NULL,
`shipley_block_02_answer_2` TEXT default NULL,
`shipley_block_03_answer_2` TEXT default NULL,
`shipley_block_04_answer_2` TEXT default NULL,
`shipley_block_05_answer1_2` TEXT default NULL,
`shipley_block_05_answer2_2` TEXT default NULL,
`shipley_block_06_answer1_2` TEXT default NULL,
`shipley_block_06_answer2_2` TEXT default NULL,
`shipley_block_07_answer1_2` TEXT default NULL,
`shipley_block_07_answer2_2` TEXT default NULL,
`shipley_block_08_answer1_2` TEXT default NULL,
`shipley_block_08_answer2_2` TEXT default NULL,
`shipley_block_09_answer1_2` TEXT default NULL,
`shipley_block_09_answer2_2` TEXT default NULL,
`shipley_block_10_answer1_2` TEXT default NULL,
`shipley_block_10_answer2_2` TEXT default NULL,
`shipley_block_10_answer3_2` TEXT default NULL,
`shipley_block_10_answer4_2` TEXT default NULL,
`shipley_block_11_answer1_2` TEXT default NULL,
`shipley_block_11_answer2_2` TEXT default NULL,
`shipley_block_11_answer3_2` TEXT default NULL,
`shipley_block_11_answer4_2` TEXT default NULL,
`shipley_block_12_answer1_2` TEXT default NULL,
`shipley_block_12_answer2_2` TEXT default NULL,
`shipley_block_12_answer3_2` TEXT default NULL,
`shipley_block_12_answer4_2` TEXT default NULL,
`shipley2_complete_2` TEXT default NULL,
`Data_dir_assessment` TEXT default NULL,
  `File_type` varchar(25) DEFAULT NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 -- META
INSERT INTO test_names (Test_name, Full_name, Sub_group) VALUES ('Shipley2_Data', 'Shipley2 Data', '1');
INSERT INTO instrument_subtests (Test_name, Subtest_name, Description, Order_number) VALUES ('Shipley2_Data', 'Shipley2_Data_page1', "Page 1", 1);

-- adding to test battery
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data', '0', '0', 'Y', 'Visit', 1, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data', '0', '0', 'Y', 'Visit', 2, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data', '0', '0', 'Y', 'Visit', 3, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data', '0', '0', 'Y', 'Visit', 9, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data', '0', '0', 'Y', 'Visit', 10, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Shipley2_Data', '0', '0', 'Y', 'Visit', 21, 'VSA', NULL);
