CREATE TABLE `SSIS_Behavior_lookup` (
    `form` enum('Teacher','Parent'),
    `age_range` enum('3-5','5-12','13-18'),
    `sex` enum('female','male','combined'),
    `subscale` enum('Communication','Cooperation','Assertion','Responsibility','Empathy','Engagement','Self-Control','Externalizing','Bullying','Hyperactivity/Inattention','Internalizing','Autism Spectrum'),
    `behavior_level` enum('Below Average','Average','Above Average'),
    `score_min` int(2) default NULL,
    `score_max` int(2) default NULL,
     PRIMARY KEY  (`form`,`age_range`,`sex`,`subscale`,`behavior_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SSIS_Behavior_lookup VALUES
('Teacher','5-12','female','Communication','Below Average',0,12),
('Teacher','5-12','female','Communication','Average',13,20),
('Teacher','5-12','female','Communication','Above Average',21,21),
('Teacher','5-12','female','Cooperation','Below Average',0,9),
('Teacher','5-12','female','Cooperation','Average',10,17),
('Teacher','5-12','female','Cooperation','Above Average',18,18),
('Teacher','5-12','female','Assertion','Below Average',0,8),
('Teacher','5-12','female','Assertion','Average',9,16),
('Teacher','5-12','female','Assertion','Above Average',17,21),
('Teacher','5-12','female','Responsibility','Below Average',0,10),
('Teacher','5-12','female','Responsibility','Average',11,18),
('Teacher','5-12','female','Responsibility','Above Average',DEFAULT,DEFAULT),
('Teacher','5-12','female','Empathy','Below Average',0,9),
('Teacher','5-12','female','Empathy','Average',10,17),
('Teacher','5-12','female','Empathy','Above Average',18,18),
('Teacher','5-12','female','Engagement','Below Average',0,11),
('Teacher','5-12','female','Engagement','Average',12,18),
('Teacher','5-12','female','Engagement','Above Average',19,21),
('Teacher','5-12','female','Self-Control','Below Average',0,10),
('Teacher','5-12','female','Self-Control','Average',11,19),
('Teacher','5-12','female','Self-Control','Above Average',20,21),
('Teacher','5-12','female','Externalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','female','Externalizing','Average',0,10),
('Teacher','5-12','female','Externalizing','Above Average',11,36),
('Teacher','5-12','female','Bullying','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','female','Bullying','Average',0,3),
('Teacher','5-12','female','Bullying','Above Average',4,15),
('Teacher','5-12','female','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','female','Hyperactivity/Inattention','Average',0,8),
('Teacher','5-12','female','Hyperactivity/Inattention','Above Average',9,21),
('Teacher','5-12','female','Internalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','female','Internalizing','Average',0,6),
('Teacher','5-12','female','Internalizing','Above Average',7,21),
('Teacher','5-12','female','Autism Spectrum','Below Average',0,1),
('Teacher','5-12','female','Autism Spectrum','Average',2,13),
('Teacher','5-12','female','Autism Spectrum','Above Average',14,45),
('Teacher','5-12','male','Communication','Below Average',0,10),
('Teacher','5-12','male','Communication','Average',11,19),
('Teacher','5-12','male','Communication','Above Average',20,21),
('Teacher','5-12','male','Cooperation','Below Average',0,7),
('Teacher','5-12','male','Cooperation','Average',8,16),
('Teacher','5-12','male','Cooperation','Above Average',17,18),
('Teacher','5-12','male','Assertion','Below Average',0,7),
('Teacher','5-12','male','Assertion','Average',8,16),
('Teacher','5-12','male','Assertion','Above Average',17,21),
('Teacher','5-12','male','Responsibility','Below Average',0,7),
('Teacher','5-12','male','Responsibility','Average',8,16),
('Teacher','5-12','male','Responsibility','Above Average',17,18),
('Teacher','5-12','male','Empathy','Below Average',0,6),
('Teacher','5-12','male','Empathy','Average',7,15),
('Teacher','5-12','male','Empathy','Above Average',16,18),
('Teacher','5-12','male','Engagement','Below Average',0,9),
('Teacher','5-12','male','Engagement','Average',10,18),
('Teacher','5-12','male','Engagement','Above Average',19,21),
('Teacher','5-12','male','Self-Control','Below Average',0,8),
('Teacher','5-12','male','Self-Control','Average',9,18),
('Teacher','5-12','male','Self-Control','Above Average',19,21),
('Teacher','5-12','male','Externalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','male','Externalizing','Average',0,13),
('Teacher','5-12','male','Externalizing','Above Average',14,36),
('Teacher','5-12','male','Bullying','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','male','Bullying','Average',0,4),
('Teacher','5-12','male','Bullying','Above Average',5,15),
('Teacher','5-12','male','Hyperactivity/Inattention','Below Average',0,0),
('Teacher','5-12','male','Hyperactivity/Inattention','Average',1,11),
('Teacher','5-12','male','Hyperactivity/Inattention','Above Average',12,21),
('Teacher','5-12','male','Internalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','male','Internalizing','Average',0,7),
('Teacher','5-12','male','Internalizing','Above Average',8,21),
('Teacher','5-12','male','Autism Spectrum','Below Average',0,3),
('Teacher','5-12','male','Autism Spectrum','Average',4,17),
('Teacher','5-12','male','Autism Spectrum','Above Average',18,45),
('Teacher','5-12','combined','Communication','Below Average',0,11),
('Teacher','5-12','combined','Communication','Average',12,19),
('Teacher','5-12','combined','Communication','Above Average',20,21),
('Teacher','5-12','combined','Cooperation','Below Average',0,8),
('Teacher','5-12','combined','Cooperation','Average',9,16),
('Teacher','5-12','combined','Cooperation','Above Average',17,18),
('Teacher','5-12','combined','Assertion','Below Average',0,7),
('Teacher','5-12','combined','Assertion','Average',8,16),
('Teacher','5-12','combined','Assertion','Above Average',17,21),
('Teacher','5-12','combined','Responsibility','Below Average',0,8),
('Teacher','5-12','combined','Responsibility','Average',9,17),
('Teacher','5-12','combined','Responsibility','Above Average',18,18),
('Teacher','5-12','combined','Empathy','Below Average',0,8),
('Teacher','5-12','combined','Empathy','Average',9,16),
('Teacher','5-12','combined','Empathy','Above Average',17,18),
('Teacher','5-12','combined','Engagement','Below Average',0,10),
('Teacher','5-12','combined','Engagement','Average',11,18),
('Teacher','5-12','combined','Engagement','Above Average',19,21),
('Teacher','5-12','combined','Self-Control','Below Average',0,9),
('Teacher','5-12','combined','Self-Control','Average',10,18),
('Teacher','5-12','combined','Self-Control','Above Average',19,21),
('Teacher','5-12','combined','Externalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','combined','Externalizing','Average',0,12),
('Teacher','5-12','combined','Externalizing','Above Average',13,36),
('Teacher','5-12','combined','Bullying','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','combined','Bullying','Average',0,4),
('Teacher','5-12','combined','Bullying','Above Average',5,15),
('Teacher','5-12','combined','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','combined','Hyperactivity/Inattention','Average',0,9),
('Teacher','5-12','combined','Hyperactivity/Inattention','Above Average',10,21),
('Teacher','5-12','combined','Internalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','5-12','combined','Internalizing','Average',0,7),
('Teacher','5-12','combined','Internalizing','Above Average',8,21),
('Teacher','5-12','combined','Autism Spectrum','Below Average',0,2),
('Teacher','5-12','combined','Autism Spectrum','Average',3,15),
('Teacher','5-12','combined','Autism Spectrum','Above Average',16,45),
('Teacher','13-18','female','Communication','Below Average',0,12),
('Teacher','13-18','female','Communication','Average',13,21),
('Teacher','13-18','female','Communication','Above Average',DEFAULT,DEFAULT),
('Teacher','13-18','female','Cooperation','Below Average',0,10),
('Teacher','13-18','female','Cooperation','Average',11,18),
('Teacher','13-18','female','Cooperation','Above Average',DEFAULT,DEFAULT),
('Teacher','13-18','female','Assertion','Below Average',0,7),
('Teacher','13-18','female','Assertion','Average',8,17),
('Teacher','13-18','female','Assertion','Above Average',18,21),
('Teacher','13-18','female','Responsibility','Below Average',0,10),
('Teacher','13-18','female','Responsibility','Average',11,18),
('Teacher','13-18','female','Responsibility','Above Average',DEFAULT,DEFAULT),
('Teacher','13-18','female','Empathy','Below Average',0,8),
('Teacher','13-18','female','Empathy','Average',9,17),
('Teacher','13-18','female','Empathy','Above Average',18,18),
('Teacher','13-18','female','Engagement','Below Average',0,10),
('Teacher','13-18','female','Engagement','Average',11,19),
('Teacher','13-18','female','Engagement','Above Average',20,21),
('Teacher','13-18','female','Self-Control','Below Average',0,9),
('Teacher','13-18','female','Self-Control','Average',10,20),
('Teacher','13-18','female','Self-Control','Above Average',21,21),
('Teacher','13-18','female','Externalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','female','Externalizing','Average',0,7),
('Teacher','13-18','female','Externalizing','Above Average',8,36),
('Teacher','13-18','female','Bullying','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','female','Bullying','Average',0,3),
('Teacher','13-18','female','Bullying','Above Average',4,15),
('Teacher','13-18','female','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','female','Hyperactivity/Inattention','Average',0,5),
('Teacher','13-18','female','Hyperactivity/Inattention','Above Average',6,21),
('Teacher','13-18','female','Internalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','female','Internalizing','Average',0,7),
('Teacher','13-18','female','Internalizing','Above Average',8,21),
('Teacher','13-18','female','Autism Spectrum','Below Average',0,0),
('Teacher','13-18','female','Autism Spectrum','Average',1,12),
('Teacher','13-18','female','Autism Spectrum','Above Average',13,45),
('Teacher','13-18','male','Communication','Below Average',0,12),
('Teacher','13-18','male','Communication','Average',13,19),
('Teacher','13-18','male','Communication','Above Average',20,21),
('Teacher','13-18','male','Cooperation','Below Average',0,9),
('Teacher','13-18','male','Cooperation','Average',10,16),
('Teacher','13-18','male','Cooperation','Above Average',17,18),
('Teacher','13-18','male','Assertion','Below Average',0,8),
('Teacher','13-18','male','Assertion','Average',9,17),
('Teacher','13-18','male','Assertion','Above Average',18,21),
('Teacher','13-18','male','Responsibility','Below Average',0,9),
('Teacher','13-18','male','Responsibility','Average',10,17),
('Teacher','13-18','male','Responsibility','Above Average',18,18),
('Teacher','13-18','male','Empathy','Below Average',0,7),
('Teacher','13-18','male','Empathy','Average',8,15),
('Teacher','13-18','male','Empathy','Above Average',16,18),
('Teacher','13-18','male','Engagement','Below Average',0,10),
('Teacher','13-18','male','Engagement','Average',11,19),
('Teacher','13-18','male','Engagement','Above Average',20,21),
('Teacher','13-18','male','Self-Control','Below Average',0,9),
('Teacher','13-18','male','Self-Control','Average',10,19),
('Teacher','13-18','male','Self-Control','Above Average',20,21),
('Teacher','13-18','male','Externalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','male','Externalizing','Average',0,10),
('Teacher','13-18','male','Externalizing','Above Average',11,36),
('Teacher','13-18','male','Bullying','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','male','Bullying','Average',0,3),
('Teacher','13-18','male','Bullying','Above Average',4,15),
('Teacher','13-18','male','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','male','Hyperactivity/Inattention','Average',0,7),
('Teacher','13-18','male','Hyperactivity/Inattention','Above Average',8,21),
('Teacher','13-18','male','Internalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','male','Internalizing','Average',0,7),
('Teacher','13-18','male','Internalizing','Above Average',8,21),
('Teacher','13-18','male','Autism Spectrum','Below Average',0,2),
('Teacher','13-18','male','Autism Spectrum','Average',3,14),
('Teacher','13-18','male','Autism Spectrum','Above Average',15,45),
('Teacher','13-18','combined','Communication','Below Average',0,12),
('Teacher','13-18','combined','Communication','Average',13,20),
('Teacher','13-18','combined','Communication','Above Average',21,21),
('Teacher','13-18','combined','Cooperation','Below Average',0,9),
('Teacher','13-18','combined','Cooperation','Average',10,17),
('Teacher','13-18','combined','Cooperation','Above Average',18,18),
('Teacher','13-18','combined','Assertion','Below Average',0,7),
('Teacher','13-18','combined','Assertion','Average',8,17),
('Teacher','13-18','combined','Assertion','Above Average',18,21),
('Teacher','13-18','combined','Responsibility','Below Average',0,10),
('Teacher','13-18','combined','Responsibility','Average',11,17),
('Teacher','13-18','combined','Responsibility','Above Average',18,18),
('Teacher','13-18','combined','Empathy','Below Average',0,7),
('Teacher','13-18','combined','Empathy','Average',8,16),
('Teacher','13-18','combined','Empathy','Above Average',17,18),
('Teacher','13-18','combined','Engagement','Below Average',0,10),
('Teacher','13-18','combined','Engagement','Average',11,19),
('Teacher','13-18','combined','Engagement','Above Average',20,21),
('Teacher','13-18','combined','Self-Control','Below Average',0,9),
('Teacher','13-18','combined','Self-Control','Average',10,19),
('Teacher','13-18','combined','Self-Control','Above Average',20,21),
('Teacher','13-18','combined','Externalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','combined','Externalizing','Average',0,8),
('Teacher','13-18','combined','Externalizing','Above Average',9,36),
('Teacher','13-18','combined','Bullying','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','combined','Bullying','Average',0,3),
('Teacher','13-18','combined','Bullying','Above Average',4,15),
('Teacher','13-18','combined','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','combined','Hyperactivity/Inattention','Average',0,6),
('Teacher','13-18','combined','Hyperactivity/Inattention','Above Average',7,21),
('Teacher','13-18','combined','Internalizing','Below Average',DEFAULT,DEFAULT),
('Teacher','13-18','combined','Internalizing','Average',0,7),
('Teacher','13-18','combined','Internalizing','Above Average',8,21),
('Teacher','13-18','combined','Autism Spectrum','Below Average',0,1),
('Teacher','13-18','combined','Autism Spectrum','Average',2,13),
('Teacher','13-18','combined','Autism Spectrum','Above Average',14,45);

INSERT INTO SSIS_Behavior_lookup VALUES
('Parent','5-12','female','Communication','Below Average',0,12),
('Parent','5-12','female','Communication','Average',13,19),
('Parent','5-12','female','Communication','Above Average',20,21),
('Parent','5-12','female','Cooperation','Below Average',0,10),
('Parent','5-12','female','Cooperation','Average',11,16),
('Parent','5-12','female','Cooperation','Above Average',17,18),
('Parent','5-12','female','Assertion','Below Average',0,11),
('Parent','5-12','female','Assertion','Average',12,19),
('Parent','5-12','female','Assertion','Above Average',20,21),
('Parent','5-12','female','Responsibility','Below Average',0,9),
('Parent','5-12','female','Responsibility','Average',10,16),
('Parent','5-12','female','Responsibility','Above Average',17,18),
('Parent','5-12','female','Empathy','Below Average',0,10),
('Parent','5-12','female','Empathy','Average',11,17),
('Parent','5-12','female','Empathy','Above Average',18,18),
('Parent','5-12','female','Engagement','Below Average',0,11),
('Parent','5-12','female','Engagement','Average',12,19),
('Parent','5-12','female','Engagement','Above Average',20,21),
('Parent','5-12','female','Self-Control','Below Average',0,8),
('Parent','5-12','female','Self-Control','Average',9,16),
('Parent','5-12','female','Self-Control','Above Average',17,21),
('Parent','5-12','female','Externalizing','Below Average',0,0),
('Parent','5-12','female','Externalizing','Average',1,11),
('Parent','5-12','female','Externalizing','Above Average',12,36),
('Parent','5-12','female','Bullying','Below Average',DEFAULT,DEFAULT),
('Parent','5-12','female','Bullying','Average',0,3),
('Parent','5-12','female','Bullying','Above Average',4,15),
('Parent','5-12','female','Hyperactivity/Inattention','Below Average',0,0),
('Parent','5-12','female','Hyperactivity/Inattention','Average',1,8),
('Parent','5-12','female','Hyperactivity/Inattention','Above Average',9,21),
('Parent','5-12','female','Internalizing','Below Average',0,0),
('Parent','5-12','female','Internalizing','Average',1,9),
('Parent','5-12','female','Internalizing','Above Average',10,30),
('Parent','5-12','female','Autism Spectrum','Below Average',0,2),
('Parent','5-12','female','Autism Spectrum','Average',3,13),
('Parent','5-12','female','Autism Spectrum','Above Average',14,45),
('Parent','5-12','male','Communication','Below Average',0,12),
('Parent','5-12','male','Communication','Average',13,19),
('Parent','5-12','male','Communication','Above Average',20,21),
('Parent','5-12','male','Cooperation','Below Average',0,9),
('Parent','5-12','male','Cooperation','Average',10,16),
('Parent','5-12','male','Cooperation','Above Average',17,18),
('Parent','5-12','male','Assertion','Below Average',0,10),
('Parent','5-12','male','Assertion','Average',11,18),
('Parent','5-12','male','Assertion','Above Average',19,21),
('Parent','5-12','male','Responsibility','Below Average',0,9),
('Parent','5-12','male','Responsibility','Average',10,16),
('Parent','5-12','male','Responsibility','Above Average',17,18),
('Parent','5-12','male','Empathy','Below Average',0,9),
('Parent','5-12','male','Empathy','Average',10,16),
('Parent','5-12','male','Empathy','Above Average',17,18),
('Parent','5-12','male','Engagement','Below Average',0,11),
('Parent','5-12','male','Engagement','Average',12,19),
('Parent','5-12','male','Engagement','Above Average',20,21),
('Parent','5-12','male','Self-Control','Below Average',0,7),
('Parent','5-12','male','Self-Control','Average',8,16),
('Parent','5-12','male','Self-Control','Above Average',17,21),
('Parent','5-12','male','Externalizing','Below Average',0,1),
('Parent','5-12','male','Externalizing','Average',2,13),
('Parent','5-12','male','Externalizing','Above Average',14,36),
('Parent','5-12','male','Bullying','Below Average',DEFAULT,DEFAULT),
('Parent','5-12','male','Bullying','Average',0,3),
('Parent','5-12','male','Bullying','Above Average',4,15),
('Parent','5-12','male','Hyperactivity/Inattention','Below Average',0,0),
('Parent','5-12','male','Hyperactivity/Inattention','Average',1,9),
('Parent','5-12','male','Hyperactivity/Inattention','Above Average',10,21),
('Parent','5-12','male','Internalizing','Below Average',0,0),
('Parent','5-12','male','Internalizing','Average',1,9),
('Parent','5-12','male','Internalizing','Above Average',10,30),
('Parent','5-12','male','Autism Spectrum','Below Average',0,2),
('Parent','5-12','male','Autism Spectrum','Average',3,14),
('Parent','5-12','male','Autism Spectrum','Above Average',15,45),
('Parent','5-12','combined','Communication','Below Average',0,12),
('Parent','5-12','combined','Communication','Average',13,19),
('Parent','5-12','combined','Communication','Above Average',20,21),
('Parent','5-12','combined','Cooperation','Below Average',0,9),
('Parent','5-12','combined','Cooperation','Average',10,16),
('Parent','5-12','combined','Cooperation','Above Average',17,18),
('Parent','5-12','combined','Assertion','Below Average',0,11),
('Parent','5-12','combined','Assertion','Average',12,18),
('Parent','5-12','combined','Assertion','Above Average',19,21),
('Parent','5-12','combined','Responsibility','Below Average',0,9),
('Parent','5-12','combined','Responsibility','Average',10,16),
('Parent','5-12','combined','Responsibility','Above Average',17,18),
('Parent','5-12','combined','Empathy','Below Average',0,9),
('Parent','5-12','combined','Empathy','Average',10,17),
('Parent','5-12','combined','Empathy','Above Average',18,18),
('Parent','5-12','combined','Engagement','Below Average',0,11),
('Parent','5-12','combined','Engagement','Average',12,19),
('Parent','5-12','combined','Engagement','Above Average',20,21),
('Parent','5-12','combined','Self-Control','Below Average',0,7),
('Parent','5-12','combined','Self-Control','Average',8,16),
('Parent','5-12','combined','Self-Control','Above Average',17,21),
('Parent','5-12','combined','Externalizing','Below Average',0,0),
('Parent','5-12','combined','Externalizing','Average',1,12),
('Parent','5-12','combined','Externalizing','Above Average',13,36),
('Parent','5-12','combined','Bullying','Below Average',DEFAULT,DEFAULT),
('Parent','5-12','combined','Bullying','Average',0,3),
('Parent','5-12','combined','Bullying','Above Average',4,15),
('Parent','5-12','combined','Hyperactivity/Inattention','Below Average',0,0),
('Parent','5-12','combined','Hyperactivity/Inattention','Average',1,9),
('Parent','5-12','combined','Hyperactivity/Inattention','Above Average',10,21),
('Parent','5-12','combined','Internalizing','Below Average',0,0),
('Parent','5-12','combined','Internalizing','Average',1,9),
('Parent','5-12','combined','Internalizing','Above Average',10,30),
('Parent','5-12','combined','Autism Spectrum','Below Average',0,2),
('Parent','5-12','combined','Autism Spectrum','Average',3,14),
('Parent','5-12','combined','Autism Spectrum','Above Average',15,45),
('Parent','13-18','female','Communication','Below Average',0,13),
('Parent','13-18','female','Communication','Average',14,20),
('Parent','13-18','female','Communication','Above Average',21,21),
('Parent','13-18','female','Cooperation','Below Average',0,10),
('Parent','13-18','female','Cooperation','Average',11,17),
('Parent','13-18','female','Cooperation','Above Average',18,18),
('Parent','13-18','female','Assertion','Below Average',0,11),
('Parent','13-18','female','Assertion','Average',12,18),
('Parent','13-18','female','Assertion','Above Average',19,21),
('Parent','13-18','female','Responsibility','Below Average',0,11),
('Parent','13-18','female','Responsibility','Average',12,18),
('Parent','13-18','female','Responsibility','Above Average',DEFAULT,DEFAULT),
('Parent','13-18','female','Empathy','Below Average',0,10),
('Parent','13-18','female','Empathy','Average',11,17),
('Parent','13-18','female','Empathy','Above Average',18,18),
('Parent','13-18','female','Engagement','Below Average',0,10),
('Parent','13-18','female','Engagement','Average',11,19),
('Parent','13-18','female','Engagement','Above Average',20,21),
('Parent','13-18','female','Self-Control','Below Average',0,8),
('Parent','13-18','female','Self-Control','Average',9,17),
('Parent','13-18','female','Self-Control','Above Average',18,21),
('Parent','13-18','female','Externalizing','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','female','Externalizing','Average',0,9),
('Parent','13-18','female','Externalizing','Above Average',10,36),
('Parent','13-18','female','Bullying','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','female','Bullying','Average',0,2),
('Parent','13-18','female','Bullying','Above Average',3,15),
('Parent','13-18','female','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','female','Hyperactivity/Inattention','Average',0,7),
('Parent','13-18','female','Hyperactivity/Inattention','Above Average',8,21),
('Parent','13-18','female','Internalizing','Below Average',0,0),
('Parent','13-18','female','Internalizing','Average',1,9),
('Parent','13-18','female','Internalizing','Above Average',10,30),
('Parent','13-18','female','Autism Spectrum','Below Average',0,1),
('Parent','13-18','female','Autism Spectrum','Average',2,12),
('Parent','13-18','female','Autism Spectrum','Above Average',13,45),
('Parent','13-18','male','Communication','Below Average',0,12),
('Parent','13-18','male','Communication','Average',13,20),
('Parent','13-18','male','Communication','Above Average',21,21),
('Parent','13-18','male','Cooperation','Below Average',0,10),
('Parent','13-18','male','Cooperation','Average',11,17),
('Parent','13-18','male','Cooperation','Above Average',18,18),
('Parent','13-18','male','Assertion','Below Average',0,10),
('Parent','13-18','male','Assertion','Average',11,18),
('Parent','13-18','male','Assertion','Above Average',19,21),
('Parent','13-18','male','Responsibility','Below Average',0,9),
('Parent','13-18','male','Responsibility','Average',10,17),
('Parent','13-18','male','Responsibility','Above Average',18,18),
('Parent','13-18','male','Empathy','Below Average',0,9),
('Parent','13-18','male','Empathy','Average',10,16),
('Parent','13-18','male','Empathy','Above Average',17,18),
('Parent','13-18','male','Engagement','Below Average',0,10),
('Parent','13-18','male','Engagement','Average',11,19),
('Parent','13-18','male','Engagement','Above Average',20,21),
('Parent','13-18','male','Self-Control','Below Average',0,8),
('Parent','13-18','male','Self-Control','Average',9,17),
('Parent','13-18','male','Self-Control','Above Average',18,21),
('Parent','13-18','male','Externalizing','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','male','Externalizing','Average',0,11),
('Parent','13-18','male','Externalizing','Above Average',12,36),
('Parent','13-18','male','Bullying','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','male','Bullying','Average',0,3),
('Parent','13-18','male','Bullying','Above Average',4,15),
('Parent','13-18','male','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','male','Hyperactivity/Inattention','Average',0,8),
('Parent','13-18','male','Hyperactivity/Inattention','Above Average',9,21),
('Parent','13-18','male','Internalizing','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','male','Internalizing','Average',0,9),
('Parent','13-18','male','Internalizing','Above Average',10,30),
('Parent','13-18','male','Autism Spectrum','Below Average',0,1),
('Parent','13-18','male','Autism Spectrum','Average',2,14),
('Parent','13-18','male','Autism Spectrum','Above Average',15,45),
('Parent','13-18','combined','Communication','Below Average',0,12),
('Parent','13-18','combined','Communication','Average',13,20),
('Parent','13-18','combined','Communication','Above Average',21,21),
('Parent','13-18','combined','Cooperation','Below Average',0,10),
('Parent','13-18','combined','Cooperation','Average',11,17),
('Parent','13-18','combined','Cooperation','Above Average',18,18),
('Parent','13-18','combined','Assertion','Below Average',0,11),
('Parent','13-18','combined','Assertion','Average',12,18),
('Parent','13-18','combined','Assertion','Above Average',19,21),
('Parent','13-18','combined','Responsibility','Below Average',0,10),
('Parent','13-18','combined','Responsibility','Average',11,17),
('Parent','13-18','combined','Responsibility','Above Average',18,18),
('Parent','13-18','combined','Empathy','Below Average',0,9),
('Parent','13-18','combined','Empathy','Average',10,17),
('Parent','13-18','combined','Empathy','Above Average',18,18),
('Parent','13-18','combined','Engagement','Below Average',0,10),
('Parent','13-18','combined','Engagement','Average',11,19),
('Parent','13-18','combined','Engagement','Above Average',20,21),
('Parent','13-18','combined','Self-Control','Below Average',0,8),
('Parent','13-18','combined','Self-Control','Average',9,17),
('Parent','13-18','combined','Self-Control','Above Average',18,21),
('Parent','13-18','combined','Externalizing','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','combined','Externalizing','Average',0,10),
('Parent','13-18','combined','Externalizing','Above Average',11,36),
('Parent','13-18','combined','Bullying','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','combined','Bullying','Average',0,3),
('Parent','13-18','combined','Bullying','Above Average',4,15),
('Parent','13-18','combined','Hyperactivity/Inattention','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','combined','Hyperactivity/Inattention','Average',0,7),
('Parent','13-18','combined','Hyperactivity/Inattention','Above Average',8,21),
('Parent','13-18','combined','Internalizing','Below Average',DEFAULT,DEFAULT),
('Parent','13-18','combined','Internalizing','Average',0,9),
('Parent','13-18','combined','Internalizing','Above Average',10,30),
('Parent','13-18','combined','Autism Spectrum','Below Average',0,1),
('Parent','13-18','combined','Autism Spectrum','Average',2,13),
('Parent','13-18','combined','Autism Spectrum','Above Average',14,45);