CREATE TABLE `tsi_ds` (
  `CommentID`                    varchar(255) NOT NULL DEFAULT '',
  `UserID`                       varchar(255) DEFAULT NULL,
  `Examiner`                     varchar(255) DEFAULT NULL,
  `Testdate`                     timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
  `Date_taken`                   date DEFAULT NULL,
  `Candidate_Age`                varchar(255) DEFAULT NULL,
  `Window_Difference`            int(11) DEFAULT NULL,
  
  `contact_date`        date DEFAULT NULL,
  `contact_date_status` enum('not_answered') DEFAULT NULL,
  `contacted_by`        varchar(255) DEFAULT NULL,
  `contacted_by_status` enum('not_answered') DEFAULT NULL,
  
  `child_ethnicity`  enum('hispanic','non_hispanic','not_answered') DEFAULT NULL,
  `mother_ethnicity` enum('hispanic','non_hispanic','not_answered') DEFAULT NULL,
  `father_ethnicity` enum('hispanic','non_hispanic','not_answered') DEFAULT NULL,
  
  `candidate_race` varchar(255) DEFAULT NULL,
  `mother_race`    varchar(255) DEFAULT NULL,
  `father_race`    varchar(255) DEFAULT NULL,

  `primary_language`        varchar(255) DEFAULT NULL,
  `primary_language_status` enum('not_answered') DEFAULT NULL,
  
  `mother_occupation`        varchar(255) DEFAULT NULL,
  `mother_occupation_status` enum('not_answered') DEFAULT NULL,
  `mother_education`         enum('not_answered','some_hs','hs','some_college_2yr_degree','college_degree','some_grad_school','grad_degree') DEFAULT NULL,
  `mother_dob_date`          date DEFAULT NULL,
  `mother_dob_date_status`   enum('not_answered') DEFAULT NULL,
  
  `father_occupation`        varchar(255) DEFAULT NULL,
  `father_occupation_status` enum('not_answered') DEFAULT NULL,
  `father_education`         enum('not_answered','some_hs','hs','some_college_2yr_degree','college_degree','some_grad_school','grad_degree') DEFAULT NULL,
  `father_dob_date`          date DEFAULT NULL,
  `father_dob_date_status`   enum('not_answered') DEFAULT NULL,
    
  `ses_income` enum('less_than_25K','25K-35K','35K-50K','50K-75K','75K-100K','100K-150K','150K-200K','over_200K','not_answered') DEFAULT NULL,
  
  `nb_siblings`                enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `dob_sibling1_date`          date DEFAULT NULL,
  `dob_sibling1_date_status`   enum('not_answered') DEFAULT NULL,
  `dob_sibling2_date`          date DEFAULT NULL,
  `dob_sibling2_date_status`   enum('not_answered') DEFAULT NULL,
  `dob_sibling3_date`          date DEFAULT NULL,
  `dob_sibling3_date_status`   enum('not_answered') DEFAULT NULL,
  `dx_sibling1`           varchar(255) DEFAULT NULL,
  `dx_sibling2`           varchar(255) DEFAULT NULL,
  `dx_sibling3`           varchar(255) DEFAULT NULL,
  `dx_sibling1_status`    enum('not_answered') DEFAULT NULL,
  `dx_sibling2_status`    enum('not_answered') DEFAULT NULL,
  `dx_sibling3_status`    enum('not_answered') DEFAULT NULL,
  `relation_sibling1`     enum('half_sibling','full_sibling','step_sibling','not_answered') DEFAULT NULL,
  `relation_sibling2`     enum('half_sibling','full_sibling','step_sibling','not_answered') DEFAULT NULL,
  `relation_sibling3`     enum('half_sibling','full_sibling','step_sibling','not_answered') DEFAULT NULL,
  `live_at_home_sibling1` enum('yes','no','part_time','not_answered') DEFAULT NULL,
  `live_at_home_sibling2` enum('yes','no','part_time','not_answered') DEFAULT NULL,
  `live_at_home_sibling3` enum('yes','no','part_time','not_answered') DEFAULT NULL,

  `nature_referral`              enum('self_referred', 'referred_registry', 'referred_clinic', 'other', 'not_answered') DEFAULT NULL,
  `nature_referral_other`        varchar(255) DEFAULT NULL,
  `nature_referral_other_status` enum('not_answered') DEFAULT NULL,

  `enrolled_research_registry`             enum('yes','no','not_answered') DEFAULT NULL,
  `enrolled_research_registry_list`        varchar(255) DEFAULT NULL, 
  `enrolled_research_registry_list_status` enum('not_answered') DEFAULT NULL,
  `enrolled_research_study`                enum('yes','no','not_answered') DEFAULT NULL,
  `enrolled_research_study_list`           varchar(255) DEFAULT NULL, 
  `enrolled_research_study_list_status`    enum('not_answered') DEFAULT NULL,

  `neurological_problems`            enum('yes','no','not_answered') DEFAULT NULL,
  `genetic_conditions`               enum('yes','no','not_answered') DEFAULT NULL,
  `seizures_or_neuro_disorder`       enum('yes','no','not_answered') DEFAULT NULL,
  `cns_problems`                     enum('yes','no','not_answered') DEFAULT NULL,
  `congenital_heart_problems`        enum('yes','no','not_answered') DEFAULT NULL,
  `atriaseptal_defects`              enum('yes','no','not_answered') DEFAULT NULL,
  `hearing_vision_impairments`       enum('yes','no','not_answered') DEFAULT NULL,
  `diabetes`                         enum('yes','no','not_answered') DEFAULT NULL,
  `complications_birth`              enum('yes','no','not_answered') DEFAULT NULL,
  `premature_birth`                  enum('yes','no','not_answered') DEFAULT NULL,
  `weeks_gestation`                  float DEFAULT NULL,
  `weeks_gestation_status`           enum('not_answered') DEFAULT NULL,
  `low_birth_weight`                 enum('yes','no','not_answered') DEFAULT NULL,
  `delivery_problems`                enum('yes','no','not_answered') DEFAULT NULL,
  `tetralogy_fallot`                 enum('yes','no','not_answered') DEFAULT NULL,
  `gastrointestinal_malformation`    enum('yes','no','not_answered') DEFAULT NULL,
  `in_utero_exposure`                enum('yes','no','not_answered') DEFAULT NULL,
  `in_utero_substance`               varchar(255) DEFAULT NULL,
  `in_utero_substance_status`        enum('not_answered') DEFAULT NULL,
  `in_utero_substance_amount`        varchar(255) DEFAULT NULL,
  `in_utero_substance_amount_status` enum('not_answered') DEFAULT NULL,
  `in_utero_time_exposure`           varchar(255) DEFAULT NULL,
  `in_utero_time_exposure_status`    enum('not_answered') DEFAULT NULL,
  `further_information`              mediumtext,
  `further_information_status`       enum('not_answered') DEFAULT NULL,
  
  `med_his_q_1_med_surgical_problems`       enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_2_hospitalized`                enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_3_surgery`                     enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_3_surgery_describe`            varchar(255) DEFAULT NULL,
  `med_his_q_3_surgery_describe_status`     enum('not_answered') DEFAULT NULL,
  `med_his_q_4_metal`                       enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_5_medications`                 enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_5_medications_describe`        varchar(255) DEFAULT NULL,
  `med_his_q_5_medications_describe_status` enum('not_answered') DEFAULT NULL,
  `med_his_q_6_allergies`                   enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_6_allergies_describe`          varchar(255) DEFAULT NULL,
  `med_his_q_6_allergies_describe_status`   enum('not_answered') DEFAULT NULL,
  `med_his_q_7_doctor`                      enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_8_brain_MRI`                   enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_8_brain_MRI_results`           varchar(255) DEFAULT NULL,
  `med_his_q_8_brain_MRI_results_status`    enum('not_answered') DEFAULT NULL,
  `med_his_q_8_brain_MRI_notes`             varchar(255) DEFAULT NULL,
  `med_his_q_8_brain_MRI_notes_status`      enum('not_answered') DEFAULT NULL,
  `med_his_q_9_anethesia`                   enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_9_anethesia_problems`          varchar(255) DEFAULT NULL,
  `med_his_q_9_anethesia_problems_status`   enum('not_answered') DEFAULT NULL,
  `med_his_q_9_anethesia_notes`             varchar(255) DEFAULT NULL,
  `med_his_q_9_anethesia_notes_status`      enum('not_answered') DEFAULT NULL,
  `med_his_q_10_nap`                        enum('yes','no','not_answered') DEFAULT NULL,
  `med_his_q_10_nap_how_long`               varchar(255) DEFAULT NULL,
  `med_his_q_10_nap_how_long_status`        enum('not_answered') DEFAULT NULL,
  `med_his_q_11_likelihood_sleep`           enum('1','2','3','4','5','6','7','8','9','10','not_answered') DEFAULT NULL,
  
  `city_of_birth` varchar(255) DEFAULT NULL,
  `city_of_birth_status` enum('not_answered') DEFAULT NULL,
 
  `exc_inc_meets_criteria`   enum('yes','no','not_answered') DEFAULT NULL,
  `exc_inc_contraindication` enum('yes','no','not_answered') DEFAULT NULL,
  `goto_next_level`          enum('yes','no','not_answered') DEFAULT NULL,
  `possible_exclusion`       enum('yes','no','not_answered') DEFAULT NULL,
  `review_details`           varchar(255) DEFAULT NULL,
  `review_details_status`    enum('not_answered') DEFAULT NULL,
  `review_date`              date DEFAULT NULL,
  `review_date_status`       enum('not_answered') DEFAULT NULL,
  `not_finish0` varchar(10)  default NULL,
  `not_finish1` varchar(10)  default NULL,
  `not_finish2` varchar(10)  default NULL,
  `not_finish3` varchar(10)  default NULL,   
  PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
