CREATE TABLE `TSI_SA` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`contact_date` date default NULL,
`contact_date_status` enum('not_answered') default NULL,
`same_home` enum('yes','no','not_answered') default NULL,
`divorced_or_separated` enum('yes','no','not_answered') default NULL,
`mother_education` enum('not_answered','some_hs','some_college_2yr_degree','college_degree','some_grad_school','grad_degree') default NULL,
`father_education` enum('not_answered','some_hs','some_college_2yr_degree','college_degree','some_grad_school','grad_degree') default NULL,
`household_ses_1` enum('less_than_25K','25K-35K','35K-50K','50K-75K','75K-100K','100K-150K','150K-200K','over_200K','not_answered') default NULL,
`household_ses_2` enum('less_than_25K','25K-35K','35K-50K','50K-75K','75K-100K','100K-150K','150K-200K','over_200K','not_answered') default NULL,
`neurological_problems` enum('yes','no','not_answered') default NULL,
`neurological_problems_list` varchar(255) default NULL,
`genetic_conditions` enum('yes','no','not_answered') default NULL,
`genetic_conditions_list` varchar(255) default NULL,
`seizures` enum('yes','no','not_answered') default NULL,
`cns_problems` enum('yes','no','not_answered') default NULL,
`cns_problems_list` varchar(255) default NULL,
`congenital_problems` enum('yes','no','not_answered') default NULL,
`congenital_problems_list` varchar(255) default NULL,
`hearing_vision_problems` enum('yes','no','not_answered') default NULL,
`hearing_vision_problems_desc` varchar(255) default NULL,
`weight_pounds` varchar(255) default NULL,
`weight_ounces` varchar(255) default NULL,
`surgical_problems` enum('yes','no','not_answered') default NULL,
`ever_hospitalized` enum('yes','no','not_answered') default NULL,
`surgery` enum('yes','no','not_answered') default NULL,
`surgery_desc` varchar(255) default NULL,
`surgery_when` varchar(255) default NULL,
`metal_implants` enum('yes','no','not_answered') default NULL,
`dental_implants` enum('yes','no','not_answered') default NULL,
`dental_implants_remove` varchar(255) default NULL,
`medications` enum('yes','no','not_answered') default NULL,
`medications_list` varchar(255) default NULL,
`allergies` enum('yes','no','not_answered') default NULL,
`allergies_desc` varchar(255) default NULL,
`seen_doctor` enum('yes','no','not_answered') default NULL,
`seen_doctor_desc` varchar(255) default NULL,
`new_diagnoses` varchar(255) default NULL,
PRIMARY KEY  (`CommentID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;