CREATE TABLE `UCD_Charge_GI_History` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(255) default NULL,

                            `Examiner` varchar(255) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`q1_previous` enum('0','1','2','3','4') default NULL,
`q1_current` enum('0','1','2','3','4') default NULL,
`q2_previous` enum('0','1','2','3','4') default NULL,
`q2_current` enum('0','1','2','3','4') default NULL,
`q3_previous` enum('0','1','2','3','4') default NULL,
`q3_current` enum('0','1','2','3','4') default NULL,
`q4_previous` enum('0','1','2','3','4') default NULL,
`q4_current` enum('0','1','2','3','4') default NULL,
`q5_previous` enum('0','1','2','3','4') default NULL,
`q5_current` enum('0','1','2','3','4') default NULL,
`q6_previous` enum('0','1','2','3','4') default NULL,
`q6_current` enum('0','1','2','3','4') default NULL,
`q7_previous` enum('0','1','2','3','4') default NULL,
`q7_current` enum('0','1','2','3','4') default NULL,
`q7_description` varchar(255) default NULL,
`q8_previous` enum('0','1','2','3','4') default NULL,
`q8_current` enum('0','1','2','3','4') default NULL,
`q9_previous` enum('0','1','2','3','4') default NULL,
`q9_current` enum('0','1','2','3','4') default NULL,
`q10_previous` enum('0','1','2','3','4') default NULL,
`q10_current` enum('0','1','2','3','4') default NULL,
`q11_previous` enum('yes','no') default NULL,
`q11_current` enum('yes','no') default NULL,
`q11_description` varchar(255) default NULL,
`q12_previous` enum('yes','no') default NULL,
`q12_current` enum('yes','no') default NULL,
`q12_diet_restricted_by` enum('child','parent','doctor') default NULL,
`q12_reasons` varchar(255) default NULL,
`q12_foods` varchar(255) default NULL,
`q13_previous` enum('yes','no') default NULL,
`q13_current` enum('yes','no') default NULL,
`q13_description` varchar(255) default NULL,
`gastrointestinal_diagnosis_given` enum('yes','no') default NULL,
`gastrointestinal_diagnosis` text default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
