CREATE TABLE `Vineland_SA` (
`CommentID` varchar(255) NOT NULL default '',

                            `UserID` varchar(90) default NULL,

                            `Examiner` varchar(90) default NULL,

                            `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                            `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(90) default NULL,
`Window_Difference` varchar(90) default NULL,
`File_name` varchar(90) default NULL,
`File_type` varchar(90) default NULL,
`Status` varchar(90) default NULL,
`Data_dir` varchar(90) default NULL,
`adapt_behave_comp_STD_SCORE` varchar(90) default NULL,
`adapt_behave_comp_90_CI` varchar(90) default NULL,
`adapt_behave_comp_PERCENTILE` varchar(90) default NULL,
`adapt_behave_comp_SS_Minus_Mean_SS` varchar(90) default NULL,
`adapt_behave_comp_strength_weakness` varchar(90) default NULL,
`adapt_behave_comp_base_rate` varchar(90) default NULL,
`communication_STD_SCORE` varchar(90) default NULL,
`communication_90_CI` varchar(90) default NULL,
`communication_PERCENTILE` varchar(90) default NULL,
`communication_SS_Minus_Mean_SS` varchar(90) default NULL,
`communication_strength_weakness` varchar(90) default NULL,
`communication_base_rate` varchar(90) default NULL,
`daily_living_skills_STD_SCORE` varchar(90) default NULL,
`daily_living_skills_90_CI` varchar(90) default NULL,
`daily_living_skills_PERCENTILE` varchar(90) default NULL,
`daily_living_skills_SS_Minus_Mean_SS` varchar(90) default NULL,
`daily_living_skills_strength_weakness` varchar(90) default NULL,
`daily_living_skills_base_rate` varchar(90) default NULL,
`socialization_STD_SCORE` varchar(90) default NULL,
`socialization_90_CI` varchar(90) default NULL,
`socialization_PERCENTILE` varchar(90) default NULL,
`socialization_SS_Minus_Mean_SS` varchar(90) default NULL,
`socialization_strength_weakness` varchar(90) default NULL,
`socialization_base_rate` varchar(90) default NULL,
`motor_skills_STD_SCORE` varchar(90) default NULL,
`motor_skills_90_CI` varchar(90) default NULL,
`motor_skills_PERCENTILE` varchar(90) default NULL,
`motor_skills_SS_Minus_Mean_SS` varchar(90) default NULL,
`motor_skills_strength_weakness` varchar(90) default NULL,
`motor_skills_base_rate` varchar(90) default NULL,
`receptive_RAW_SCORE` varchar(90) default NULL,
`receptive_v_Scale_Score` varchar(90) default NULL,
`receptive_age_equiv` varchar(90) default NULL,
`receptive_growth_scale_value` varchar(90) default NULL,
`receptive_percent_estimated` varchar(90) default NULL,
`receptive_vs_minus_mean_vs` varchar(90) default NULL,
`receptive_strength_weakness` varchar(90) default NULL,
`receptive_base_rate` varchar(90) default NULL,
`expressive_RAW_SCORE` varchar(90) default NULL,
`expressive_v_Scale_Score` varchar(90) default NULL,
`expressive_age_equiv` varchar(90) default NULL,
`expressive_growth_scale_value` varchar(90) default NULL,
`expressive_percent_estimated` varchar(90) default NULL,
`expressive_vs_minus_mean_vs` varchar(90) default NULL,
`expressive_strength_weakness` varchar(90) default NULL,
`expressive_base_rate` varchar(90) default NULL,
`written_RAW_SCORE` varchar(90) default NULL,
`written_v_Scale_Score` varchar(90) default NULL,
`written_age_equiv` varchar(90) default NULL,
`written_growth_scale_value` varchar(90) default NULL,
`written_percent_estimated` varchar(90) default NULL,
`written_vs_minus_mean_vs` varchar(90) default NULL,
`written_strength_weakness` varchar(90) default NULL,
`written_base_rate` varchar(90) default NULL,
`personal_RAW_SCORE` varchar(90) default NULL,
`personal_v_Scale_Score` varchar(90) default NULL,
`personal_age_equiv` varchar(90) default NULL,
`personal_growth_scale_value` varchar(90) default NULL,
`personal_percent_estimated` varchar(90) default NULL,
`personal_vs_minus_mean_vs` varchar(90) default NULL,
`personal_strength_weakness` varchar(90) default NULL,
`personal_base_rate` varchar(90) default NULL,
`domestic_RAW_SCORE` varchar(90) default NULL,
`domestic_v_Scale_Score` varchar(90) default NULL,
`domestic_age_equiv` varchar(90) default NULL,
`domestic_growth_scale_value` varchar(90) default NULL,
`domestic_percent_estimated` varchar(90) default NULL,
`domestic_vs_minus_mean_vs` varchar(90) default NULL,
`domestic_strength_weakness` varchar(90) default NULL,
`domestic_base_rate` varchar(90) default NULL,
`community_RAW_SCORE` varchar(90) default NULL,
`community_v_Scale_Score` varchar(90) default NULL,
`community_age_equiv` varchar(90) default NULL,
`community_growth_scale_value` varchar(90) default NULL,
`community_percent_estimated` varchar(90) default NULL,
`community_vs_minus_mean_vs` varchar(90) default NULL,
`community_strength_weakness` varchar(90) default NULL,
`community_base_rate` varchar(90) default NULL,
`inter_pers_rel_RAW_SCORE` varchar(90) default NULL,
`inter_pers_rel_v_Scale_Score` varchar(90) default NULL,
`inter_pers_rel_age_equiv` varchar(90) default NULL,
`inter_pers_rel_growth_scale_value` varchar(90) default NULL,
`inter_pers_rel_percent_estimated` varchar(90) default NULL,
`inter_pers_rel_vs_minus_mean_vs` varchar(90) default NULL,
`inter_pers_rel_strength_weakness` varchar(90) default NULL,
`inter_pers_rel_base_rate` varchar(90) default NULL,
`play_leisure_RAW_SCORE` varchar(90) default NULL,
`play_leisure_v_Scale_Score` varchar(90) default NULL,
`play_leisure_age_equiv` varchar(90) default NULL,
`play_leisure_growth_scale_value` varchar(90) default NULL,
`play_leisure_percent_estimated` varchar(90) default NULL,
`play_leisure_vs_minus_mean_vs` varchar(90) default NULL,
`play_leisure_strength_weakness` varchar(90) default NULL,
`play_leisure_base_rate` varchar(90) default NULL,
`copy_skills_RAW_SCORE` varchar(90) default NULL,
`copy_skills_v_Scale_Score` varchar(90) default NULL,
`copy_skills_age_equiv` varchar(90) default NULL,
`copy_skills_growth_scale_value` varchar(90) default NULL,
`copy_skills_percent_estimated` varchar(90) default NULL,
`copy_skills_vs_minus_mean_vs` varchar(90) default NULL,
`copy_skills_strength_weakness` varchar(90) default NULL,
`copy_skills_base_rate` varchar(90) default NULL,
`gross_motor_RAW_SCORE` varchar(90) default NULL,
`gross_motor_v_Scale_Score` varchar(90) default NULL,
`gross_motor_age_equiv` varchar(90) default NULL,
`gross_motor_growth_scale_value` varchar(90) default NULL,
`gross_motor_percent_estimated` varchar(90) default NULL,
`gross_motor_vs_minus_mean_vs` varchar(90) default NULL,
`gross_motor_strength_weakness` varchar(90) default NULL,
`gross_motor_base_rate` varchar(90) default NULL,
`fine_motor_RAW_SCORE` varchar(90) default NULL,
`fine_motor_v_Scale_Score` varchar(90) default NULL,
`fine_motor_age_equiv` varchar(90) default NULL,
`fine_motor_growth_scale_value` varchar(90) default NULL,
`fine_motor_percent_estimated` varchar(90) default NULL,
`fine_motor_vs_minus_mean_vs` varchar(90) default NULL,
`fine_motor_strength_weakness` varchar(90) default NULL,
`fine_motor_base_rate` varchar(90) default NULL,
`other_comments` text default NULL,
PRIMARY KEY  (`CommentID`)

              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `test_names` (`Test_name`, `Full_name`, `Sub_group`) VALUES ('Vineland_SA', 'Vineland Adaptive Behavior Scales, Third Edition (Vineland™-3)', '1');
-- Adding to test battery
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Vineland_SA', '0', '0', 'Y', 'Visit', 1, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Vineland_SA', '0', '0', 'Y', 'Visit', 2, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Vineland_SA', '0', '0', 'Y', 'Visit', 3, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Vineland_SA', '0', '0', 'Y', 'Visit', 9, 'VSA', NULL);
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Vineland_SA', '0', '0', 'Y', 'Visit', 10, 'VSA', NULL);

-- DS SA battery --
INSERT INTO test_battery (Test_name, AgeMinDays, AgeMaxDays, Active, Stage, SubprojectID, Visit_label, CenterID)
VALUES ('Vineland_SA', 0, 0, 'Y', 'Visit', 21, 'VSA', NULL);
