sudo: required

# any language should do it
language: php
cache:
    directories:
        - vendor
env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
  matrix:
    - PHP=7.2 
    - PHP=7.3
services:
- docker

install:
- sudo apt-get update
- sudo apt-get install -y libapparmor1
- pecl install -f ast-0.1.6
- sudo apt-get install npm
- npm install
- composer install
- npm run compile
script:
- npm run lint:php && npm run lint:javascript && docker-compose run -T --rm integration-tests vendor/bin/phpunit --configuration test/phpunit.xml
