language: php


cache:
    directories:
        - vendor

matrix:
  include:
  - php: "7.2"
    env: PHP='7.2'
  - php: "7.3"
    env: PHP='7.3'

before_install:

install:

before_script:
   echo "$PHP";
script:

