language: php


cache:
    directories:
        - vendor
php:
    - "7.2"
env: BROWSER_NAME="chrome" CHROME_HEADLESS="1"
addons:
    chrome: stable

before_install:

install:

before_script:

script:
after_script:
dist: precise
