sudo: required

# any language should do it
language: php

matrix:
  include:
    t: "make"
    t: "integration-tests" 

services:
- docker

install:
- sudo apt-get update
- sudo apt-get install -y libapparmor1
- pecl install -f ast-0.1.6
- sudo apt-get install npm
- make dev

script:
# Unable to initialize database, use the following code to debug. - docker-compose up --build
# docker-compose up --build
- if[ $t == "make" ]; then make checkstatic fi
#  fi 
#- if[ $TEST_SUITE == "integration-tests" ]; then
#  docker-compose run -T --rm $TEST_SUITE vendor/bin/phpunit --configuration test/phpunit.xml
#  fi
