sudo: required

# any language should do it
language: php

matrix:
  include:
  - php: "7.2"
      env:
       - TEST_SUITE=make
       - TEST_SUITE=integration-tests
  - php: "7.3"
      env:
       - TEST_SUITE=make
       - TEST_SUITE=integration-tests

services:
- docker

env:
  - TEST_SUITE=unit-tests
  - TEST_SUITE=integration-tests

install:
- sudo apt-get update
- sudo apt-get install -y libapparmor1
- pecl install -f ast-0.1.6
- sudo apt-get install npm
- make dev

before_script:
- sed -i "s/7.2/$TRAVIS_PHP_VERSION/g" Dockerfile.test.php7

script:
# Unable to initialize database, use the following code to debug. - docker-compose up --build
# docker-compose up --build
#- if[ $TEST_SUITE == "make" ]; then
- make checkstatic
#  fi 
#- if[ $TEST_SUITE == "integration-tests" ]; then
#  docker-compose run -T --rm $TEST_SUITE vendor/bin/phpunit --configuration test/phpunit.xml
#  fi
