language: php


cache:
    directories:
        - vendor

matrix:
  include:
  - php: "7.2"
    env: PHP='7.2'
  - php: "7.3"
    env: PHP='7.3'

before_install:

install:

before_script:
   sed -i "s/7.2/$PHP/g" Dockerfile.test.php7
script:
   cat Dockerfile.test.php7

