language: php
sudo: false
dist: trusty

php:
  - 7.2

env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="htmlunit"
    - CHROMEDRIVER_VERSION="2.38"

matrix:
  include:
    # Add build to run tests against Chrome inside Travis environment
    - php: 7.2
      env: BROWSER_NAME="chrome" CHROME_HEADLESS="1"
      addons:
        chrome: stable

cache:
  directories:
    - $HOME/.composer/cache
    - jar

before_install:
    # Start Xvfb in a desktop screen size,
    # otherwise some tests will fail because the links
    # are hidden when Selenium tries to find them.
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x16"
    #- "export DISPLAY=:99.0"
    #- "sh -e /etc/init.d/xvfb start"
    # Ensure node version is up to date
    - nvm install node
    - mkdir -p project project/libraries
    - pecl install -f ast-0.1.6

install:
  - travis_retry composer self-update
  - composer install
before_script:
  - if [ "$BROWSER_NAME" = "htmlunit" ]; then mkdir chromedriver; wget -q -t 3 https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; unzip chromedriver_linux64 -d chromedriver; fi
  - if [ "$BROWSER_NAME" = "htmlunit" ]; then export CHROMEDRIVER_PATH=$PWD/chromedriver/chromedriver; fi
  - sh -e /etc/init.d/xvfb start
  - if [ ! -f jar/selenium-server-standalone-3.8.1.jar ]; then wget -q -t 3 -P jar https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.1.jar; fi
  - java -Dwebdriver.firefox.marionette=false -Dwebdriver.chrome.driver="$CHROMEDRIVER_PATH" -jar jar/selenium-server-standalone-3.8.1.jar -enablePassThrough false -log ./logs/selenium.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo Waiting for Selenium server on port 4444...; done; echo "Selenium server started"
  - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
  - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"

script:
  - if [ -n "$SAUCELABS" ]; then EXCLUDE_GROUP+="exclude-saucelabs,"; fi
  - if [ "$BROWSER_NAME" = "MicrosoftEdge" ]; then EXCLUDE_GROUP+="exclude-edge,"; fi
  - if [ -n "$EXCLUDE_GROUP" ]; then EXTRA_PARAMS+=" --exclude-group $EXCLUDE_GROUP"; fi
  - ./vendor/bin/phpunit --coverage-clover ./logs/coverage-clover.xml $EXTRA_PARAMS

after_script:
  - if [ -f ./logs/selenium.log ]; then cat ./logs/selenium.log; fi
  - if [ -f ./logs/php-server.log ]; then cat ./logs/php-server.log; fi

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
