sudo: required

# any language should do it
language: php

php:
    - "7.2"
    - "7.3"

services:
- docker

install:
- sudo apt-get update
- sudo apt-get install -y libapparmor1
- pecl install -f ast-0.1.6
- sudo apt-get install npm
- npm install
- composer install
- npm run compile
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then sed -i 's/php7.2/php7.3/g' docker-compose.yml; fi
script:
- npm run lint:php && npm run lint:javascript && docker-compose run -T --rm integration-tests vendor/bin/phpunit --configuration test/phpunit.xml
