version: '3'
  
networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: apache.dockerfile
    container_name: apache
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    links:
      - "mysql:database"
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: l8_1
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:15.7.0-alpine3.10
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    entrypoint: ['npm']
