FROM php:7.2

RUN apt-get update && \
    apt-get install -y mariadb-client zlib1g-dev zip

# Install extensions through the scripts the container provides
RUN docker-php-ext-install pdo_mysql \
  && docker-php-ext-configure zip --with-libzip \
  && docker-php-ext-install zip
