version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.test.db
      args:
        BASE_DIR: /app/
    volumes:
      - ./test/mysql-config:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=LorisTest
      - MYSQL_ROOT_PASSWORD=rootpassword

  selenium:
    image: selenium/standalone-firefox:3.8.1-aluminum
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    environment:
      - SE_OPTS=-enablePassThrough false
    links:
      - web:web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./test/test_instrument:/var/www/html/project/instruments
    environment:
      - LORIS_DB_CONFIG=/var/www/html/test/config.xml
    depends_on:
      - db
    ports:
      - "8000:80"
#    command: php -S 0.0.0.0:8000 -t /app/htdocs /app/htdocs/router.php

  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile.test.php7
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - LORIS_DB_CONFIG=test/config.xml
    depends_on:
      - db
    entrypoint: /app/test/wait-for-services.sh

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test.php7
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - LORIS_DB_CONFIG=test/config.xml
      - SELENIUM_REQUIRED=true
    depends_on:
      - db
      - selenium
      - web
    entrypoint: /app/test/wait-for-services.sh
    links:
      - web:web

