version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.test.db
      args:
        BASE_DIR: /app/
    volumes:
      - ./SQL/0000-00-00-schema.sql:/docker-entrypoint-initdb.d/0000-00-00-schema.sql
      - ./SQL/0000-00-01-Permission.sql:/docker-entrypoint-initdb.d/0000-00-01-Permission.sql
      - ./SQL/0000-00-02-Modules.sql:/docker-entrypoint-initdb.d/0000-00-02-Modules.sql
      - ./SQL/0000-00-03-ConfigTables.sql:/docker-entrypoint-initdb.d/0000-00-03-ConfigTables.sql
      - ./SQL/0000-00-04-Help.sql:/docker-entrypoint-initdb.d/0000-00-04-Help.sql
      - ./SQL/0000-00-05-ElectrophysiologyTables.sql:/docker-entrypoint-initdb.d/0000-00-05-ElectrophysiologyTables.sql
      - ./raisinbread/instruments/instrument_sql/aosi.sql:/docker-entrypoint-initdb.d/0000-00-06-aosi.sql
      - ./raisinbread/instruments/instrument_sql/bmi.sql:/docker-entrypoint-initdb.d/0000-00-07-bmi.sql
      - ./raisinbread/instruments/instrument_sql/medical_history.sql:/docker-entrypoint-initdb.d/0000-00-07-medical_history.sql
      - ./raisinbread/instruments/instrument_sql/mri_parameter_form.sql:/docker-entrypoint-initdb.d/0000-00-08-mri_parameter_form.sql
      - ./raisinbread/instruments/instrument_sql/radiology_review.sql:/docker-entrypoint-initdb.d/0000-00-09-radiology_review.sql
      - ./test/test_instrument/testtest.sql :/docker-entrypoint-initdb.d/0000-00-10-testtest.sql
      - ./raisinbread/RB_files/*.sql:/docker-entrypoint-initdb.d/0000-00-11-*.sql
      - ./test/mysql-config:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=LorisTest
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  selenium:
    image: selenium/standalone-firefox-debug:3.8.1-aluminum
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    environment:
      - SE_OPTS=-enablePassThrough false

  web:
    build:
      context: .
      dockerfile: Dockerfile.test.php7
    volumes:
      - ./:/app
      - ./test/test_instrument:/app/project/instruments
    environment:
      - LORIS_DB_CONFIG=/app/test/config.xml
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t /app/htdocs /app/htdocs/router.php

  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile.test.php7
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - LORIS_DB_CONFIG=test/config.xml
    depends_on:
      - db
    entrypoint: /app/test/wait-for-services.sh

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test.php7
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - LORIS_DB_CONFIG=test/config.xml
      - SELENIUM_REQUIRED=true
    depends_on:
      - db
      - selenium
      - web
    entrypoint: /app/test/wait-for-services.sh

  selenium-debug:
    image: selenium/standalone-firefox-debug:2.53.1
    links:
      - web-debug:web
    ports:
      - "5901:5900"

  web-debug:
    build:
      context: .
      dockerfile: Dockerfile.test.php7.debug
    volumes:
      - ./:/app
      - ./test/test_instrument:/app/project/instruments
    environment:
      - LORIS_DB_CONFIG=/app/test/config.xml
      - XDEBUG_CONFIG=remote_host=${XDEBUG_REMOTE_HOST}
      - PHP_IDE_CONFIG=serverName=LorisTests
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t /app/htdocs /app/htdocs/router.php

  unit-tests-debug:
    build:
      context: .
      dockerfile: Dockerfile.test.php7.debug
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - LORIS_DB_CONFIG=test/config.xml
      - XDEBUG_CONFIG=remote_host=${XDEBUG_REMOTE_HOST}
      - PHP_IDE_CONFIG=serverName=LorisTests
    depends_on:
      - db
    entrypoint: /app/test/wait-for-services.sh

  integration-tests-debug:
    build:
      context: .
      dockerfile: Dockerfile.test.php7.debug
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - LORIS_DB_CONFIG=test/config.xml
      - SELENIUM_REQUIRED=true
      - XDEBUG_CONFIG=remote_host=${XDEBUG_REMOTE_HOST}
      - PHP_IDE_CONFIG=serverName=LorisTests
    links:
      - db
      - selenium-debug:selenium
      - web-debug:web
    entrypoint: /app/test/wait-for-services.sh
