FROM php:7.3-apache

ARG DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip


# Update web root to public
ENV APACHE_DOCUMENT_ROOT /var/www/loris/htdocs/
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf


# Enable mod_rewrite
RUN a2enmod rewrite
