/* This SQL is referenced via htdocs/feedback_mri_popup_ibis.php */
CREATE TABLE `feedback_mri_comments_ibis` (
  `CommentID` int(11) unsigned NOT NULL auto_increment,
  `FileID` int(10) unsigned,
  `SessionID` int(10) unsigned,
  `t1` enum('1', '2', '3'),
  `t1_overall_motion_score` enum('1', '2', '3', '4'),
  `t1_presence_absence_motion` enum('1', '2'),
  `t1_eye_motion` enum('1', '2'),
  `t1_ringing` enum('1', '2'),
  `t1_hemodynamic_artifact` enum('1', '2'),
  `t1_coverage_crop` enum('1', '2'),
  `t1_comment` text,
  `t2` enum('1', '2', '3'),
  `t2_overall_motion_score` enum('1', '2', '3', '4'),
  `t2_presence_absence_motion` enum('1', '2'),
  `t2_eye_motion` enum('1', '2'),
  `t2_ringing` enum('1', '2'),
  `t2_hemodynamic_artifact` enum('1', '2'),
  `t2_coverage_crop` enum('1', '2'),
  `t2_dark_cerebellar_tonsils` enum('1', '2'),
  `t2_comment` text,
  `dwi_qc` enum('1', '2', '3'),
  `dwi_exclusion_reason` enum('1', '2', '3'),
  `dwi_comment` text, 
  `ChangeTime` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`CommentID`),
  KEY `FK_feedback_mri_comments_3` (`FileID`),
  KEY `FK_feedback_mri_comments_4` (`SessionID`),
  CONSTRAINT `FK_feedback_mri_comments_ibis_1` FOREIGN KEY (`SessionID`) REFERENCES `session` (`ID`),
  CONSTRAINT `FK_feedback_mri_comments_ibis_2` FOREIGN KEY (`FileID`) REFERENCES `files` (`FileID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
