-- Remove all instruments from IBIS EP low risk as it is no more needed.
UPDATE test_battery SET Active='N' where SubprojectID='19';

UPDATE test_battery SET Active='N' where test_name='ACEFamilyMedicalHistory' and SubprojectID='18' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='APSI' and SubprojectID='18' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='BISQ' and SubprojectID='18' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='fyi' and SubprojectID='18' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='Infant_social_motivation' and SubprojectID='18' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='ibq_r' and SubprojectID='18' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='med_psych_hist' and SubprojectID='18' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='vrrsb' and SubprojectID='18' and Visit_label='V18';
UPDATE test_battery SET Active='N' where test_name='vrrsb' and SubprojectID='18' and Visit_label='V18-CVD';
UPDATE test_battery SET Active='N' where test_name='CBCL_1_to_5_yrs' and SubprojectID='18' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='HandPreference' and SubprojectID='18' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='BSRC' and SubprojectID='18' and Visit_label='V24-CVD';

UPDATE test_battery SET Active='N' where test_name='ACEFamilyMedicalHistory' and SubprojectID='20' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='APSI' and SubprojectID='20' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='BISQ' and SubprojectID='20' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='fyi' and SubprojectID='20' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='Infant_social_motivation' and SubprojectID='20' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='ibq_r' and SubprojectID='20' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='med_psych_hist' and SubprojectID='20' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='ACEFamilyMedicalHistory' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='APSI' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='BISQ' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='csbs' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='fyi' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='ibq_r' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='Infant_social_motivation' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='med_psych_hist' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='toddler_social_motivation' and SubprojectID='20' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='ACEFamilyMedicalHistory' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='ACE Subject Medical History' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='BISQ' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='BSRC' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='CBCL_1_to_5_yrs' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='HandPreference' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='fyi' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='macarthur_words_gestures' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='m_chat_subject' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='med_psych_hist' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='toddler_social_motivation' and SubprojectID='20' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='vrrsb' and SubprojectID='20' and Visit_label='V24';

UPDATE test_battery SET Active='N' where test_name='ACEFamilyMedicalHistory' and SubprojectID='23' and Visit_label='V06';
UPDATE test_battery SET Active='N' where test_name='ACEFamilyMedicalHistory' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='APSI' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='BISQ' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='csbs' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='fyi' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='ibq_r' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='Infant_social_motivation' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='med_psych_hist' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='toddler_social_motivation' and SubprojectID='23' and Visit_label='V12';
UPDATE test_battery SET Active='N' where test_name='ACEFamilyMedicalHistory' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='ACE Subject Medical History' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='BISQ' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='BSRC' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='CBCL_1_to_5_yrs' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='HandPreference' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='fyi' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='macarthur_words_gestures' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='m_chat_subject' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='med_psych_hist' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='toddler_social_motivation' and SubprojectID='23' and Visit_label='V24';
UPDATE test_battery SET Active='N' where test_name='vrrsb' and SubprojectID='23' and Visit_label='V24';
