ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `ES_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ES_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ES_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ES_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ES_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ES_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ES_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ES_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `SC_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `OR_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OR_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OR_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OR_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OR_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OR_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OR_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OR_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `SP_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_AGE_EQUIV` varchar (100) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_RAW` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_STD_SCORE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_CI` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_PER_RANK` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_NCE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_STANINE` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_GRADE_EQUIV` varchar (100) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_AGE_EQUIV` varchar (100) default NULL;





