ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ERS_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `AWF_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `EC_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `SC_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `OE_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `SP_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SP_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFA_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFS_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_CI` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_GRADE_EQUIV` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `MFM_AGE_EQUIV` varchar (10) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RC_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RC_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RC_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RC_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RC_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_RC_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `LC_ODC_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_ODC_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_ODC_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_ODC_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_ODC_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `LC_ODC_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SC_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SC_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SC_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SC_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SC_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SC_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SB_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SB_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SB_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SB_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SB_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `SC_SB_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `EC_WC_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_WC_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_WC_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_WC_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_WC_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_WC_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `EC_TDO_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_TDO_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_TDO_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_TDO_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_TDO_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_TDO_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `EC_GM_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_GM_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_GM_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_GM_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_GM_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `EC_GM_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORA_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORA_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORA_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORA_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORA_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORA_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORR_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORR_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORR_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORR_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORR_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `ORF_ORR_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `OE_EV_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_EV_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_EV_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_EV_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_EV_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_EV_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `OE_OWF_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_OWF_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_OWF_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_OWF_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_OWF_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_OWF_QD` varchar (50) default NULL;

ALTER TABLE WIAT_III_SA ADD COLUMN `OE_SR_RAW` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_SR_STD_SCORE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_SR_PER_RANK` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_SR_NCE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_SR_STANINE` varchar (10) default NULL;
ALTER TABLE WIAT_III_SA ADD COLUMN `OE_SR_QD` varchar (50) default NULL;








