-- Rename Instruments(Redmine 17815)
UPDATE test_names SET Full_name="ABC2 (Aberrant Behavior Checklist) - Survey" where Full_name="ABC-2";
UPDATE test_names SET Full_name="ACE Family Medical History - Survey" where Full_name="ACE Subject Medical History Survey";
UPDATE test_names SET Full_name="ACE Subject Medical History - Survey" where Full_name="ACEFamilyMedicalHistory - Survey";
UPDATE test_names SET Full_name="ABCL Informant (Adult Informant Behavior Checklist – Ages 18 to 59) - Dad on Mom - Survey" where Full_name="Adult Informant Report Ages 18 -59 aka Adult Informant CBCL (Dad on Mom)";
UPDATE test_names SET Full_name="ABCL Informant (Adult Informant Behavior Checklist - Ages 18 to 59) - Mom on Dad - Survey" where Full_name="Adult Informant Report Ages 18 -59 aka Adult Informant CBCL (Mom On Dad)";
UPDATE test_names SET Full_name="ABCL Self (Adult Self Behavior Checklist - Ages 18 to 59) - Dad - Survey" where Full_name="Adult Self Report Ages 18-59 aka Adult Self CBCL (Dad)";
UPDATE test_names SET Full_name="ABCL Self (Adult Self Behavior Checklist - Ages 18 to 59) - Mom - Survey" where Full_name="Adult Self Report Ages 18-59 aka Adult Self CBCL (Mom)";
UPDATE test_names SET Full_name="AP (Air Pollution) - Survey" where Full_name="Air Pollution";
UPDATE test_names SET Full_name="APSI (Autism Parent Screen for Infants) - Survey" where Full_name="Autism Parent Screen for Infants Survey (APSI Survey)";
UPDATE test_names SET Full_name="BISQ (Brief Infant Sleep Questionnaire) - Survey" where Full_name="Brief Infant Sleep Questionnaire (BISQ - Survey Version)";
UPDATE test_names SET Full_name="BRIEF2 Parent (Behavior Rating Inventory of Executive Functioning) - Survey" where Full_name="BRIEF2 Parent Form";
UPDATE test_names SET Full_name="BRIEF2 Teacher (Behavior Rating Inventory of Executive Functioning) - Survey" where Full_name="BRIEF2 Teacher Form";
UPDATE test_names SET Full_name="CCC2 – Children’s Communication Checklist 2 - Survey" where Full_name="Children Communication Checklist 2";
UPDATE test_names SET Full_name="CBCL (Child Behavior Checklist) 1.5 to 5 years - Survey" where Full_name="CBCL (1.5-5 years)";
UPDATE test_names SET Full_name="CBCL (Child Behavior Checklist) 6 to 18 years - Survey" where Full_name="CBCL (6-18 years)";
UPDATE test_names SET Full_name="Charge GI Form (Gastro Intestinal) - Survey" where Full_name="CHARGE GI History";
UPDATE test_names SET Full_name="CONNERS-3 Parent Short - Survey" where Full_name="CONNERS 3 - Parent Short";
UPDATE test_names SET Full_name="CONNERS-3 Teacher Short - Survey" where Full_name="CONNERS 3 - Teacher Short";
UPDATE test_names SET Full_name="CSHQ (Children's Sleep Habits Questionnaire) - Survey" where Full_name="Children's Sleep Habits Questionnaire";
UPDATE test_names SET Full_name="FYI (First Year Inventory) - Survey" where Full_name="First Year Inventory - Survey Version";
UPDATE test_names SET Full_name="IBIS Perinatal Data Form - Survey" where Full_name="IBIS Perinatal Data Form";
UPDATE test_names SET Full_name="IBQ-R (Infant Behavior Questionnaire - Revised) - Survey" where Full_name="IBQ-R (Infant Behavior Questionnaire) Survey";
UPDATE test_names SET Full_name="SMQ - Infant (Social Motivation Questionnaire - Infant) - Survey" where Full_name="Infant Social Motivation Questionnaire - Survey";
UPDATE test_names SET Full_name="M-CHAT [Revised with Follow-up] - Survey" where Full_name="M-CHAT [Revised with Follow-Up]";
UPDATE test_names SET Full_name="MCDI - Words & Gestures - Survey" where Full_name="MacArthur CDI - Words & Gestures (Survey Version)";
UPDATE test_names SET Full_name="MCDI - Words, Sentences & Gestures - Survey" where Full_name="MCDI - Words, Gestures & Sentences Survey";
UPDATE test_names SET Full_name="MASC2 - Parent (Multidimensional Anxiety Scale for Children - Parent) - Survey" where Full_name="MASC2: PARENT";
UPDATE test_names SET Full_name="MASC2 - Self Report (Multidimensional Anxiety Scale for Children - Self-Report) - Survey" where Full_name="MASC2: SELF-REPORT";
UPDATE test_names SET Full_name="Peer Contact Questionnaire – Survey" where Full_name="Peer Contact Questionnaire";
UPDATE test_names SET Full_name="PSPQ Informant (Personality Styles & Preferences) - Dad on Mom - Survey" where Full_name="PSPQ Dad Self Report (Send to Dad)";
UPDATE test_names SET Full_name="PSPQ Informant (Personality Styles & Preferences) - Mom on Dad - Survey" where Full_name="PSPQ Dad's Report on Mom (Send to Dad)";
UPDATE test_names SET Full_name="PSPQ Self (Personality Styles & Preferences) - Dad - Survey" where Full_name="PSPQ Mom Self Report (Send to Mom)";
UPDATE test_names SET Full_name="PSPQ Self (Personality Styles & Preferences) - Mom - Survey" where Full_name="PSPQ Mom's Report on Dad(Send to Mom)";
UPDATE test_names SET Full_name="QRS Subject (Questionnaire on Resources and Stress - Subject) - Survey" where Full_name="QRS";
UPDATE test_names SET Full_name="RBS–R - Subject (Repetitive Behavior Scale - Revised - Subject) - Survey" where Full_name="RBS-R (Repetive Behavior Scale - Revised)";
UPDATE test_names SET Full_name="RBSC - EC (Repetitive Behavior Scale for Early Childhood - Infant Items) - Survey" where Full_name="Repetitive Behavior Scale for Early Childhood (Infant Items) Survey";
UPDATE test_names SET Full_name="RBSC - EC (Repetitive Behavior Scale for Early Childhood - Supplement) - Survey" where Full_name="Repetitive Behavior Scales Early Childhood Supplement (RBS-ECS)";
UPDATE test_names SET Full_name="SCQ Proband (Social Communication Questionnaire) - Survey" where Full_name="SCQ Proband -Survey";
UPDATE test_names SET Full_name="Seizure Questionnaire - Survey" where Full_name="Seizure Questionnaire";
UPDATE test_names SET Full_name="SEQ3 (Sensory Experiences Questionnaire - Version 3.0) - Survey" where Full_name="Sensory Experiences Questionnaire Version 3.0";
UPDATE test_names SET Full_name="SRS-2 SA - Subject (Social Responsiveness Scale – School Age - Subject) - Dad OR Mom - Survey" where Full_name="SRS-2 School Age (Send to Mom OR Dad)";
UPDATE test_names SET Full_name="SRS-2 SA - Teacher (Social Responsiveness Scale – School Age - Teacher) - Teacher - Survey" where Full_name="SRS-2 School Age (Send to Teacher)";
UPDATE test_names SET Full_name="SRS-2 SA - Proband (Social Responsiveness Scale – School Age - Proband) - Dad OR Mom - Survey" where Full_name="SRS-2 School Age Proband (Send to Mom OR Dad)";
UPDATE test_names SET Full_name="SRS-2 Informant - Dad on Mom (Social Responsiveness Scale – Informant) - Dad on Mom - Survey" where Full_name="SRS2 Dad Self Report (Send to Dad)";
UPDATE test_names SET Full_name="SRS-2 Informant - Mom on Dad (Social Responsiveness Scale – Informant) - Mom on Dad - Survey" where Full_name="SRS2 Dad's Report on Mom (Send to Dad)";
UPDATE test_names SET Full_name="SRS-2 Self (Social Responsiveness Scale – Informant) - Dad - Survey" where Full_name="SRS2 Mom Self Report (Send to Mom)";
UPDATE test_names SET Full_name="SRS-2 Self (Social Responsiveness Scale – Self) – Mom - Survey" where Full_name="SRS2 Mom's Report on Dad (Send to Mom)";
UPDATE test_names SET Full_name="SSCQ (Sibling Social Contact Questionnaire) - Survey" where Full_name="Sibling Social Contact Questionnaire";
UPDATE test_names SET Full_name="SSIS Parent (Social Skills Improvement System) - Survey" where Full_name="SSIS Parent";
UPDATE test_names SET Full_name="SSIS Teacher (Social Skills Improvement System) - Survey" where Full_name="SSIS Teacher: Social Skills Improvement System";
UPDATE test_names SET Full_name="TANNER Staging Questionnaire (Boys) - Survey" where Full_name="TANNER Staging Questionnaire (Boys) Survey";
UPDATE test_names SET Full_name="TANNER Staging Questionnaire (Girls) - Survey" where Full_name="TANNER Staging Questionnaire (Girls) Survey";
UPDATE test_names SET Full_name="TRF (Teacher's Report Form) Ages 6 to 18 - Survey" where Full_name="Teacher's Report Form (TRF) for Ages 6-18";
UPDATE test_names SET Full_name="SMQ - Toddler (Social Motivation Questionnaire - Toddler) - Survey" where Full_name="Toddler Social Motivation Questionnaire -Survey Version";
