ALTER TABLE mri_parameter_form_sa
    ADD COLUMN `t1w_run1_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_passfail`,
    ADD COLUMN `t1w_run2_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_passfail`,
    ADD COLUMN `t1w_run3_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_passfail`,
    ADD COLUMN `t1w_run4_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_passfail`,
    ADD COLUMN `t1w_run5_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_passfail`,
    ADD COLUMN `t1w_run6_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_passfail`,
    ADD COLUMN `t2w_run1_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_passfail`,
    ADD COLUMN `t2w_run2_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_passfail`,
    ADD COLUMN `t2w_run3_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_passfail`,
    ADD COLUMN `t2w_run4_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_passfail`,
    ADD COLUMN `t2w_run5_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_passfail`,
    ADD COLUMN `t2w_run6_facemask`                                       enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_passfail`,

    ADD COLUMN `t1w_run1_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_2_passfail`,
    ADD COLUMN `t1w_run2_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_2_passfail`,
    ADD COLUMN `t1w_run3_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_2_passfail`,
    ADD COLUMN `t1w_run4_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_2_passfail`,
    ADD COLUMN `t1w_run5_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_2_passfail`,
    ADD COLUMN `t1w_run6_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_2_passfail`,
    ADD COLUMN `t2w_run1_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_2_passfail`,
    ADD COLUMN `t2w_run2_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_2_passfail`,
    ADD COLUMN `t2w_run3_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_2_passfail`,
    ADD COLUMN `t2w_run4_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_2_passfail`,
    ADD COLUMN `t2w_run5_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_2_passfail`,
    ADD COLUMN `t2w_run6_2_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_2_passfail`,

    ADD COLUMN `t1w_run1_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_3_passfail`,
    ADD COLUMN `t1w_run2_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_3_passfail`,
    ADD COLUMN `t1w_run3_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_3_passfail`,
    ADD COLUMN `t1w_run4_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_3_passfail`,
    ADD COLUMN `t1w_run5_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_3_passfail`,
    ADD COLUMN `t1w_run6_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_3_passfail`,
    ADD COLUMN `t2w_run1_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_3_passfail`,
    ADD COLUMN `t2w_run2_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_3_passfail`,
    ADD COLUMN `t2w_run3_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_3_passfail`,
    ADD COLUMN `t2w_run4_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_3_passfail`,
    ADD COLUMN `t2w_run5_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_3_passfail`,
    ADD COLUMN `t2w_run6_3_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_3_passfail`,

    ADD COLUMN `t1w_run1_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run1_4_passfail`,
    ADD COLUMN `t1w_run2_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run2_4_passfail`,
    ADD COLUMN `t1w_run3_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run3_4_passfail`,
    ADD COLUMN `t1w_run4_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run4_4_passfail`,
    ADD COLUMN `t1w_run5_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run5_4_passfail`,
    ADD COLUMN `t1w_run6_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t1w_run6_4_passfail`,
    ADD COLUMN `t2w_run1_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run1_4_passfail`,
    ADD COLUMN `t2w_run2_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run2_4_passfail`,
    ADD COLUMN `t2w_run3_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run3_4_passfail`,
    ADD COLUMN `t2w_run4_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run4_4_passfail`,
    ADD COLUMN `t2w_run5_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run5_4_passfail`,
    ADD COLUMN `t2w_run6_4_facemask`                                     enum ('yes','no')                                   DEFAULT NULL AFTER `t2w_run6_4_passfail`,

    CHANGE `dti_sequences_acquired` `cmrr1_dti_sequences_acquired`       enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell` `cmrr1_dti3_shell`                               enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell_attempts` `cmrr1_dti3_shell_attempts`             enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `dti3_shell_num_attempts` `cmrr1_dti3_shell_num_attempts`     enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    CHANGE `6b0` `cmrr1_6b0`                                             enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `6b0_attempts` `cmrr1_6b0_attempts`                           enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `6b0_num_attempts` `cmrr1_6b0_num_attempts`                   enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    CHANGE `dti2_shell` `cmrr1_dti2_shell`                               enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti2_shell_attempts` `cmrr1_dti2_shell_attempts`             enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `dti2_shell_num_attempts` `cmrr1_dti2_shell_num_attempts`     enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    CHANGE `6b0_2` `cmrr1_6b0_2`                                         enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `6b0_2_attempts` `cmrr1_6b0_2_attempts`                       enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `6b0_2_num_attempts` `cmrr1_6b0_2_num_attempts`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    CHANGE `dti1_shell` `cmrr1_dti1_shell`                               enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti1_shell_attempts` `cmrr1_dti1_shell_attempts`             enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `dti1_shell_num_attempts` `cmrr1_dti1_shell_num_attempts`     enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    ADD COLUMN `cmrr1_facemask`                                          enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr1_dti1_shell_num_attempts`,
    CHANGE `dti_comments` `cmrr1_dti_comments`                           text,

    ADD COLUMN `siemens_dti_sequences_acquired`                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable`,
    ADD COLUMN `siemens_dti3_shell`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_dti_sequences_acquired`,
    ADD COLUMN `siemens_dti3_shell_attempts`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_dti3_shell`,
    ADD COLUMN `siemens_dti3_shell_num_attempts`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_dti3_shell_attempts`,
    ADD COLUMN `siemens_6b0`                                             enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_dti3_shell_num_attempts`,
    ADD COLUMN `siemens_6b0_attempts`                                    enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_6b0`,
    ADD COLUMN `siemens_6b0_num_attempts`                                enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_6b0_attempts`,
    ADD COLUMN `siemens_dti2_shell`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_6b0_num_attempts`,
    ADD COLUMN `siemens_dti2_shell_attempts`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_dti2_shell`,
    ADD COLUMN `siemens_dti2_shell_num_attempts`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_dti2_shell_attempts`,
    ADD COLUMN `siemens_6b0_2`                                           enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_dti2_shell_num_attempts`,
    ADD COLUMN `siemens_6b0_2_attempts`                                  enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_6b0_2`,
    ADD COLUMN `siemens_6b0_2_num_attempts`                              enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_6b0_2_attempts`,
    ADD COLUMN `siemens_dti1_shell`                                      enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens_6b0_2_num_attempts`,
    ADD COLUMN `siemens_dti1_shell_attempts`                             enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens_dti1_shell`,
    ADD COLUMN `siemens_dti1_shell_num_attempts`                         enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens_dti1_shell_attempts`,
    ADD COLUMN `siemens_facemask`                                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens_dti1_shell_num_attempts`,
    ADD COLUMN `siemens_dti_comments`                                    text AFTER `siemens_facemask`,

    CHANGE `dti_sequences_acquired_2` `cmrr2_dti_sequences_acquired_2`   enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell_2` `cmrr2_dti3_shell_2`                           enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell_attempts_2` `cmrr2_dti3_shell_attempts_2`         enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `dti3_shell_num_attempts_2` `cmrr2_dti3_shell_num_attempts_2` enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    CHANGE `6b0_2` `cmrr2_6b0_2`                                         enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `6b0_attempts_2` `cmrr2_6b0_attempts_2`                       enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `6b0_num_attempts_2` `cmrr2_6b0_num_attempts_2`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    ADD COLUMN `cmrr2_facemask_2`                                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr2_6b0_num_attempts_2`,
    CHANGE `dti_comments_2` `cmrr2_dti_comments_2`                       text,

    ADD COLUMN `siemens2_dti_sequences_acquired_2`                       enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable_2`,
    ADD COLUMN `siemens2_dti3_shell_2`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens2_dti_sequences_acquired_2`,
    ADD COLUMN `siemens2_dti3_shell_attempts_2`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens2_dti3_shell_2`,
    ADD COLUMN `siemens2_dti3_shell_num_attempts_2`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens2_dti3_shell_attempts_2`,
    ADD COLUMN `siemens2_6b0_2`                                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens2_dti3_shell_num_attempts_2`,
    ADD COLUMN `siemens2_6b0_attempts_2`                                 enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens2_6b0_2`,
    ADD COLUMN `siemens2_6b0_num_attempts_2`                             enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens2_6b0_attempts_2`,
    ADD COLUMN `siemens2_facemask_2`                                     enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens2_6b0_num_attempts_2`,
    ADD COLUMN `siemens2_dti_comments_2`                                 text AFTER `siemens2_facemask_2`,

    CHANGE `dti_sequences_acquired_3` `cmrr3_dti_sequences_acquired_3`   enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell_3` `cmrr3_dti3_shell_3`                           enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell_attempts_3` `cmrr3_dti3_shell_attempts_3`         enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `dti3_shell_num_attempts_3` `cmrr3_dti3_shell_num_attempts_3` enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    CHANGE `6b0_3` `cmrr3_6b0_3`                                         enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `6b0_attempts_3` `cmrr3_6b0_attempts_3`                       enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `6b0_num_attempts_3` `cmrr3_6b0_num_attempts_3`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    ADD COLUMN `cmrr3_facemask_3`                                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr3_6b0_num_attempts_3`,
    CHANGE `dti_comments_3` `cmrr3_dti_comments_3`                       text,

    ADD COLUMN `siemens3_dti_sequences_acquired_3`                       enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable_3`,
    ADD COLUMN `siemens3_dti3_shell_3`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens3_dti_sequences_acquired_3`,
    ADD COLUMN `siemens3_dti3_shell_attempts_3`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens3_dti3_shell_3`,
    ADD COLUMN `siemens3_dti3_shell_num_attempts_3`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens3_dti3_shell_attempts_3`,
    ADD COLUMN `siemens3_6b0_3`                                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens3_dti3_shell_num_attempts_3`,
    ADD COLUMN `siemens3_6b0_attempts_3`                                 enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens3_6b0_3`,
    ADD COLUMN `siemens3_6b0_num_attempts_3`                             enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens3_6b0_attempts_3`,
    ADD COLUMN `siemens3_facemask_3`                                     enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens3_6b0_num_attempts_3`,
    ADD COLUMN `siemens3_dti_comments_3`                                 text AFTER `siemens3_facemask_3`,

    CHANGE `dti_sequences_acquired_4` `cmrr4_dti_sequences_acquired_4`   enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell_4` `cmrr4_dti3_shell_4`                           enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `dti3_shell_attempts_4` `cmrr4_dti3_shell_attempts_4`         enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `dti3_shell_num_attempts_4` `cmrr4_dti3_shell_num_attempts_4` enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    CHANGE `6b0_4` `cmrr4_6b0_4`                                         enum ('complete','partial','none')                  DEFAULT NULL,
    CHANGE `6b0_attempts_4` `cmrr4_6b0_attempts_4`                       enum ('console_pass','console_fail')                DEFAULT NULL,
    CHANGE `6b0_num_attempts_4` `cmrr4_6b0_num_attempts_4`               enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL,
    ADD COLUMN `cmrr4_facemask_4`                                        enum ('yes', 'no')                                  DEFAULT NULL AFTER `cmrr4_6b0_num_attempts_4`,
    CHANGE `dti_comments_4` `cmrr4_dti_comments_4`                       text,

    ADD COLUMN `siemens4_dti_sequences_acquired_4`                       enum ('complete','partial','none')                  DEFAULT NULL AFTER `if_none_partial_unusable_4`,
    ADD COLUMN `siemens4_dti3_shell_4`                                   enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens4_dti_sequences_acquired_4`,
    ADD COLUMN `siemens4_dti3_shell_attempts_4`                          enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens4_dti3_shell_4`,
    ADD COLUMN `siemens4_dti3_shell_num_attempts_4`                      enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens4_dti3_shell_attempts_4`,
    ADD COLUMN `siemens4_6b0_4`                                          enum ('complete','partial','none')                  DEFAULT NULL AFTER `siemens4_dti3_shell_num_attempts_4`,
    ADD COLUMN `siemens4_6b0_attempts_4`                                 enum ('console_pass','console_fail')                DEFAULT NULL AFTER `siemens4_6b0_4`,
    ADD COLUMN `siemens4_6b0_num_attempts_4`                             enum ('0','1','2','3','4','5','6','7','8','9','10') DEFAULT NULL AFTER `siemens4_6b0_attempts_4`,
    ADD COLUMN `siemens4_facemask_4`                                     enum ('yes', 'no')                                  DEFAULT NULL AFTER `siemens4_6b0_num_attempts_4`,
    ADD COLUMN `siemens4_dti_comments_4`                                 text AFTER `siemens4_facemask_4`;