name: Test

on:
   pull_request:
     branches: [ main ]

jobs:
   test_pull_request:
      runs-on: ubuntu-latest
      steps:
        - run: composer self-update 1.10.17
        - run: make dev
        - run: npm run tests:static
