name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4]
    steps:
    - uses: actions/checkout@v2
      env:
        PHP: 7.4
    - name: php version
      run: echo $PWD
    - name: fdsfkdlsfd
      run: echo ${{ PHP }}
    - name: fjdksa
      run: echo ${{ matrix.os }}
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest     
    - name: Install dependencies
      run: make dev
    - name: Run test suite
      run: npm run tests:unit a:${{ matrix.os }}
